# Neural Sequence Model: Char-CNN BiLSTM-CRF



In this notebook, I implement a more sophisticated architecture for the NER task, specifically following the Ma and Hovy (2016) approach. I decided to move away from a basic BiLSTM + Softmax setup because NER requires a better way to handle rare words and label consistency.

- Character embeddings for each word
- CNN over characters to create a character-level word representation
- Pretrained GloVe word embeddings
- Hybrid Embeddings concatenating those CNN-generated character representations with pretrained GloVe word embeddings.
- BiLSTM to read left and right context
- CRF output layer to decode the best label sequence

This architecture is useful for NER because named entities often contain rare or unseen words(OOV words). The character CNN handles the variety, while the CRF ensures the final output is a sequence that actually makes sense.

## 1. Setup

In [1]:
import sys
import os
from collections import Counter
import random
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchcrf import CRF

from tqdm import tqdm
import copy
from itertools import product

from sklearn.metrics import classification_report, precision_recall_fscore_support, confusion_matrix

from seqeval.metrics import f1_score as seq_f1_score
from seqeval.metrics import precision_score as seq_precision_score
from seqeval.metrics import recall_score as seq_recall_score
from seqeval.metrics import classification_report as seq_classification_report
from seqeval.metrics.sequence_labeling import get_entities
from seqeval.scheme import IOB2

In [2]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

In [3]:
set_seed(42)

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

sys.path.append(os.path.abspath(".."))

## 2. Load Data

In [5]:
from src.load_dataset import load_dataset

train_sents, train_tags = load_dataset("../data/raw/train.txt")
valid_sents, valid_tags = load_dataset("../data/raw/valid.txt")
test_sents, test_tags = load_dataset("../data/raw/test.txt")

print(f"Training sentences: {len(train_sents)}")
print(f"Valid sentences: {len(valid_sents)}")
print(f"Testing sentences: {len(test_sents)}")

Training sentences: 14041
Valid sentences: 3250
Testing sentences: 3453

In [6]:
print(train_sents[:5])
print(valid_tags[:5])
print(test_sents[:5])

[['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.'], ['Peter', 'Blackburn'], ['BRUSSELS', '1996-08-22'], ['The', 'European', 'Commission', 'said', 'on', 'Thursday', 'it', 'disagreed', 'with', 'German', 'advice', 'to', 'consumers', 'to', 'shun', 'British', 'lamb', 'until', 'scientists', 'determine', 'whether', 'mad', 'cow', 'disease', 'can', 'be', 'transmitted', 'to', 'sheep', '.'], ['Germany', "'s", 'representative', 'to', 'the', 'European', 'Union', "'s", 'veterinary', 'committee', 'Werner', 'Zwingmann', 'said', 'on', 'Wednesday', 'consumers', 'should', 'buy', 'sheepmeat', 'from', 'countries', 'other', 'than', 'Britain', 'until', 'the', 'scientific', 'advice', 'was', 'clearer', '.']]
[['O', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], ['B-LOC', 'O'], ['B-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ORG', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ORG', 'O', 'B-ORG', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ORG', 'O'], ['O', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-LOC', 'I-LOC', 'O', 'B-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-LOC', 'O', 'B-PER', 'I-PER', 'O', 'O', 'O', 'O', 'O']]
[['SOCCER', '-', 'JAPAN', 'GET', 'LUCKY', 'WIN', ',', 'CHINA', 'IN', 'SURPRISE', 'DEFEAT', '.'], ['Nadim', 'Ladki'], ['AL-AIN', ',', 'United', 'Arab', 'Emirates', '1996-12-06'], ['Japan', 'began', 'the', 'defence', 'of', 'their', 'Asian', 'Cup', 'title', 'with', 'a', 'lucky', '2-1', 'win', 'against', 'Syria', 'in', 'a', 'Group', 'C', 'championship', 'match', 'on', 'Friday', '.'], ['But', 'China', 'saw', 'their', 'luck', 'desert', 'them', 'in', 'the', 'second', 'match', 'of', 'the', 'group', ',', 'crashing', 'to', 'a', 'surprise', '2-0', 'defeat', 'to', 'newcomers', 'Uzbekistan', '.']]

## 3. Build Word, Character, and Label Vocabularies

The model needs three vocabularies:

- a word vocabulary for word embeddings
- a character vocabulary for the character CNN
- a tag vocabulary for the NER labels

I lowercase words for the word vocabulary to improve coverage with pretrained embeddings. However, I still preserve the original token form when building character inputs. This is important because the character CNN is meant to capture subword and morphological signals such as capitalisation, suffixes, punctuation, and word shape.

In [7]:
# To count each word appears in the training set
word_counter = Counter(word.lower() for sent in train_sents for word in sent)

# To count each character appears in the training set
char_counter = Counter(ch for sent in train_sents for word in sent for ch in word)

# To extract sorted tag list from the training set
tag_list = sorted(set(tag for sent_tags in train_tags for tag in sent_tags))

I sorted the tags to keep the ID mapping consistent. Since sets are unordered, sorting ensures the same tag gets the same index every time I run the code.

In [8]:
PAD_TOKEN = '<PAD>'
UNK_TOKEN = '<UNK>'
PAD_CHAR = '<PAD>'
UNK_CHAR = '<UNK>'


# Initialize dictionaries with PAD_TOKEN and UNK_TOKEN
word_to_id = {PAD_TOKEN: 0, UNK_TOKEN: 1}
char_to_id = {PAD_CHAR: 0, UNK_CHAR: 1}

# Append each word to word_to_id and give ID
for word, count in word_counter.items():
    word_to_id[word] = len(word_to_id)

# Append each word to char_to_id and give ID
for ch, count in char_counter.items():
    char_to_id[ch] = len(char_to_id)

# Assign an ID for each tag
tag_to_id = {tag: idx for idx, tag in enumerate(tag_list)}

In [9]:
print(f'Word vocab size: {len(word_to_id)}')
print(f'Char vocab size: {len(char_to_id)}')
print(f'Number of tags: {len(tag_to_id)}')
print(tag_to_id)

Word vocab size: 21011
Char vocab size: 86
Number of tags: 9
{'B-LOC': 0, 'B-MISC': 1, 'B-ORG': 2, 'B-PER': 3, 'I-LOC': 4, 'I-MISC': 5, 'I-ORG': 6, 'I-PER': 7, 'O': 8}

In [10]:
id_to_tag = {idx: tag for idx, tag in enumerate(tag_list)}

In [11]:
id_to_tag

{0: 'B-LOC',
 1: 'B-MISC',
 2: 'B-ORG',
 3: 'B-PER',
 4: 'I-LOC',
 5: 'I-MISC',
 6: 'I-ORG',
 7: 'I-PER',
 8: 'O'}

I convert words,characters and tags into IDs because the model cannot work with text, only numbers. 

I set "0" **<PAD>** to handle padding when sentences have different lengths, and set it to 0 so it can be ignored during training. 

Secondly, add **<UNK>** to handle unseen words or characters, and set it to 1 , so the model can still learn a representation for unknown inputs. 

Lastly, I assign a unique ID to each word, character and tags from the training data so everything converted into numerical form for the model.

## 4. Dataset and Padding

This step is all about organizing our raw lists into structured **batches**.

In [12]:
# Converts the word into the index
def word_to_index(word):
    # Assigned default value to 1, 
    # If word not in dictionary treat it UNKNOWN WORD
    return word_to_id.get(word.lower(), word_to_id[UNK_TOKEN])

# Converts the character into the index 
# and create the sentence with char ID's
def chars_to_indices(word):
    return [char_to_id.get(ch, char_to_id[UNK_CHAR]) for ch in word]

# Pytorch wrapper
class NERDataset(Dataset):
    def __init__(self, sentences, tags):
        self.sentences = sentences
        self.tags = tags

    # Define to access length of sentences
    def __len__(self):
        return len(self.sentences)

    # Define to access tags and sentences using indexing
    def __getitem__(self, idx):
        words = self.sentences[idx]
        tags = self.tags[idx]
        
        word_ids = [word_to_index(word) for word in words] # Extract word index
        char_ids = [chars_to_indices(word) for word in words] # Extract char index
        tag_ids = [tag_to_id[tag] for tag in tags] # # Extract tag index

        return {'words': words, # word
                'word_ids': word_ids, # word id, input for word embedding
                'char_ids': char_ids, # char id, input for char embedding
                'tag_ids': tag_ids # tag id
                }

In [13]:
from src.collate_batches import collate_batches
from functools import partial

# Creates collate_fn function assigned tag_to_id parameter
collate_fn = partial(collate_batches, tag_to_id=tag_to_id)

batch_size = 32 # Initialize batch size

# Create train loader, validation loader and test loader
train_loader = DataLoader(NERDataset(train_sents, train_tags), batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
valid_loader = DataLoader(NERDataset(valid_sents, valid_tags), batch_size=batch_size, shuffle=False, collate_fn=collate_fn)
test_loader = DataLoader(NERDataset(test_sents, test_tags), batch_size=batch_size, shuffle=False, collate_fn=collate_fn)

I create the NERDataset class as a PyTorch wrapper. Inside `__getitem__`, I take one sentence and convert its words, characters, and tags into their corresponding IDs and it return everything in a dictionary.

After that, implement a custom collate_batches function to handle batching and padding. I use batch size 32, practical choice that works well in most NLP tasks and it is a good balance between speed and memory. I also use dynamic padding so that each batch is padded only to its maximum length, which makes training more efficient and avoids unnecessary padding. 

The mask ensures that padded positions do not affect the model. This is important because the BiLSTM and CRF layers should only learn from actual tokens, not padded values.

Lastly, I shuffle the training data to help the model generalise better, but I do not shuffle validation and test data so the evaluation stays consistent.

In [14]:
example_batch = next(iter(train_loader))
print(f"word_ids: {example_batch['word_ids'].shape}")
print(f"char_ids: {example_batch['char_ids'].shape}")
print(f"tag_ids: {example_batch['tag_ids'].shape}")
print(f"mask: {example_batch['mask'].shape}")

word_ids: torch.Size([32, 47])
char_ids: torch.Size([32, 47, 13])
tag_ids: torch.Size([32, 47])
mask: torch.Size([32, 47])

In [15]:
len(example_batch['words'][0])

10

In [16]:
print(f"sentence: {example_batch['words'][0]}")
print(example_batch['mask'][0])
print(example_batch['word_ids'][0])
print(example_batch['char_ids'][0])

sentence: ['SOCCER', '-', 'RUSSIA', 'AND', 'BRAZIL', 'DRAW', '2-2', 'IN', 'FRIENDLY', '.']
tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False])
tensor([1756,  637, 1157,   85, 2696, 2661, 2353,  230, 7221,   10,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0])
tensor([[26, 56, 37, 37,  2, 25,  0,  0,  0,  0,  0,  0,  0],
        [31,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [25,  3, 26, 26, 61, 65,  0,  0,  0,  0,  0,  0,  0],
        [65, 48, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [18, 25, 65, 44, 61, 27,  0,  0,  0,  0,  0,  0,  0],
        [64, 25, 65, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [34, 31, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [61, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [51, 25, 61,  2, 48, 64, 27, 73,  0,  0,  0,  0,  0],
        [21,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [17]:
example_batch['char_ids'][0].shape

torch.Size([47, 13])

## 5. Pretrained GloVe word embeddings

I use pretrained GloVe embeddings to provide the model with a solid foundation of word meanings learned from a massive external corpus. This is a crucial step for my project because the initial OOV analysis revealed a significant gap. About 12.18% of words in the test set and 8.36% in the validation set were never seen during training. 

When I look at entity types, 

-   the PER category has a very high OOV rate, reaching 54.02% in the test set. This means many person names are not seen during training. 
-   ORG entities also have relatively high OOV rates 23.32%, showing that some categories are more sparse than others.

Because of this, if the model only relies on training data, it may struggle with unseen words. Pretrained embeddings help solve this by placing similar words closer in the embedding space, so the model can generalise better.

When it comes to the "why I choose GloVe instead of Word2Vec",  because it uses global word co-occurrence information, which gives more stable semantic representations. Also, GloVe embeddings are widely available in standard formats and are easy to use.

Furthermore, based on the dataset statistics, 

- The training set contains around 203k tokens across approximately 14k sentences, indicating a small to moderate size dataset. 
- Sentence lengths are relatively short, with a median of around 9–11 tokens and 95% of sentences below 40 tokens.

This analysis guides my choice of embedding dimension.

Using very high-dimensional embeddings, softened the model with unnecessary extra parameters. Since the dataset is not very large, I use 100d embedding as they provide enough capacity to represent word meaning while keeping the model efficient and reducing the risk of overfitting.

In [18]:
with open("../data/glove/wiki_giga_2024_100.txt", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

the 0.306717 -0.32053 -0.39364699999999997 0.08282600000000001 0.073522 -0.409154 -0.265564 -0.23693999999999998 -0.305832 0.74529 0.214341 0.27678099999999994 -0.152797 -0.127524 0.11952500000000002 0.640965 -0.175869 0.160711 0.47797799999999996 -0.160939 -0.150093 0.674601 -0.099565 0.021881999999999985 -0.032770999999999995 0.368641 -0.08701900000000007 -0.13332599999999997 0.170143 0.15693399999999996 0.6775059999999999 -0.099686 0.392113 0.37343400000000004 -5.736062 0.413845 0.477368 -0.04169700000000001 0.38310900000000003 0.12015199999999998 -0.20947 0.605104 0.23635299999999998 0.15113100000000002 -0.508865 0.671239 -0.300263 -0.267927 2.549487 0.06717699999999999 0.217224 -0.031316 0.05231 0.119321 -0.332154 -0.8079040000000001 -0.546453 -0.04439199999999999 -0.281657 0.286647 0.32577500000000004 -0.021960000000000007 -0.636903 -0.268063 0.247956 -0.402493 0.276707 -0.275139 0.20115899999999998 0.08284399999999997 0.591695 -0.017126999999999948 -0.09226899999999999 0.39200799999999997 0.078245 -0.04990700000000001 0.235151 0.457376 -0.111987 -0.05691 0.06509200000000001 0.10651200000000001 0.9833700000000001 0.6081669999999999 -0.250386 -0.44967999999999997 0.185177 0.056664000000000006 0.296632 -0.24443900000000002 -0.019506999999999997 0.324114 0.460377 -0.04133099999999999 -0.333933 0.06237300000000001 -0.11478300000000001 0.127164 -0.02989900000000001 0.24711300000000003

, 0.022531999999999996 0.320788 -0.295389 0.61206 0.767145 0.266352 -0.215857 0.02751200000000001 -0.364298 0.37444 0.22959799999999997 0.097367 -0.175404 -0.133931 0.04780899999999999 -0.21933899999999995 -0.028425000000000006 -0.213325 -0.694809 -0.363699 0.007584000000000007 0.174892 -0.25993000000000005 0.484391 -0.03788 0.12768800000000002 -0.22585899999999998 0.015317999999999998 -0.09641599999999999 0.11412800000000001 -0.419879 0.348794 -0.502019 0.154648 -4.866347 0.302259 0.03592300000000004 0.338694 -0.203098 0.04616399999999998 -0.09178399999999999 0.24286799999999997 0.26193 0.36846100000000004 0.066353 1.207422 0.22256099999999998 0.17989 2.780558 0.05538500000000002 0.379366 -0.38585 -0.33546600000000004 0.03431000000000001 -0.419285 0.03121099999999999 -0.017715999999999996 0.23199999999999998 0.5564 -0.13279800000000003 0.016859 -0.23133399999999998 0.194549 -0.051671999999999996 -0.20049300000000003 0.10592299999999999 0.058381000000000016 0.25366000000000005 -0.306578 -0.03605399999999999 -0.195459 0.008589000000000013 0.388561 -0.3172 -0.27020500000000003 0.03609200000000001 0.018797 -0.205368 -0.006506999999999985 0.071884 -0.098216 0.183838 0.009167999999999982 0.5505359999999999 0.611872 0.152103 -0.012454 -0.291144 -0.31479999999999997 0.141704 -0.31404 0.093639 -0.251115 -0.505637 -0.538312 -0.422704 -0.680767 0.155399 0.324172 0.06897700000000001

. -0.075626 0.36995500000000003 -0.349095 -0.030794000000000002 0.258182 -0.09033 -0.121666 -0.16773999999999997 0.13382100000000002 0.22788799999999998 -0.13915200000000003 -0.118993 0.17035899999999998 0.29836599999999996 0.027396999999999977 0.33781799999999995 0.16159400000000002 -0.191168 -0.14315300000000003 -0.18119400000000002 -0.080677 0.256582 -0.09169100000000001 0.127094 -0.123001 0.24414399999999997 -0.370986 0.130183 -0.085863 -0.124973 0.06433 0.669755 0.05122199999999999 0.14919 -5.154602 0.298214 0.23285300000000003 -0.173202 0.087315 -0.259364 -0.6151150000000001 0.06021199999999999 0.217021 0.09152300000000002 -0.05606100000000001 1.0962159999999999 0.140408 -0.199139 2.462894 -0.330588 0.390039 -0.151522 -0.269224 -0.09874100000000001 -0.413607 -0.24167899999999998 -0.449461 -0.060261 0.059852 0.218875 0.18197599999999997 -0.308204 -0.075567 -0.24466900000000003 0.15988600000000003 -0.07924500000000001 0.041881999999999975 0.17276300000000003 -0.037951 -0.220034 -0.229537 0.173499 -0.26580000000000004 -0.253259 -0.217682 -0.393058 -0.12898800000000002 0.179841 -0.12226599999999999 0.142645 0.094697 -0.023773999999999962 -0.456714 0.9317 -0.092499 0.175973 0.092606 0.26004099999999997 0.551341 -0.22065400000000002 0.172405 0.213564 -0.08877399999999999 -0.03480200000000001 -0.351306 -0.07118199999999997 -0.10045699999999999 0.088199 0.17028799999999997 0.257782

of 0.487177 -0.193218 -0.49086300000000005 -0.149596 -0.096297 -0.028723000000000012 -0.865399 -0.68128 -0.348396 0.879677 1.226995 -0.15376800000000002 0.051680000000000004 0.328863 -0.24846500000000002 -0.14158500000000002 -0.11965999999999999 -0.17630900000000002 -0.004018999999999995 0.226617 -0.019252000000000005 0.231474 0.41627899999999995 -0.31146599999999997 0.350501 0.623147 -0.048505999999999994 0.444642 -0.26823600000000003 0.112441 -0.022201000000000005 0.011538 1.004663 -0.210586 -5.348688 0.6777169999999999 0.5293680000000001 0.35358599999999996 0.100031 0.573126 -0.28428 0.018901 0.609741 0.02038200000000001 -0.685319 1.372962 -0.138276 0.202165 2.547048 -0.05627399999999999 0.15548599999999999 0.286924 0.07470500000000002 0.27965 -0.830346 -0.534159 -0.400945 -0.17041900000000001 0.28926300000000005 0.07095299999999999 -0.322517 0.23517400000000002 -0.25637699999999997 -0.812458 0.362899 -0.282198 0.713008 -0.02795900000000001 0.32622399999999996 -0.047894999999999965 -0.183155 -0.022980999999999988 0.09442199999999998 0.342811 0.07405 0.008420999999999998 0.45737500000000003 0.028581 -0.06950800000000001 -0.440637 -0.169564 0.341569 0.37258699999999995 -0.114298 -0.225383 0.365151 -0.10386500000000001 0.300648 -0.218422 0.139739 -0.36844299999999996 0.033894999999999995 0.128268 0.24138500000000002 -0.5022880000000001 -0.42181199999999996 -0.018413 -0.348117 0.447189 -0.200448

to 0.17394 -0.10466 -0.729389 0.373954 0.5811029999999999 0.012022000000000005 -0.308268 -0.219555 0.254265 -0.20730200000000001 -0.035552 -0.137131 0.10429300000000002 -0.443801 -0.6356850000000001 -0.723644 0.08070800000000002 0.5212519999999999 0.319435 -0.546933 -0.21446400000000002 -0.054630999999999985 0.184281 -0.45198999999999995 0.45628 0.24538599999999994 -0.25619600000000003 -0.186353 0.03639600000000001 -0.298276 0.12464799999999998 -0.051843999999999994 0.246887 -0.009172 -5.280305 0.121787 -0.40334500000000006 -0.32355 -0.0028719999999999857 -0.15690099999999998 -0.373408 -0.17880900000000002 -0.06271899999999997 -0.232052 -0.11066899999999999 0.40438699999999994 0.325183 0.360639 2.9436739999999997 -0.101794 -0.146727 -0.46002 -0.602007 -0.066105 -1.427999 -0.499579 -0.039386000000000004 0.318227 -0.578248 0.094882 0.61041 -0.11227699999999999 -0.484421 -0.44207300000000005 0.021160999999999985 -0.17100900000000002 0.053563 -0.622849 -0.212814 -0.362263 -0.886979 0.055782 0.070311 -0.268179 -0.506691 -0.130203 0.015109000000000011 0.233872 -0.113485 0.551537 0.10431200000000002 -0.234596 0.339977 1.300433 0.04050800000000001 -0.596113 -0.113356 0.423937 0.664012 0.03237799999999999 0.8615630000000001 0.5924510000000001 -0.348283 0.184023 -0.388102 0.19828600000000002 -0.018146 0.242697 0.06084200000000001 0.21607800000000002

I initialise embeddings for unseen words using a normal distribution with a small standard deviation 0.5, so that they are similar in scale to pretrained GloVe vectors, which are typically in the range of approximately [-1, 1] with a standard deviation around 0.5–0.6. Instead of assigning identical zero vectors to all unknown words, this helps the model learn meaningful representations. 

`float32`-4 bytes per value- is used instead of float64 -8 bytes per value- because it is more efficient in terms of memory and computation. Float64 doubles the memory usage and slows down training. Also, GPUs and Pytorch are optimized for float32.

In [19]:
from src.load_dataset import load_glove

word_embeddings, glove_found = load_glove("../data/glove/wiki_giga_2024_100.txt", word_to_id)

During implementation, I encountered a case where a GloVe vectors (102d) did not match the expected embedding dimension. ValueError occured when constructing the embedding matrix. To handle this, I added a dimension check to ensure only valid vectors are used.

In [20]:
vocab = len(word_to_id)
print(f"Matched GloVe vectors: {glove_found}")
print(f"Coverage: {(glove_found / vocab):.2%}")

Matched GloVe vectors: 18327
Coverage: 87.23%

The pretrained GloVe embeddings cover a substantial portion of the vocabulary, with 18,327 words successfully matched 87.32%. This suggests that most frequent words benefit from pretrained semantic representations.

However, some words remain unmatched and are initialised randomly, which may affect performance, especially for rare entities such as person names.

## 6. Model Architecture

1. Each word is represented with a word embedding.
2. Each word also gets a character representation from a CNN over character embeddings.
3. The word embedding and character representation are concatenated.
4. A BiLSTM reads the sentence from both directions.
5. A CRF layer decodes the best BIO label sequence.

In [21]:
class CharCNN(nn.Module):

    def __init__(self, num_chars, char_embedding_dim, char_out_channels, kernel_size=3, padding_idx=0):
        super().__init__()

        self.char_embedding = nn.Embedding(num_chars, char_embedding_dim, padding_idx=padding_idx)

        self.cnn = nn.Conv1d(in_channels=char_embedding_dim, out_channels=char_out_channels, kernel_size=kernel_size,
                             padding=kernel_size // 2)

        self.relu = nn.ReLU()


    def forward(self, char_ids):
        batch, sent_len, word_len = char_ids.shape

        flatten_chars = char_ids.reshape(batch * sent_len, word_len)
        char_emb = self.char_embedding(flatten_chars)
        char_emb = char_emb.permute(0, 2, 1)
        cnn_out = self.relu(self.cnn(char_emb))

        pooled = torch.max(cnn_out, dim=2).values

        char_rep = pooled.reshape(batch, sent_len, -1)

        return char_rep

In [22]:
class CharCNNBiLSTMCRF(nn.Module):

    def __init__(self,word_embeddings, num_char, num_tags, 
                char_embedding_dim=30, char_out_channel=50,
                lstm_hidden_dim = 200, dropout=0.2):

        super().__init__()

        self.word_emb = nn.Embedding.from_pretrained(word_embeddings, freeze=False, padding_idx=word_to_id[PAD_TOKEN])
        
        self.char_cnn = CharCNN(num_chars=num_char, char_embedding_dim=char_embedding_dim, char_out_channels=char_out_channel,
                                padding_idx=char_to_id[PAD_CHAR])

        self.dropout = nn.Dropout(dropout)

        self.bilstm = nn.LSTM(input_size=word_embeddings.shape[1] + char_out_channel, hidden_size=lstm_hidden_dim,
                              batch_first=True, bidirectional=True)

        # Convert each output into emissions for each tag
        self.emissions = nn.Linear(lstm_hidden_dim * 2, num_tags)

        self.crf = CRF(num_tags, batch_first=True)


    def forward(self, word_ids, char_ids, tags=None, mask=None):
        
        word_emb = self.word_emb(word_ids)  # [B, S, word_emb_dim]
        char_emb = self.char_cnn(char_ids)  # [B, S, char_out_channels]

        x = torch.cat([word_emb, char_emb], dim=-1)

        bilstm_out, _ = self.bilstm(x) # [B, S, hidden_dim]
        bilstm_out = self.dropout(bilstm_out)

        emissions = self.emissions(bilstm_out)

        if tags is not None:

            loss = -self.crf(emissions, tags, mask=mask.bool(), reduction="token_mean")

            return loss

        preds = self.crf.decode(emissions, mask=mask.bool())

        return preds

## 7. Training Loop And Validation by Model Architecture and Hyperparameter Tunning

In [23]:
def move_to_device(batch, device):

    return {key: value.to(device) if torch.is_tensor(value) else value for key, value in batch.items()}

In [24]:
def train(model, train_data, val_data, lr, epochs):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    epoch_results = []
    best_val_f1 = -1
    best_model_state = None
    best_epoch = 0
    patience = 3
    epochs_no_improve = 0

    for epoch_num in range(epochs):

        total_loss_train = 0
        train_preds = []
        train_true_labels = []

        model.train()

        for batch in tqdm(train_data):

            batch = move_to_device(batch, device)

            word_ids = batch["word_ids"]
            char_ids = batch["char_ids"]
            labels = batch["tag_ids"]
            mask = batch["mask"].bool()

            optimizer.zero_grad()
            
            
            loss = model(word_ids, char_ids, tags=labels, mask=mask)

            loss.backward()
            optimizer.step()      

            total_loss_train += loss.item()

            with torch.no_grad():

                pred_ids = model(word_ids, char_ids, mask=mask)

                for true_labels, pred_labels, sent_mask in zip(labels.cpu().tolist(), pred_ids, mask.cpu().tolist()):

                    length = sum(sent_mask)

                    train_true_labels.append([id_to_tag[label] for label in true_labels[:length]])
                    train_preds.append([id_to_tag[label] for label in pred_labels[:length]])

        train_f1 = seq_f1_score(train_true_labels, train_preds, mode="strict", scheme=IOB2, average="macro", zero_division=0)


        model.eval()

        total_loss_val = 0
        val_true_labels = []
        val_preds = []

        with torch.no_grad():

            for batch in val_data:
            
                batch = move_to_device(batch, device)
                word_ids = batch["word_ids"]
                char_ids = batch["char_ids"]
                labels = batch["tag_ids"]
                mask = batch["mask"].bool()

                val_loss = model(word_ids, char_ids, tags=labels, mask=mask)

                pred_ids = model(word_ids, char_ids, mask=mask)

                total_loss_val += val_loss.item()

                for true_labels, pred_labels, sent_mask in zip(labels.cpu().tolist(), pred_ids, mask.cpu().tolist()):

                    length = sum(sent_mask)

                    val_true_labels.append([id_to_tag[label] for label in true_labels[:length]])

                    val_preds.append([id_to_tag[label] for label in pred_labels[:length]])

            val_f1 = seq_f1_score(val_true_labels, val_preds, mode="strict", scheme=IOB2, average="macro", zero_division=0)

            # save best model weights by validation macro F1
            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_epoch = epoch_num + 1
                best_model_state = copy.deepcopy(model.state_dict())
                epochs_no_improve = 0

            else:
                epochs_no_improve += 1


            results = {"Epoch": epoch_num + 1, 
                       "train_loss": round(total_loss_train / len(train_data), 3), 
                       "val_loss": round(total_loss_val / len(val_data), 3),
                       "val_f1": round(val_f1, 3),
                       "train_f1": round(train_f1, 3)}


            epoch_results.append(results)

            print(f'Epochs: {epoch_num+1} | Train Loss: {total_loss_train / len(train_data):.3f} | Train F1: {train_f1:.3f}')
            print(f'Val loss: {total_loss_val/len(val_data):.3f} | Val F1: {val_f1:.3f}')

            if epochs_no_improve >= patience:

                print(f"Early stopping after epoch {epoch_num + 1}")
                break

    # Load best weights 
    model.load_state_dict(best_model_state)

    print(f"Best model from epoch {best_epoch} Val Macro F1 = {best_val_f1:.3f}")

    return model, epoch_results, best_epoch

In [57]:
model = CharCNNBiLSTMCRF(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                        char_embedding_dim=30, char_out_channel=50,
                        lstm_hidden_dim = 200, dropout=0.2).to(device)


EPOCHS = 10
LR = 1e-3

In [ ]:
model, results = train(model, train_loader, valid_loader, LR, EPOCHS)

100%|██████████| 439/439 [00:27<00:00, 15.82it/s]

Epochs: 1 | Train Loss: 0.250 | Train F1: 0.687
Val loss: 0.100 | Val F1: 0.823

100%|██████████| 439/439 [00:27<00:00, 15.74it/s]

Epochs: 2 | Train Loss: 0.056 | Train F1: 0.907
Val loss: 0.065 | Val F1: 0.863

100%|██████████| 439/439 [00:29<00:00, 14.95it/s]

Epochs: 3 | Train Loss: 0.032 | Train F1: 0.949
Val loss: 0.067 | Val F1: 0.875

100%|██████████| 439/439 [00:29<00:00, 15.08it/s]

Epochs: 4 | Train Loss: 0.019 | Train F1: 0.970
Val loss: 0.064 | Val F1: 0.876

100%|██████████| 439/439 [00:28<00:00, 15.67it/s]

Epochs: 5 | Train Loss: 0.012 | Train F1: 0.982
Val loss: 0.080 | Val F1: 0.872

100%|██████████| 439/439 [00:27<00:00, 16.09it/s]

Epochs: 6 | Train Loss: 0.007 | Train F1: 0.990
Val loss: 0.069 | Val F1: 0.863

100%|██████████| 439/439 [00:27<00:00, 15.79it/s]

Epochs: 7 | Train Loss: 0.005 | Train F1: 0.995
Val loss: 0.073 | Val F1: 0.862
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.876

The CharCNN-BiLSTM-CRF model achieved a best validation macro F1 score of `0.876` at epoch 4 and the model learned quickly.

After `epoch 4`, the validation F1 started to decrease while the training F1 continued to improve. This suggests that the model began to overfit the training data. Early stopping helped prevent further overfitting by selecting the best-performing model on the validation set.

The model performs well, but the gap `0.119` between `training F1 0.995` and `validation F1 0.876` indicates some overfitting. Further hyperparameter tuning may improve generalization slightly.

In [59]:
param_lr = [1e-3, 1e-4, 5e-4]
dropouts = [0.2, 0.3, 0.5]

In [62]:
search_results = []

for lr, dropout in product(param_lr, dropouts):

    model = CharCNNBiLSTMCRF(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                            char_embedding_dim=30, char_out_channel=50,
                            lstm_hidden_dim = 200, dropout=dropout).to(device)

    _, results, best_epoch = train(model, train_loader, valid_loader, lr, EPOCHS)

    best_epoch_result = results[best_epoch - 1]

    search_results.append({"learning_rate": lr,
                           "dropout": dropout,
                           "Best Epoch": best_epoch,
                           "Train Loss": best_epoch_result["train_loss"],
                           "Val Loss": best_epoch_result["val_loss"],
                           "Train F1": best_epoch_result["train_f1"],
                           "Validation F1": best_epoch_result["val_f1"],
                           "Train-Val Gap": (best_epoch_result["train_f1"] - best_epoch_result["val_f1"])})

100%|██████████| 439/439 [00:27<00:00, 16.15it/s]

Epochs: 1 | Train Loss: 0.248 | Train F1: 0.690
Val loss: 0.095 | Val F1: 0.840

100%|██████████| 439/439 [00:29<00:00, 14.72it/s]

Epochs: 2 | Train Loss: 0.057 | Train F1: 0.907
Val loss: 0.071 | Val F1: 0.859

100%|██████████| 439/439 [00:26<00:00, 16.36it/s]

Epochs: 3 | Train Loss: 0.032 | Train F1: 0.948
Val loss: 0.065 | Val F1: 0.869

100%|██████████| 439/439 [00:27<00:00, 16.11it/s]

Epochs: 4 | Train Loss: 0.019 | Train F1: 0.971
Val loss: 0.063 | Val F1: 0.878

100%|██████████| 439/439 [00:27<00:00, 16.12it/s]

Epochs: 5 | Train Loss: 0.012 | Train F1: 0.982
Val loss: 0.077 | Val F1: 0.865

100%|██████████| 439/439 [00:27<00:00, 16.08it/s]

Epochs: 6 | Train Loss: 0.007 | Train F1: 0.991
Val loss: 0.072 | Val F1: 0.867

100%|██████████| 439/439 [00:27<00:00, 16.21it/s]

Epochs: 7 | Train Loss: 0.004 | Train F1: 0.994
Val loss: 0.083 | Val F1: 0.866
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.878

100%|██████████| 439/439 [00:27<00:00, 15.79it/s]

Epochs: 1 | Train Loss: 0.257 | Train F1: 0.684
Val loss: 0.105 | Val F1: 0.810

100%|██████████| 439/439 [00:28<00:00, 15.61it/s]

Epochs: 2 | Train Loss: 0.059 | Train F1: 0.904
Val loss: 0.077 | Val F1: 0.852

100%|██████████| 439/439 [00:28<00:00, 15.61it/s]

Epochs: 3 | Train Loss: 0.033 | Train F1: 0.945
Val loss: 0.103 | Val F1: 0.822

100%|██████████| 439/439 [00:27<00:00, 15.69it/s]

Epochs: 4 | Train Loss: 0.020 | Train F1: 0.968
Val loss: 0.074 | Val F1: 0.872

100%|██████████| 439/439 [00:27<00:00, 15.80it/s]

Epochs: 5 | Train Loss: 0.012 | Train F1: 0.982
Val loss: 0.087 | Val F1: 0.856

100%|██████████| 439/439 [00:27<00:00, 16.07it/s]

Epochs: 6 | Train Loss: 0.008 | Train F1: 0.989
Val loss: 0.090 | Val F1: 0.864

100%|██████████| 439/439 [00:27<00:00, 15.71it/s]

Epochs: 7 | Train Loss: 0.005 | Train F1: 0.994
Val loss: 0.106 | Val F1: 0.859
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.872

100%|██████████| 439/439 [00:27<00:00, 16.03it/s]

Epochs: 1 | Train Loss: 0.264 | Train F1: 0.668
Val loss: 0.107 | Val F1: 0.808

100%|██████████| 439/439 [00:27<00:00, 15.95it/s]

Epochs: 2 | Train Loss: 0.063 | Train F1: 0.896
Val loss: 0.084 | Val F1: 0.847

100%|██████████| 439/439 [00:28<00:00, 15.39it/s]

Epochs: 3 | Train Loss: 0.036 | Train F1: 0.938
Val loss: 0.081 | Val F1: 0.845

100%|██████████| 439/439 [00:27<00:00, 15.80it/s]

Epochs: 4 | Train Loss: 0.023 | Train F1: 0.962
Val loss: 0.089 | Val F1: 0.852

100%|██████████| 439/439 [00:28<00:00, 15.51it/s]

Epochs: 5 | Train Loss: 0.014 | Train F1: 0.978
Val loss: 0.073 | Val F1: 0.868

100%|██████████| 439/439 [00:27<00:00, 15.82it/s]

Epochs: 6 | Train Loss: 0.010 | Train F1: 0.983
Val loss: 0.081 | Val F1: 0.869

100%|██████████| 439/439 [00:27<00:00, 15.70it/s]

Epochs: 7 | Train Loss: 0.007 | Train F1: 0.989
Val loss: 0.080 | Val F1: 0.865

100%|██████████| 439/439 [00:27<00:00, 15.73it/s]

Epochs: 8 | Train Loss: 0.005 | Train F1: 0.993
Val loss: 0.099 | Val F1: 0.851

100%|██████████| 439/439 [00:27<00:00, 15.84it/s]

Epochs: 9 | Train Loss: 0.004 | Train F1: 0.994
Val loss: 0.099 | Val F1: 0.861
Early stopping after epoch 9
Best model from epoch 6 Val Macro F1 = 0.869

100%|██████████| 439/439 [00:29<00:00, 15.09it/s]

Epochs: 1 | Train Loss: 0.718 | Train F1: 0.040
Val loss: 0.496 | Val F1: 0.217

100%|██████████| 439/439 [00:27<00:00, 15.98it/s]

Epochs: 2 | Train Loss: 0.332 | Train F1: 0.464
Val loss: 0.295 | Val F1: 0.579

100%|██████████| 439/439 [00:28<00:00, 15.50it/s]

Epochs: 3 | Train Loss: 0.210 | Train F1: 0.673
Val loss: 0.221 | Val F1: 0.679

100%|██████████| 439/439 [00:28<00:00, 15.64it/s]

Epochs: 4 | Train Loss: 0.155 | Train F1: 0.756
Val loss: 0.184 | Val F1: 0.737

100%|██████████| 439/439 [00:28<00:00, 15.35it/s]

Epochs: 5 | Train Loss: 0.125 | Train F1: 0.802
Val loss: 0.153 | Val F1: 0.770

100%|██████████| 439/439 [00:27<00:00, 15.92it/s]

Epochs: 6 | Train Loss: 0.104 | Train F1: 0.832
Val loss: 0.136 | Val F1: 0.792

100%|██████████| 439/439 [00:28<00:00, 15.19it/s]

Epochs: 7 | Train Loss: 0.088 | Train F1: 0.856
Val loss: 0.142 | Val F1: 0.789

100%|██████████| 439/439 [00:28<00:00, 15.60it/s]

Epochs: 8 | Train Loss: 0.076 | Train F1: 0.871
Val loss: 0.125 | Val F1: 0.808

100%|██████████| 439/439 [00:27<00:00, 15.80it/s]

Epochs: 9 | Train Loss: 0.066 | Train F1: 0.886
Val loss: 0.116 | Val F1: 0.815

100%|██████████| 439/439 [00:27<00:00, 15.74it/s]

Epochs: 10 | Train Loss: 0.059 | Train F1: 0.898
Val loss: 0.116 | Val F1: 0.822
Best model from epoch 10 Val Macro F1 = 0.822

100%|██████████| 439/439 [00:28<00:00, 15.62it/s]

Epochs: 1 | Train Loss: 0.738 | Train F1: 0.031
Val loss: 0.521 | Val F1: 0.171

100%|██████████| 439/439 [00:27<00:00, 15.70it/s]

Epochs: 2 | Train Loss: 0.350 | Train F1: 0.435
Val loss: 0.301 | Val F1: 0.572

100%|██████████| 439/439 [00:28<00:00, 15.60it/s]

Epochs: 3 | Train Loss: 0.220 | Train F1: 0.654
Val loss: 0.225 | Val F1: 0.658

100%|██████████| 439/439 [00:27<00:00, 15.93it/s]

Epochs: 4 | Train Loss: 0.160 | Train F1: 0.744
Val loss: 0.175 | Val F1: 0.742

100%|██████████| 439/439 [00:27<00:00, 15.73it/s]

Epochs: 5 | Train Loss: 0.126 | Train F1: 0.796
Val loss: 0.146 | Val F1: 0.774

100%|██████████| 439/439 [00:27<00:00, 15.70it/s]

Epochs: 6 | Train Loss: 0.103 | Train F1: 0.829
Val loss: 0.130 | Val F1: 0.793

100%|██████████| 439/439 [00:28<00:00, 15.49it/s]

Epochs: 7 | Train Loss: 0.087 | Train F1: 0.852
Val loss: 0.121 | Val F1: 0.801

100%|██████████| 439/439 [00:27<00:00, 15.99it/s]

Epochs: 8 | Train Loss: 0.075 | Train F1: 0.869
Val loss: 0.112 | Val F1: 0.812

100%|██████████| 439/439 [00:27<00:00, 15.80it/s]

Epochs: 9 | Train Loss: 0.066 | Train F1: 0.883
Val loss: 0.107 | Val F1: 0.814

100%|██████████| 439/439 [00:27<00:00, 15.68it/s]

Epochs: 10 | Train Loss: 0.058 | Train F1: 0.896
Val loss: 0.094 | Val F1: 0.829
Best model from epoch 10 Val Macro F1 = 0.829

100%|██████████| 439/439 [00:30<00:00, 14.40it/s]

Epochs: 1 | Train Loss: 0.727 | Train F1: 0.034
Val loss: 0.503 | Val F1: 0.200

100%|██████████| 439/439 [00:29<00:00, 14.81it/s]

Epochs: 2 | Train Loss: 0.344 | Train F1: 0.435
Val loss: 0.295 | Val F1: 0.574

100%|██████████| 439/439 [00:28<00:00, 15.27it/s]

Epochs: 3 | Train Loss: 0.214 | Train F1: 0.655
Val loss: 0.215 | Val F1: 0.684

100%|██████████| 439/439 [00:30<00:00, 14.21it/s]

Epochs: 4 | Train Loss: 0.152 | Train F1: 0.751
Val loss: 0.165 | Val F1: 0.753

100%|██████████| 439/439 [00:29<00:00, 15.07it/s]

Epochs: 5 | Train Loss: 0.118 | Train F1: 0.803
Val loss: 0.143 | Val F1: 0.775

100%|██████████| 439/439 [00:27<00:00, 15.85it/s]

Epochs: 6 | Train Loss: 0.098 | Train F1: 0.832
Val loss: 0.127 | Val F1: 0.791

100%|██████████| 439/439 [00:29<00:00, 15.08it/s]

Epochs: 7 | Train Loss: 0.084 | Train F1: 0.851
Val loss: 0.112 | Val F1: 0.799

100%|██████████| 439/439 [00:29<00:00, 14.72it/s]

Epochs: 8 | Train Loss: 0.074 | Train F1: 0.869
Val loss: 0.109 | Val F1: 0.810

100%|██████████| 439/439 [00:29<00:00, 14.75it/s]

Epochs: 9 | Train Loss: 0.066 | Train F1: 0.880
Val loss: 0.100 | Val F1: 0.823

100%|██████████| 439/439 [00:28<00:00, 15.20it/s]

Epochs: 10 | Train Loss: 0.059 | Train F1: 0.893
Val loss: 0.098 | Val F1: 0.821
Best model from epoch 9 Val Macro F1 = 0.823

100%|██████████| 439/439 [00:29<00:00, 14.81it/s]

Epochs: 1 | Train Loss: 0.354 | Train F1: 0.544
Val loss: 0.157 | Val F1: 0.758

100%|██████████| 439/439 [00:28<00:00, 15.31it/s]

Epochs: 2 | Train Loss: 0.089 | Train F1: 0.856
Val loss: 0.097 | Val F1: 0.825

100%|██████████| 439/439 [00:28<00:00, 15.37it/s]

Epochs: 3 | Train Loss: 0.055 | Train F1: 0.909
Val loss: 0.078 | Val F1: 0.856

100%|██████████| 439/439 [00:27<00:00, 15.94it/s]

Epochs: 4 | Train Loss: 0.038 | Train F1: 0.937
Val loss: 0.068 | Val F1: 0.869

100%|██████████| 439/439 [00:27<00:00, 15.98it/s]

Epochs: 5 | Train Loss: 0.027 | Train F1: 0.956
Val loss: 0.074 | Val F1: 0.861

100%|██████████| 439/439 [00:27<00:00, 16.02it/s]

Epochs: 6 | Train Loss: 0.019 | Train F1: 0.969
Val loss: 0.082 | Val F1: 0.851

100%|██████████| 439/439 [00:28<00:00, 15.66it/s]

Epochs: 7 | Train Loss: 0.013 | Train F1: 0.979
Val loss: 0.087 | Val F1: 0.855
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.869

100%|██████████| 439/439 [00:27<00:00, 15.98it/s]

Epochs: 1 | Train Loss: 0.345 | Train F1: 0.554
Val loss: 0.155 | Val F1: 0.755

100%|██████████| 439/439 [00:26<00:00, 16.29it/s]

Epochs: 2 | Train Loss: 0.087 | Train F1: 0.856
Val loss: 0.091 | Val F1: 0.840

100%|██████████| 439/439 [00:27<00:00, 16.08it/s]

Epochs: 3 | Train Loss: 0.054 | Train F1: 0.906
Val loss: 0.087 | Val F1: 0.851

100%|██████████| 439/439 [00:27<00:00, 15.79it/s]

Epochs: 4 | Train Loss: 0.038 | Train F1: 0.936
Val loss: 0.070 | Val F1: 0.869

100%|██████████| 439/439 [00:27<00:00, 15.86it/s]

Epochs: 5 | Train Loss: 0.027 | Train F1: 0.954
Val loss: 0.083 | Val F1: 0.856

100%|██████████| 439/439 [00:28<00:00, 15.43it/s]

Epochs: 6 | Train Loss: 0.019 | Train F1: 0.968
Val loss: 0.071 | Val F1: 0.867

100%|██████████| 439/439 [00:28<00:00, 15.28it/s]

Epochs: 7 | Train Loss: 0.014 | Train F1: 0.978
Val loss: 0.089 | Val F1: 0.856
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.869

100%|██████████| 439/439 [00:27<00:00, 15.85it/s]

Epochs: 1 | Train Loss: 0.368 | Train F1: 0.523
Val loss: 0.169 | Val F1: 0.750

100%|██████████| 439/439 [00:27<00:00, 15.76it/s]

Epochs: 2 | Train Loss: 0.101 | Train F1: 0.834
Val loss: 0.114 | Val F1: 0.813

100%|██████████| 439/439 [00:27<00:00, 15.92it/s]

Epochs: 3 | Train Loss: 0.062 | Train F1: 0.896
Val loss: 0.096 | Val F1: 0.830

100%|██████████| 439/439 [00:27<00:00, 15.89it/s]

Epochs: 4 | Train Loss: 0.044 | Train F1: 0.924
Val loss: 0.087 | Val F1: 0.845

100%|██████████| 439/439 [00:27<00:00, 15.82it/s]

Epochs: 5 | Train Loss: 0.032 | Train F1: 0.946
Val loss: 0.084 | Val F1: 0.847

100%|██████████| 439/439 [00:28<00:00, 15.34it/s]

Epochs: 6 | Train Loss: 0.024 | Train F1: 0.959
Val loss: 0.092 | Val F1: 0.855

100%|██████████| 439/439 [00:28<00:00, 15.44it/s]

Epochs: 7 | Train Loss: 0.018 | Train F1: 0.969
Val loss: 0.109 | Val F1: 0.849

100%|██████████| 439/439 [00:28<00:00, 15.52it/s]

Epochs: 8 | Train Loss: 0.013 | Train F1: 0.977
Val loss: 0.111 | Val F1: 0.848

100%|██████████| 439/439 [00:28<00:00, 15.27it/s]

Epochs: 9 | Train Loss: 0.010 | Train F1: 0.983
Val loss: 0.130 | Val F1: 0.851
Early stopping after epoch 9
Best model from epoch 6 Val Macro F1 = 0.855

In [63]:
results_df = pd.DataFrame(search_results).sort_values(by=["Validation F1", "Train-Val Gap"], 
                                                      ascending=[False, True])

results_df

,learning_rate,dropout,Best Epoch,Train Loss,Val Loss,Train F1,Validation F1,Train-Val Gap
0,0.0010,0.2,4,0.019,0.063,0.971,0.878,0.093
1,0.0010,0.3,4,0.020,0.074,0.968,0.872,0.096
7,0.0005,0.3,4,0.038,0.070,0.936,0.869,0.067
6,0.0005,0.2,4,0.038,0.068,0.937,0.869,0.068
2,0.0010,0.5,6,0.010,0.081,0.983,0.869,0.114
8,0.0005,0.5,6,0.024,0.092,0.959,0.855,0.104
4,0.0001,0.3,10,0.058,0.094,0.896,0.829,0.067
5,0.0001,0.5,9,0.066,0.100,0.880,0.823,0.057
3,0.0001,0.2,10,0.059,0.116,0.898,0.822,0.076

I used grid search to test different learning rates and dropout values.

The best result was achieved with `learning rate of 0.001 and a dropout rate of 0.2`, giving `the validation macro F1 score of 0.878`. Lower learning rates did not perform as well, and increasing dropout did not lead to any improvement.

The validation score only increased slightly, but the gap between training and validation F1 decreased from `0.119 to 0.093`. This suggests that the model was generalising a bit better and relying less on memorising the training data.

Based on these results, I use `learning rate of 0.001 and dropout of 0.2` for the further experiments.

### Additional Dropout Regularisation

To reduce the gap, an additional dropout layer was applied before the BiLSTM.

In [25]:
class CharCNNBiLSTMCRF2(nn.Module):

    def __init__(self,word_embeddings, num_char, num_tags, 
                char_embedding_dim=30, char_out_channel=50,
                lstm_hidden_dim = 200, dropout=0.2):

        super().__init__()

        self.word_emb = nn.Embedding.from_pretrained(word_embeddings, freeze=False, padding_idx=word_to_id[PAD_TOKEN])
        
        self.char_cnn = CharCNN(num_chars=num_char, char_embedding_dim=char_embedding_dim, char_out_channels=char_out_channel,
                                padding_idx=char_to_id[PAD_CHAR])

        self.dropout = nn.Dropout(dropout)

        self.bilstm = nn.LSTM(input_size=word_embeddings.shape[1] + char_out_channel, hidden_size=lstm_hidden_dim,
                              batch_first=True, bidirectional=True)

        # Convert each output into emissions for each tag
        self.emissions = nn.Linear(lstm_hidden_dim * 2, num_tags)

        self.crf = CRF(num_tags, batch_first=True)


    def forward(self, word_ids, char_ids, tags=None, mask=None):
        
        word_emb = self.word_emb(word_ids)  # [B, S, word_emb_dim]
        char_emb = self.char_cnn(char_ids)  # [B, S, char_out_channels]

        x = torch.cat([word_emb, char_emb], dim=-1)
        x = self.dropout(x)

        bilstm_out, _ = self.bilstm(x) # [B, S, hidden_dim]
        bilstm_out = self.dropout(bilstm_out)

        emissions = self.emissions(bilstm_out)

        if tags is not None:

            loss = -self.crf(emissions, tags, mask=mask.bool(), reduction="token_mean")

            return loss

        preds = self.crf.decode(emissions, mask=mask.bool())

        return preds

In [66]:
model2 = CharCNNBiLSTMCRF2(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                        char_embedding_dim=30, char_out_channel=50,
                        lstm_hidden_dim = 200, dropout=0.2).to(device)


EPOCHS = 10
LR = 1e-3

In [67]:
model2, results, best_epoch = train(model2, train_loader, valid_loader, LR, EPOCHS)

100%|██████████| 439/439 [00:32<00:00, 13.55it/s]

Epochs: 1 | Train Loss: 0.285 | Train F1: 0.635
Val loss: 0.104 | Val F1: 0.820

100%|██████████| 439/439 [00:29<00:00, 14.91it/s]

Epochs: 2 | Train Loss: 0.073 | Train F1: 0.874
Val loss: 0.085 | Val F1: 0.848

100%|██████████| 439/439 [00:28<00:00, 15.23it/s]

Epochs: 3 | Train Loss: 0.046 | Train F1: 0.919
Val loss: 0.076 | Val F1: 0.861

100%|██████████| 439/439 [00:28<00:00, 15.31it/s]

Epochs: 4 | Train Loss: 0.031 | Train F1: 0.944
Val loss: 0.059 | Val F1: 0.880

100%|██████████| 439/439 [00:28<00:00, 15.45it/s]

Epochs: 5 | Train Loss: 0.022 | Train F1: 0.959
Val loss: 0.065 | Val F1: 0.873

100%|██████████| 439/439 [00:28<00:00, 15.54it/s]

Epochs: 6 | Train Loss: 0.016 | Train F1: 0.970
Val loss: 0.068 | Val F1: 0.875

100%|██████████| 439/439 [00:27<00:00, 15.70it/s]

Epochs: 7 | Train Loss: 0.012 | Train F1: 0.977
Val loss: 0.079 | Val F1: 0.861
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.880

After adding dropout before the BiLSTM, the model achieved a best validation macro `F1 score of 0.880`, slightly improving on the previous result of `0.878`.

The train-validation gap also decreased from `0.093 to 0.083`, suggesting that the additional dropout helped reduce overfitting. As expected, the training F1 score was slightly lower because dropout makes the learning task more challenging and discourages memorisation.

The model showed slightly better generalisation and achieved the best validation performance.

### Change optimizer to AdamW

Even after adding extra dropout, there was still some overfitting. To try to improve generalisation further, I replaced the Adam optimizer with AdamW and tested different weight decay values `1e-5, 1e-4, and 1e-3`.

In [30]:
def train_wd(model, train_data, val_data, lr, wd, epochs):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = model.to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)

    epoch_results = []
    best_val_f1 = -1
    best_model_state = None
    best_epoch = 0
    patience = 3
    epochs_no_improve = 0

    for epoch_num in range(epochs):

        total_loss_train = 0
        train_preds = []
        train_true_labels = []

        model.train()

        for batch in tqdm(train_data):

            batch = move_to_device(batch, device)

            word_ids = batch["word_ids"]
            char_ids = batch["char_ids"]
            labels = batch["tag_ids"]
            mask = batch["mask"].bool()

            optimizer.zero_grad()
            
            
            loss = model(word_ids, char_ids, tags=labels, mask=mask)

            loss.backward()
            optimizer.step()      

            total_loss_train += loss.item()

            with torch.no_grad():

                pred_ids = model(word_ids, char_ids, mask=mask)

                for true_labels, pred_labels, sent_mask in zip(labels.cpu().tolist(), pred_ids, mask.cpu().tolist()):

                    length = sum(sent_mask)

                    train_true_labels.append([id_to_tag[label] for label in true_labels[:length]])
                    train_preds.append([id_to_tag[label] for label in pred_labels[:length]])

        train_f1 = seq_f1_score(train_true_labels, train_preds, mode="strict", scheme=IOB2, average="macro", zero_division=0)


        model.eval()

        total_loss_val = 0
        val_true_labels = []
        val_preds = []

        with torch.no_grad():

            for batch in val_data:
            
                batch = move_to_device(batch, device)
                word_ids = batch["word_ids"]
                char_ids = batch["char_ids"]
                labels = batch["tag_ids"]
                mask = batch["mask"].bool()

                val_loss = model(word_ids, char_ids, tags=labels, mask=mask)

                pred_ids = model(word_ids, char_ids, mask=mask)

                total_loss_val += val_loss.item()

                for true_labels, pred_labels, sent_mask in zip(labels.cpu().tolist(), pred_ids, mask.cpu().tolist()):

                    length = sum(sent_mask)

                    val_true_labels.append([id_to_tag[label] for label in true_labels[:length]])

                    val_preds.append([id_to_tag[label] for label in pred_labels[:length]])

            val_f1 = seq_f1_score(val_true_labels, val_preds, mode="strict", scheme=IOB2, average="macro", zero_division=0)

            # save best model weights by validation macro F1
            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_epoch = epoch_num + 1
                best_model_state = copy.deepcopy(model.state_dict())
                epochs_no_improve = 0

            else:
                epochs_no_improve += 1


            results = {"Epoch": epoch_num + 1, 
                       "train_loss": round(total_loss_train / len(train_data), 3), 
                       "val_loss": round(total_loss_val / len(val_data), 3),
                       "val_f1": round(val_f1, 3),
                       "train_f1": round(train_f1, 3)}


            epoch_results.append(results)

            print(f'Epochs: {epoch_num+1} | Train Loss: {total_loss_train / len(train_data):.3f} | Train F1: {train_f1:.3f}')
            print(f'Val loss: {total_loss_val/len(val_data):.3f} | Val F1: {val_f1:.3f}')

            if epochs_no_improve >= patience:

                print(f"Early stopping after epoch {epoch_num + 1}")
                break

    # Load best weights 
    model.load_state_dict(best_model_state)

    print(f"Best model from epoch {best_epoch} Val Macro F1 = {best_val_f1:.3f}")

    return model, epoch_results, best_epoch

In [76]:
weight_decays = [1e-5, 1e-4, 1e-3]

In [77]:
wd_results = []

for wd in weight_decays:

    print(f"{wd}:")

    model_wd = CharCNNBiLSTMCRF2(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                        char_embedding_dim=30, char_out_channel=50,
                        lstm_hidden_dim = 200, dropout=0.2).to(device)

    
    _, results_wd, best_epoch_wd = train_wd(model_wd, train_loader, valid_loader, LR,wd=wd, epochs=EPOCHS)

    best_epoch_result_wd = results_wd[best_epoch_wd - 1]

    wd_results.append({"weight_decay": wd,
                        "Best Epoch": best_epoch_wd,
                        "Train Loss": best_epoch_result_wd["train_loss"],
                        "Val Loss": best_epoch_result_wd["val_loss"],
                        "Train F1": best_epoch_result_wd["train_f1"],
                        "Validation F1": best_epoch_result_wd["val_f1"],
                        "Train-Val Gap": (best_epoch_result_wd["train_f1"] - best_epoch_result_wd["val_f1"])})

1e-05:

100%|██████████| 439/439 [00:29<00:00, 14.88it/s]

Epochs: 1 | Train Loss: 0.271 | Train F1: 0.646
Val loss: 0.109 | Val F1: 0.794

100%|██████████| 439/439 [00:29<00:00, 14.93it/s]

Epochs: 2 | Train Loss: 0.073 | Train F1: 0.874
Val loss: 0.075 | Val F1: 0.848

100%|██████████| 439/439 [00:29<00:00, 15.07it/s]

Epochs: 3 | Train Loss: 0.044 | Train F1: 0.921
Val loss: 0.057 | Val F1: 0.877

100%|██████████| 439/439 [00:29<00:00, 14.69it/s]

Epochs: 4 | Train Loss: 0.031 | Train F1: 0.945
Val loss: 0.055 | Val F1: 0.886

100%|██████████| 439/439 [00:31<00:00, 14.04it/s]

Epochs: 5 | Train Loss: 0.021 | Train F1: 0.961
Val loss: 0.066 | Val F1: 0.873

100%|██████████| 439/439 [00:31<00:00, 13.92it/s]

Epochs: 6 | Train Loss: 0.015 | Train F1: 0.969
Val loss: 0.068 | Val F1: 0.870

100%|██████████| 439/439 [00:29<00:00, 14.80it/s]

Epochs: 7 | Train Loss: 0.011 | Train F1: 0.979
Val loss: 0.056 | Val F1: 0.877
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.886
0.0001:

100%|██████████| 439/439 [00:30<00:00, 14.61it/s]

Epochs: 1 | Train Loss: 0.287 | Train F1: 0.636
Val loss: 0.103 | Val F1: 0.819

100%|██████████| 439/439 [00:29<00:00, 14.74it/s]

Epochs: 2 | Train Loss: 0.072 | Train F1: 0.879
Val loss: 0.076 | Val F1: 0.844

100%|██████████| 439/439 [00:29<00:00, 14.70it/s]

Epochs: 3 | Train Loss: 0.045 | Train F1: 0.918
Val loss: 0.057 | Val F1: 0.885

100%|██████████| 439/439 [00:30<00:00, 14.55it/s]

Epochs: 4 | Train Loss: 0.031 | Train F1: 0.943
Val loss: 0.057 | Val F1: 0.886

100%|██████████| 439/439 [00:30<00:00, 14.17it/s]

Epochs: 5 | Train Loss: 0.022 | Train F1: 0.959
Val loss: 0.058 | Val F1: 0.882

100%|██████████| 439/439 [00:30<00:00, 14.43it/s]

Epochs: 6 | Train Loss: 0.016 | Train F1: 0.970
Val loss: 0.057 | Val F1: 0.884

100%|██████████| 439/439 [00:29<00:00, 14.88it/s]

Epochs: 7 | Train Loss: 0.011 | Train F1: 0.978
Val loss: 0.062 | Val F1: 0.872
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.886
0.001:

100%|██████████| 439/439 [00:29<00:00, 15.05it/s]

Epochs: 1 | Train Loss: 0.289 | Train F1: 0.628
Val loss: 0.107 | Val F1: 0.810

100%|██████████| 439/439 [00:29<00:00, 15.07it/s]

Epochs: 2 | Train Loss: 0.074 | Train F1: 0.874
Val loss: 0.069 | Val F1: 0.866

100%|██████████| 439/439 [00:29<00:00, 14.72it/s]

Epochs: 3 | Train Loss: 0.046 | Train F1: 0.918
Val loss: 0.073 | Val F1: 0.865

100%|██████████| 439/439 [00:28<00:00, 15.32it/s]

Epochs: 4 | Train Loss: 0.031 | Train F1: 0.941
Val loss: 0.072 | Val F1: 0.876

100%|██████████| 439/439 [00:29<00:00, 15.08it/s]

Epochs: 5 | Train Loss: 0.023 | Train F1: 0.957
Val loss: 0.082 | Val F1: 0.859

100%|██████████| 439/439 [00:29<00:00, 15.11it/s]

Epochs: 6 | Train Loss: 0.017 | Train F1: 0.968
Val loss: 0.077 | Val F1: 0.867

100%|██████████| 439/439 [00:28<00:00, 15.19it/s]

Epochs: 7 | Train Loss: 0.012 | Train F1: 0.977
Val loss: 0.078 | Val F1: 0.875
Early stopping after epoch 7
Best model from epoch 4 Val Macro F1 = 0.876

In [78]:
wd_results_df = pd.DataFrame(wd_results).sort_values(by=["Validation F1", "Train-Val Gap"], 
                                                      ascending=[False, True])

wd_results_df

,weight_decay,Best Epoch,Train Loss,Val Loss,Train F1,Validation F1,Train-Val Gap
1,0.00010,4,0.031,0.057,0.943,0.886,0.057
0,0.00001,4,0.031,0.055,0.945,0.886,0.059
2,0.00100,4,0.031,0.072,0.941,0.876,0.065

Using `AdamW` improved the model's performance. **The best validation macro F1 score** increased from `0.880 to 0.886` when using a weight decay of 1e-5 or 1e-4.

**The train-validation gap** also decreased from `0.083 to 0.057`, suggesting that the model generalised better to unseen data and overfitted less than before.

A larger weight decay `1e-3` reduced performance, which suggests that too much regularisation prevented the model from learning useful patterns from the training data.

AdamW with a small weight decay value gave the best balance between performance and generalisation and produced the strongest results so far.

For the further experiments, I use the following hyperparameters:

- Learning rate: `1e-3`
- Dropout: `0.2`
- Optimizer: `AdamW`
- Weight decay: `1e-4`
- Early-stopping patience: `3`

These values were selected based on the previous experiments, where they provided the best balance between validation performance and generalisation. I

### Frozen and Fine-Tuned GloVe Embeddings

So far, all experiments used `fine-tuned GloVe embeddings`, meaning the embedding weights were updated during training. In this experiment, I `froze the GloVe embeddings` and kept the pre-trained vectors unchanged.

The goal was to see whether the model could benefit more from the original GloVe representations rather than adapting them to the training data.

In [24]:
class CharCNNBiLSTMCRF_frozen(nn.Module):

    def __init__(self,word_embeddings, num_char, num_tags, 
                char_embedding_dim=30, char_out_channel=50,
                lstm_hidden_dim = 200, dropout=0.2):

        super().__init__()

        self.word_emb = nn.Embedding.from_pretrained(word_embeddings, freeze=True, padding_idx=word_to_id[PAD_TOKEN])
        
        self.char_cnn = CharCNN(num_chars=num_char, char_embedding_dim=char_embedding_dim, char_out_channels=char_out_channel,
                                padding_idx=char_to_id[PAD_CHAR])

        self.dropout = nn.Dropout(dropout)

        self.bilstm = nn.LSTM(input_size=word_embeddings.shape[1] + char_out_channel, hidden_size=lstm_hidden_dim,
                              batch_first=True, bidirectional=True)

        # Convert each output into emissions for each tag
        self.emissions = nn.Linear(lstm_hidden_dim * 2, num_tags)

        self.crf = CRF(num_tags, batch_first=True)


    def forward(self, word_ids, char_ids, tags=None, mask=None):
        
        word_emb = self.word_emb(word_ids)  # [B, S, word_emb_dim]
        char_emb = self.char_cnn(char_ids)  # [B, S, char_out_channels]

        x = torch.cat([word_emb, char_emb], dim=-1)
        x = self.dropout(x)

        bilstm_out, _ = self.bilstm(x) # [B, S, hidden_dim]
        bilstm_out = self.dropout(bilstm_out)

        emissions = self.emissions(bilstm_out)

        if tags is not None:

            loss = -self.crf(emissions, tags, mask=mask.bool(), reduction="token_mean")

            return loss

        preds = self.crf.decode(emissions, mask=mask.bool())

        return preds

In [100]:
final_model_frozen = CharCNNBiLSTMCRF_frozen(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                    char_embedding_dim=30, char_out_channel=50,
                    lstm_hidden_dim = 200, dropout=0.2).to(device)

In [101]:
trained_final_model_frozen, final_results_frozen, final_best_epoch_frozen = train_wd(final_model_frozen, train_loader, valid_loader, FINAL_LR,wd=WD, epochs=FINAL_EPOCHS)

100%|██████████| 439/439 [00:29<00:00, 14.87it/s]

Epochs: 1 | Train Loss: 0.293 | Train F1: 0.618
Val loss: 0.103 | Val F1: 0.816

100%|██████████| 439/439 [00:31<00:00, 13.90it/s]

Epochs: 2 | Train Loss: 0.091 | Train F1: 0.839
Val loss: 0.078 | Val F1: 0.852

100%|██████████| 439/439 [00:30<00:00, 14.62it/s]

Epochs: 3 | Train Loss: 0.065 | Train F1: 0.881
Val loss: 0.064 | Val F1: 0.875

100%|██████████| 439/439 [00:29<00:00, 14.77it/s]

Epochs: 4 | Train Loss: 0.051 | Train F1: 0.907
Val loss: 0.056 | Val F1: 0.878

100%|██████████| 439/439 [00:29<00:00, 14.90it/s]

Epochs: 5 | Train Loss: 0.041 | Train F1: 0.924
Val loss: 0.049 | Val F1: 0.896

100%|██████████| 439/439 [00:30<00:00, 14.51it/s]

Epochs: 6 | Train Loss: 0.034 | Train F1: 0.935
Val loss: 0.047 | Val F1: 0.898

100%|██████████| 439/439 [00:33<00:00, 13.12it/s]

Epochs: 7 | Train Loss: 0.027 | Train F1: 0.945
Val loss: 0.044 | Val F1: 0.904

100%|██████████| 439/439 [00:31<00:00, 13.89it/s]

Epochs: 8 | Train Loss: 0.023 | Train F1: 0.954
Val loss: 0.043 | Val F1: 0.904
Best model from epoch 8 Val Macro F1 = 0.904

**The validation macro F1** increased from `0.886 to 0.904`, which was the best score achieved in all experiments.

The train F1 at the best epoch was `0.954`, giving a train-validation gap of `0.050`. This is smaller than the previous gap of `0.057`, suggesting that the model was overfitting less.

A possible reason is that the pre-trained GloVe embeddings already contain useful semantic information learned from a much larger corpus. By freezing them, the model was forced to use these representations instead of changing them to fit the training set.

### BiLSTM Hidden-Dimension Experiment

The previous best model used a **BiLSTM hidden size** of `200`. In this experiment, I test smaller hidden sizes `150 and 100` to see whether reducing the model capacity could further reduce overfitting and improve generalisation.

A smaller hidden dimension means fewer trainable parameters, which can sometimes help the model focus on more general patterns instead of memorising the training data.

In [31]:
FINAL_EPOCHS = 15
FINAL_LR = 1e-3
WD = 1e-4

In [32]:
final_smodel = CharCNNBiLSTMCRF_frozen(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                    char_embedding_dim=30, char_out_channel=50,
                    lstm_hidden_dim = 150, dropout=0.2).to(device)

In [104]:
trained_final_smodel, final_results_smodel, final_best_epoch_smodel = train_wd(final_smodel, train_loader, valid_loader, FINAL_LR,wd=WD, epochs=FINAL_EPOCHS)

100%|██████████| 439/439 [00:31<00:00, 13.74it/s]

Epochs: 1 | Train Loss: 0.311 | Train F1: 0.596
Val loss: 0.116 | Val F1: 0.789

100%|██████████| 439/439 [00:31<00:00, 13.95it/s]

Epochs: 2 | Train Loss: 0.095 | Train F1: 0.831
Val loss: 0.078 | Val F1: 0.849

100%|██████████| 439/439 [00:29<00:00, 14.71it/s]

Epochs: 3 | Train Loss: 0.068 | Train F1: 0.875
Val loss: 0.063 | Val F1: 0.869

100%|██████████| 439/439 [00:30<00:00, 14.38it/s]

Epochs: 4 | Train Loss: 0.054 | Train F1: 0.899
Val loss: 0.063 | Val F1: 0.870

100%|██████████| 439/439 [00:29<00:00, 14.64it/s]

Epochs: 5 | Train Loss: 0.044 | Train F1: 0.915
Val loss: 0.050 | Val F1: 0.890

100%|██████████| 439/439 [00:28<00:00, 15.28it/s]

Epochs: 6 | Train Loss: 0.036 | Train F1: 0.931
Val loss: 0.048 | Val F1: 0.888

100%|██████████| 439/439 [00:28<00:00, 15.46it/s]

Epochs: 7 | Train Loss: 0.031 | Train F1: 0.938
Val loss: 0.045 | Val F1: 0.896

100%|██████████| 439/439 [00:28<00:00, 15.62it/s]

Epochs: 8 | Train Loss: 0.027 | Train F1: 0.947
Val loss: 0.049 | Val F1: 0.886

100%|██████████| 439/439 [00:28<00:00, 15.43it/s]

Epochs: 9 | Train Loss: 0.022 | Train F1: 0.954
Val loss: 0.048 | Val F1: 0.892

100%|██████████| 439/439 [00:27<00:00, 16.06it/s]

Epochs: 10 | Train Loss: 0.020 | Train F1: 0.960
Val loss: 0.045 | Val F1: 0.898

100%|██████████| 439/439 [00:29<00:00, 14.66it/s]

Epochs: 11 | Train Loss: 0.017 | Train F1: 0.963
Val loss: 0.044 | Val F1: 0.898

100%|██████████| 439/439 [00:27<00:00, 15.74it/s]

Epochs: 12 | Train Loss: 0.014 | Train F1: 0.969
Val loss: 0.045 | Val F1: 0.903

100%|██████████| 439/439 [00:28<00:00, 15.15it/s]

Epochs: 13 | Train Loss: 0.013 | Train F1: 0.973
Val loss: 0.048 | Val F1: 0.897

100%|██████████| 439/439 [00:28<00:00, 15.64it/s]

Epochs: 14 | Train Loss: 0.011 | Train F1: 0.975
Val loss: 0.047 | Val F1: 0.899

100%|██████████| 439/439 [00:27<00:00, 15.97it/s]

Epochs: 15 | Train Loss: 0.010 | Train F1: 0.980
Val loss: 0.047 | Val F1: 0.902
Early stopping after epoch 15
Best model from epoch 12 Val Macro F1 = 0.903

In [108]:
final_smodel2 = CharCNNBiLSTMCRF_frozen(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id), 
                    char_embedding_dim=30, char_out_channel=50,
                    lstm_hidden_dim = 100, dropout=0.2).to(device)

In [109]:
trained_final_smodel2, final_results_smodel2, final_best_epoch_smodel2 = train_wd(final_smodel2, train_loader, valid_loader, FINAL_LR, wd=WD, epochs=20)

100%|██████████| 439/439 [00:28<00:00, 15.16it/s]

Epochs: 1 | Train Loss: 0.349 | Train F1: 0.537
Val loss: 0.139 | Val F1: 0.774

100%|██████████| 439/439 [00:28<00:00, 15.40it/s]

Epochs: 2 | Train Loss: 0.110 | Train F1: 0.809
Val loss: 0.089 | Val F1: 0.831

100%|██████████| 439/439 [00:31<00:00, 14.12it/s]

Epochs: 3 | Train Loss: 0.078 | Train F1: 0.859
Val loss: 0.066 | Val F1: 0.872

100%|██████████| 439/439 [00:29<00:00, 15.14it/s]

Epochs: 4 | Train Loss: 0.062 | Train F1: 0.885
Val loss: 0.057 | Val F1: 0.879

100%|██████████| 439/439 [00:28<00:00, 15.22it/s]

Epochs: 5 | Train Loss: 0.052 | Train F1: 0.900
Val loss: 0.051 | Val F1: 0.897

100%|██████████| 439/439 [00:27<00:00, 15.77it/s]

Epochs: 6 | Train Loss: 0.044 | Train F1: 0.913
Val loss: 0.051 | Val F1: 0.888

100%|██████████| 439/439 [00:28<00:00, 15.62it/s]

Epochs: 7 | Train Loss: 0.038 | Train F1: 0.925
Val loss: 0.047 | Val F1: 0.897

100%|██████████| 439/439 [00:28<00:00, 15.54it/s]

Epochs: 8 | Train Loss: 0.034 | Train F1: 0.930
Val loss: 0.047 | Val F1: 0.893
Early stopping after epoch 8
Best model from epoch 5 Val Macro F1 = 0.897

**Reducing the hidden size did not improve validation performance**. 

**Hidden size of 150** achieved `the validation macro F1 score of 0.903`, while **hidden size of 100** achieved `0.897`. Both were lower than the previous best score of 0.904 obtained with a hidden size of 200.

The smaller models showed less overfitting, especially with a hidden size of 100, where the train-validation gap decreased to 0.022. However, this came at the cost of lower validation performance.

This suggests that reducing the model size too much limits its ability to learn useful contextual information. Although the larger model showed a slightly bigger gap, it achieved the best validation F1 score and therefore remained the preferred configuration.

### Evaluation Across Random Seeds

To make sure the results were not caused by a lucky random seed, I trained the final model with different seeds.

In [ ]:
seeds = [123, 2026]
seeds_scores = []

for seed in seeds:
    
    set_seed(seed)

    model = CharCNNBiLSTMCRF_frozen(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id),
                                    char_embedding_dim=30, char_out_channel=50,
                                    lstm_hidden_dim=200, dropout=0.2).to(device)

    _, results_seeds, best_epoch_seeds = train_wd(model, train_loader, valid_loader, FINAL_LR, wd=WD, epochs=15)

    best_result_seed = results_seeds[best_epoch_seeds - 1]

    seeds_scores.append({"seed": seed,
                        "Best Epoch": best_epoch_seeds,
                        "Train Loss": best_result_seed["train_loss"],
                        "Val Loss": best_result_seed["val_loss"],
                        "Train F1": best_result_seed["train_f1"],
                        "Validation F1": best_result_seed["val_f1"],
                        "Train-Val Gap": (best_result_seed["train_f1"] - best_result_seed["val_f1"])})

100%|██████████| 439/439 [00:29<00:00, 14.80it/s]

Epochs: 1 | Train Loss: 0.302 | Train F1: 0.605
Val loss: 0.117 | Val F1: 0.777

100%|██████████| 439/439 [00:30<00:00, 14.55it/s]

Epochs: 2 | Train Loss: 0.094 | Train F1: 0.831
Val loss: 0.073 | Val F1: 0.856

100%|██████████| 439/439 [00:28<00:00, 15.29it/s]

Epochs: 3 | Train Loss: 0.068 | Train F1: 0.874
Val loss: 0.063 | Val F1: 0.871

100%|██████████| 439/439 [00:27<00:00, 16.04it/s]

Epochs: 4 | Train Loss: 0.054 | Train F1: 0.902
Val loss: 0.056 | Val F1: 0.892

100%|██████████| 439/439 [00:29<00:00, 14.91it/s]

Epochs: 5 | Train Loss: 0.044 | Train F1: 0.917
Val loss: 0.051 | Val F1: 0.890

100%|██████████| 439/439 [00:28<00:00, 15.17it/s]

Epochs: 6 | Train Loss: 0.036 | Train F1: 0.930
Val loss: 0.047 | Val F1: 0.899

100%|██████████| 439/439 [00:28<00:00, 15.29it/s]

Epochs: 7 | Train Loss: 0.030 | Train F1: 0.937
Val loss: 0.048 | Val F1: 0.896

100%|██████████| 439/439 [00:29<00:00, 15.07it/s]

Epochs: 8 | Train Loss: 0.026 | Train F1: 0.947
Val loss: 0.045 | Val F1: 0.902

100%|██████████| 439/439 [00:28<00:00, 15.63it/s]

Epochs: 9 | Train Loss: 0.023 | Train F1: 0.955
Val loss: 0.046 | Val F1: 0.903

100%|██████████| 439/439 [00:33<00:00, 13.08it/s]

Epochs: 10 | Train Loss: 0.019 | Train F1: 0.960
Val loss: 0.046 | Val F1: 0.906

100%|██████████| 439/439 [00:31<00:00, 14.14it/s]

Epochs: 11 | Train Loss: 0.016 | Train F1: 0.966
Val loss: 0.046 | Val F1: 0.907

100%|██████████| 439/439 [00:30<00:00, 14.28it/s]

Epochs: 12 | Train Loss: 0.014 | Train F1: 0.970
Val loss: 0.049 | Val F1: 0.907

100%|██████████| 439/439 [00:33<00:00, 13.21it/s]

Epochs: 13 | Train Loss: 0.012 | Train F1: 0.973
Val loss: 0.048 | Val F1: 0.903

100%|██████████| 439/439 [00:33<00:00, 13.12it/s]

Epochs: 14 | Train Loss: 0.011 | Train F1: 0.977
Val loss: 0.050 | Val F1: 0.907

100%|██████████| 439/439 [00:31<00:00, 13.90it/s]

Epochs: 15 | Train Loss: 0.009 | Train F1: 0.982
Val loss: 0.055 | Val F1: 0.896
Early stopping after epoch 15
Best model from epoch 12 Val Macro F1 = 0.907

100%|██████████| 439/439 [00:29<00:00, 14.80it/s]

Epochs: 1 | Train Loss: 0.304 | Train F1: 0.596
Val loss: 0.111 | Val F1: 0.803

100%|██████████| 439/439 [00:30<00:00, 14.23it/s]

Epochs: 2 | Train Loss: 0.097 | Train F1: 0.830
Val loss: 0.078 | Val F1: 0.854

100%|██████████| 439/439 [00:29<00:00, 14.78it/s]

Epochs: 3 | Train Loss: 0.069 | Train F1: 0.872
Val loss: 0.062 | Val F1: 0.872

100%|██████████| 439/439 [00:28<00:00, 15.45it/s]

Epochs: 4 | Train Loss: 0.054 | Train F1: 0.899
Val loss: 0.058 | Val F1: 0.878

100%|██████████| 439/439 [00:27<00:00, 15.70it/s]

Epochs: 5 | Train Loss: 0.045 | Train F1: 0.913
Val loss: 0.051 | Val F1: 0.887

100%|██████████| 439/439 [00:27<00:00, 15.75it/s]

Epochs: 6 | Train Loss: 0.036 | Train F1: 0.928
Val loss: 0.046 | Val F1: 0.895

100%|██████████| 439/439 [00:27<00:00, 15.79it/s]

Epochs: 7 | Train Loss: 0.031 | Train F1: 0.936
Val loss: 0.046 | Val F1: 0.901

100%|██████████| 439/439 [00:26<00:00, 16.42it/s]

Epochs: 8 | Train Loss: 0.026 | Train F1: 0.947
Val loss: 0.046 | Val F1: 0.896

100%|██████████| 439/439 [00:26<00:00, 16.67it/s]

Epochs: 9 | Train Loss: 0.023 | Train F1: 0.952
Val loss: 0.044 | Val F1: 0.907

100%|██████████| 439/439 [00:26<00:00, 16.35it/s]

Epochs: 10 | Train Loss: 0.020 | Train F1: 0.958
Val loss: 0.044 | Val F1: 0.906

100%|██████████| 439/439 [00:27<00:00, 16.22it/s]

Epochs: 11 | Train Loss: 0.016 | Train F1: 0.965
Val loss: 0.047 | Val F1: 0.906

100%|██████████| 439/439 [00:27<00:00, 16.01it/s]

Epochs: 12 | Train Loss: 0.014 | Train F1: 0.971
Val loss: 0.047 | Val F1: 0.906
Early stopping after epoch 12
Best model from epoch 9 Val Macro F1 = 0.907

In [113]:
seeds_results_df = pd.DataFrame(seeds_scores).sort_values(by=["Validation F1", "Train-Val Gap"], 
                                                      ascending=[False, True])

seeds_results_df

,seed,Best Epoch,Train Loss,Val Loss,Train F1,Validation F1,Train-Val Gap
1,2026,9,0.023,0.044,0.952,0.907,0.045
0,123,12,0.014,0.049,0.970,0.907,0.063

The validation F1 scores were very close across runs, showing that the model performs consistently. The best run achieved a validation macro F1 score of `0.907`, which is slightly better than the previous best result of 0.904.

Overall, the small variation between runs suggests that the model is stable and that the improvements seen in previous experiments are reliable.

### Final Model Selection

The final model was chosen based mainly on validation macro F1 score. When two models achieved the same validation F1, I also considered the validation loss and the train-validation gap.

The final model used the following settings:

* Random seed: `2026`
* Frozen GloVe embeddings
* Character embedding dimension: `30`
* Character CNN output channels: `50`
* BiLSTM hidden dimension: `200`
* Dropout: `0.2`
* Optimizer: `AdamW`
* Learning rate: `1e-3`
* Weight decay: `1e-4`
* Early stopping patience: `3`

Both seed `123` and seed `2026` achieved the highest validation macro F1 score of `0.907`. However, seed `2026` achieved a slightly lower validation loss `0.044` and a smaller train-validation gap `0.045`. For this reason, the model from seed `2026` at epoch `9` was selected as the final model.

This model will now be evaluated on the test set, which has not been used during training or model selection, to obtain the final performance estimate.

In [25]:
set_seed(2026)

In [26]:
final_model = CharCNNBiLSTMCRF_frozen(word_embeddings=word_embeddings, num_char=len(char_to_id), num_tags=len(tag_to_id),
                                    char_embedding_dim=30, char_out_channel=50,
                                    lstm_hidden_dim=200, dropout=0.2).to(device)

In [54]:
final_model, final_results, final_best_epoch = train_wd(final_model, train_loader, valid_loader, FINAL_LR, wd=WD, epochs=15)

100%|██████████| 439/439 [00:30<00:00, 14.43it/s]

Epochs: 1 | Train Loss: 0.286 | Train F1: 0.613
Val loss: 0.104 | Val F1: 0.824

100%|██████████| 439/439 [00:32<00:00, 13.68it/s]

Epochs: 2 | Train Loss: 0.090 | Train F1: 0.844
Val loss: 0.077 | Val F1: 0.849

100%|██████████| 439/439 [00:31<00:00, 13.79it/s]

Epochs: 3 | Train Loss: 0.063 | Train F1: 0.885
Val loss: 0.064 | Val F1: 0.866

100%|██████████| 439/439 [00:31<00:00, 14.15it/s]

Epochs: 4 | Train Loss: 0.049 | Train F1: 0.908
Val loss: 0.062 | Val F1: 0.879

100%|██████████| 439/439 [00:31<00:00, 14.06it/s]

Epochs: 5 | Train Loss: 0.040 | Train F1: 0.924
Val loss: 0.052 | Val F1: 0.889

100%|██████████| 439/439 [00:31<00:00, 14.06it/s]

Epochs: 6 | Train Loss: 0.032 | Train F1: 0.937
Val loss: 0.051 | Val F1: 0.889

100%|██████████| 439/439 [00:31<00:00, 14.04it/s]

Epochs: 7 | Train Loss: 0.026 | Train F1: 0.948
Val loss: 0.053 | Val F1: 0.876

100%|██████████| 439/439 [00:30<00:00, 14.55it/s]

Epochs: 8 | Train Loss: 0.022 | Train F1: 0.956
Val loss: 0.046 | Val F1: 0.897

100%|██████████| 439/439 [00:30<00:00, 14.50it/s]

Epochs: 9 | Train Loss: 0.019 | Train F1: 0.963
Val loss: 0.055 | Val F1: 0.889

100%|██████████| 439/439 [00:30<00:00, 14.53it/s]

Epochs: 10 | Train Loss: 0.016 | Train F1: 0.968
Val loss: 0.048 | Val F1: 0.900

100%|██████████| 439/439 [00:30<00:00, 14.52it/s]

Epochs: 11 | Train Loss: 0.013 | Train F1: 0.972
Val loss: 0.050 | Val F1: 0.897

100%|██████████| 439/439 [00:29<00:00, 14.83it/s]

Epochs: 12 | Train Loss: 0.011 | Train F1: 0.977
Val loss: 0.051 | Val F1: 0.901

100%|██████████| 439/439 [00:29<00:00, 14.73it/s]

Epochs: 13 | Train Loss: 0.010 | Train F1: 0.979
Val loss: 0.050 | Val F1: 0.896

100%|██████████| 439/439 [00:31<00:00, 13.87it/s]

Epochs: 14 | Train Loss: 0.009 | Train F1: 0.983
Val loss: 0.048 | Val F1: 0.903

100%|██████████| 439/439 [00:31<00:00, 14.10it/s]

Epochs: 15 | Train Loss: 0.008 | Train F1: 0.985
Val loss: 0.057 | Val F1: 0.897
Best model from epoch 14 Val Macro F1 = 0.903

In [55]:
torch.save(final_model.state_dict(), "../models/bilstm_weights.pt")

In [56]:
final_results

[{'Epoch': 1,
  'train_loss': 0.286,
  'val_loss': 0.104,
  'val_f1': np.float64(0.824),
  'train_f1': np.float64(0.613)},
 {'Epoch': 2,
  'train_loss': 0.09,
  'val_loss': 0.077,
  'val_f1': np.float64(0.849),
  'train_f1': np.float64(0.844)},
 {'Epoch': 3,
  'train_loss': 0.063,
  'val_loss': 0.064,
  'val_f1': np.float64(0.866),
  'train_f1': np.float64(0.885)},
 {'Epoch': 4,
  'train_loss': 0.049,
  'val_loss': 0.062,
  'val_f1': np.float64(0.879),
  'train_f1': np.float64(0.908)},
 {'Epoch': 5,
  'train_loss': 0.04,
  'val_loss': 0.052,
  'val_f1': np.float64(0.889),
  'train_f1': np.float64(0.924)},
 {'Epoch': 6,
  'train_loss': 0.032,
  'val_loss': 0.051,
  'val_f1': np.float64(0.889),
  'train_f1': np.float64(0.937)},
 {'Epoch': 7,
  'train_loss': 0.026,
  'val_loss': 0.053,
  'val_f1': np.float64(0.876),
  'train_f1': np.float64(0.948)},
 {'Epoch': 8,
  'train_loss': 0.022,
  'val_loss': 0.046,
  'val_f1': np.float64(0.897),
  'train_f1': np.float64(0.956)},
 {'Epoch': 9,
  'train_loss': 0.019,
  'val_loss': 0.055,
  'val_f1': np.float64(0.889),
  'train_f1': np.float64(0.963)},
 {'Epoch': 10,
  'train_loss': 0.016,
  'val_loss': 0.048,
  'val_f1': np.float64(0.9),
  'train_f1': np.float64(0.968)},
 {'Epoch': 11,
  'train_loss': 0.013,
  'val_loss': 0.05,
  'val_f1': np.float64(0.897),
  'train_f1': np.float64(0.972)},
 {'Epoch': 12,
  'train_loss': 0.011,
  'val_loss': 0.051,
  'val_f1': np.float64(0.901),
  'train_f1': np.float64(0.977)},
 {'Epoch': 13,
  'train_loss': 0.01,
  'val_loss': 0.05,
  'val_f1': np.float64(0.896),
  'train_f1': np.float64(0.979)},
 {'Epoch': 14,
  'train_loss': 0.009,
  'val_loss': 0.048,
  'val_f1': np.float64(0.903),
  'train_f1': np.float64(0.983)},
 {'Epoch': 15,
  'train_loss': 0.008,
  'val_loss': 0.057,
  'val_f1': np.float64(0.897),
  'train_f1': np.float64(0.985)}]

In [57]:
final_results_df = pd.DataFrame(final_results).sort_values(by=["val_f1"], 
                                                      ascending=False)

final_results_df

    Epoch  train_loss  val_loss  val_f1  train_f1
13     14       0.009     0.048   0.903     0.983
11     12       0.011     0.051   0.901     0.977
9      10       0.016     0.048   0.900     0.968
7       8       0.022     0.046   0.897     0.956
14     15       0.008     0.057   0.897     0.985
10     11       0.013     0.050   0.897     0.972
12     13       0.010     0.050   0.896     0.979
4       5       0.040     0.052   0.889     0.924
5       6       0.032     0.051   0.889     0.937
8       9       0.019     0.055   0.889     0.963
3       4       0.049     0.062   0.879     0.908
6       7       0.026     0.053   0.876     0.948
2       3       0.063     0.064   0.866     0.885
1       2       0.090     0.077   0.849     0.844
0       1       0.286     0.104   0.824     0.613

In [42]:
final_results_df.to_csv("../results/bilstm_final_results.csv", index=False)

NameError: name 'final_results_df' is not defined

The final model achieved its highest validation macro F1 score of `0.903` at `epoch 14`, so the model weights from this epoch were restored.

At `epoch 15`, **training F1** increased to `0.985`, while **validation F1** decreased to `0.897`, resulting in **train-validation gap** of `0.088`. 

This widening gap indicates that the model was beginning to overfit the training data. Therefore, the epoch-14 checkpoint was selected as the final model because it provided the strongest validation performance.

## 8. Final Evaluation


After training, I evaluate on the test set. I report token-level accuracy and token-level precision, recall, and F1. Then I also compute exact entity-span evaluation.

In [27]:
final_model.load_state_dict(torch.load("../models/bilstm_weights.pt", map_location=device))

In [28]:
def evaluation(model, test_data):

    model.eval()

    # Entity level
    true_entity = []
    pred_entity = []

    # Token Level
    token_true = []
    token_pred = []

    sent_words = []

    labels_order = [id_to_tag[idx] for idx in sorted(id_to_tag)]

    with torch.no_grad():

        for batch in test_data:
        
            batch = move_to_device(batch, device)
            words = batch["words"]
            word_ids = batch["word_ids"]
            char_ids = batch["char_ids"]
            labels = batch["tag_ids"]
            mask = batch["mask"].bool()

            

            pred_ids = model(word_ids, char_ids, mask=mask)

            for words, true_labels, pred_labels, sent_mask in zip(words, labels.cpu().tolist(), pred_ids, mask.cpu().tolist()):

                length = sum(sent_mask)

                words = words[:length]
                true_tags = [id_to_tag[label] for label in true_labels[:length]]
                pred_tags = [id_to_tag[label] for label in pred_labels[:length]]

                # Append actual word
                sent_words.append(words)

                # Append tags entity level
                true_entity.append(true_tags)
                pred_entity.append(pred_tags)

                # Append tags token level
                token_true.extend(true_tags)
                token_pred.extend(pred_tags)

        # Token Level
        token_precision, token_recall, token_f1, _ = precision_recall_fscore_support(token_true, token_pred, average="macro", zero_division=0)
        token_report = classification_report(token_true, token_pred, zero_division=0)
        token_cm = confusion_matrix(token_true, token_pred, labels=labels_order)
        token_cm_df = pd.DataFrame(token_cm, index=[f"true_{label}" for label in labels_order],
                                          columns=[f"pred_{label}" for label in labels_order])

        
        # Entity Level
        f1_entity = seq_f1_score(true_entity, pred_entity, mode="strict", scheme=IOB2, average="macro", zero_division=0)
        precision_entity = seq_precision_score(true_entity, pred_entity, mode="strict", scheme=IOB2, average="macro", zero_division=0)
        recall_entity = seq_recall_score(true_entity, pred_entity, mode="strict", scheme=IOB2, average="macro", zero_division=0)
        report_entity = seq_classification_report(true_entity, pred_entity, mode="strict", scheme=IOB2, zero_division=0)

        print("\nEntity-level classification report:")
        print(report_entity)

        print("\nToken-level classification report:")
        print(token_report)



        results = {"sent_words": sent_words,
                   "token_precision": token_precision,
                    "token_recall": token_recall,
                    "token_f1": token_f1,
                    "token_report": token_report,
                    "token_cm": token_cm_df,
                    "f1_entity": f1_entity,
                    "precision_entity": precision_entity,
                    "recall_entity": recall_entity,
                    "report_entity": report_entity,
                    "true_entity": true_entity,
                    "pred_entity": pred_entity,
                    "token_true": token_true,
                    "token_pred": token_pred}

        return results

In [29]:
eval_results = evaluation(final_model, test_loader)

Entity-level classification report:
              precision    recall  f1-score   support

         LOC       0.93      0.86      0.90      1668
        MISC       0.67      0.82      0.74       702
         ORG       0.82      0.81      0.81      1661
         PER       0.94      0.89      0.91      1617

   micro avg       0.86      0.85      0.85      5648
   macro avg       0.84      0.84      0.84      5648
weighted avg       0.87      0.85      0.86      5648


Token-level classification report:
              precision    recall  f1-score   support

       B-LOC       0.94      0.87      0.90      1668
      B-MISC       0.69      0.84      0.76       702
       B-ORG       0.84      0.84      0.84      1661
       B-PER       0.94      0.89      0.91      1617
       I-LOC       0.86      0.77      0.81       257
      I-MISC       0.61      0.72      0.66       216
       I-ORG       0.82      0.85      0.83       835
       I-PER       0.97      0.93      0.95      1156
           O       0.99      0.99      0.99     38323

    accuracy                           0.97     46435
   macro avg       0.85      0.86      0.85     46435
weighted avg       0.97      0.97      0.97     46435

In [39]:
# Save token level confusion matrix
eval_results["token_cm"].to_csv("../results/token_confusion_matrix.csv", index=True)

In [36]:
token_results = pd.DataFrame({"True": eval_results["token_true"], "Predicted": eval_results["token_pred"]})
token_results

        True Predicted
0          O         O
1          O         O
2      B-LOC     B-LOC
3          O         O
4          O         O
...      ...       ...
46430      O         O
46431      O         O
46432      O         O
46433  B-PER     B-PER
46434      O         O

[46435 rows x 2 columns]

In [40]:
# Save token level predictions
token_results.to_csv("../results/token_predictions.csv", index=False)

In [37]:
sentence_results = pd.DataFrame({"Sentence": [" ".join(words) for words in eval_results["sent_words"]],
                                 "True Tags": [" ".join(tags) for tags in eval_results["true_entity"]],
                                 "Predicted Tags": [" ".join(tags) for tags in eval_results["pred_entity"]]})

sentence_results

,Sentence,True Tags,Predicted Tags
0,"SOCCER - JAPAN GET LUCKY WIN , CHINA IN SURPRI...",O O B-LOC O O O O B-PER O O O O,O O B-LOC O O O O B-LOC O O O O
1,Nadim Ladki,B-PER I-PER,B-PER I-PER
2,"AL-AIN , United Arab Emirates 1996-12-06",B-LOC O B-LOC I-LOC I-LOC O,O O B-LOC I-LOC I-LOC O
3,Japan began the defence of their Asian Cup tit...,B-LOC O O O O O B-MISC I-MISC O O O O O O O B-...,B-LOC O O O O O B-MISC I-MISC O O O O O O O B-...
4,But China saw their luck desert them in the se...,O B-LOC O O O O O O O O O O O O O O O O O O O ...,O B-LOC O O O O O O O O O O O O O O O O O O O ...
...,...,...,...
3448,That is why this is so emotional a night for m...,O O O O O O O O O O O O O B-PER O O,O O O O O O O O O O O O O B-ORG O O
3449,""" It was the joy that we all had over the peri...",O O O O O O O O O O O O O O O O O O O O O O O ...,O O O O O O O O O O O O O O O O O O O O O O O ...
3450,"Charlton managed Ireland for 93 matches , duri...",B-PER O B-LOC O O O O O O O O O O O O O O O O ...,B-ORG O B-LOC O O O O O O O O O O O O O O O O ...
3451,He guided Ireland to two successive World Cup ...,O O B-LOC O O O B-MISC I-MISC O O O O O O B-MI...,O O B-LOC O O O B-MISC I-MISC O O O O O O B-MI...
3452,The lanky former Leeds United defender did not...,O O O B-ORG I-ORG O O O O O B-LOC O O O O O O ...,O O O B-ORG I-ORG O O O O O B-LOC O O O O O O ...

In [41]:
# Save sentence level predictions
sentence_results.to_csv("../results/sentence_predictions.csv", index=False)

In [31]:
print(*eval_results["true_entity"][:5], sep="\n")

['O', 'O', 'B-LOC', 'O', 'O', 'O', 'O', 'B-PER', 'O', 'O', 'O', 'O']
['B-PER', 'I-PER']
['B-LOC', 'O', 'B-LOC', 'I-LOC', 'I-LOC', 'O']
['B-LOC', 'O', 'O', 'O', 'O', 'O', 'B-MISC', 'I-MISC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
['O', 'B-LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-LOC', 'O']

In [32]:
print(*eval_results["token_true"][:10], sep="\n")

O
O
B-LOC
O
O
O
O
B-PER
O
O

The **final model** achieved an entity-level macro F1 score of `0.84`. 

The model performed strongest on **PER and LOC entities**, with F1 scores of `0.91 and 0.90`, while **MISC** was the weakest class with an F1 score of `0.74`. 

**Token-level accuracy** was `0.97`, but this is less informative for NER because the dataset contains many **O** labels. Therefore, entity-level F1 is used as the main evaluation metric.

### 8.1 Entity Level Evaluation

In [33]:
print(eval_results["report_entity"])

              precision    recall  f1-score   support

         LOC       0.93      0.86      0.90      1668
        MISC       0.67      0.82      0.74       702
         ORG       0.82      0.81      0.81      1661
         PER       0.94      0.89      0.91      1617

   micro avg       0.86      0.85      0.85      5648
   macro avg       0.84      0.84      0.84      5648
weighted avg       0.87      0.85      0.86      5648

The **final model** achieved an **entity-level** macro precision of `0.84`, recall of `0.84`, and macro **F1 score** of `0.84` on **test set**.

The model performed best on **PER entities**, achieving **F1 score** of `0.91`, followed by **LOC** with **F1 score** of `0.90`. **ORG** achieved a moderate **F1 score** of `0.81`, while **MISC** was the most challenging category with an **F1 score** of `0.74`.

**LOC**

- `Precision = 0.93`
- `Recall = 0.86`

The model was conservative when predicting location entities. Most predicted locations were correct, but some true locations were missed.

**MISC**

- `Precision =  0.67`
- `Recall = 0.82`

The model identified many MISC entities but also produced a relatively high number of false positives.

**PER**

- `Precision =  0.94`
- `Recall = 0.89`

Person entities were identified reliably with both high precision and recall.

**ORG**

- `Precision =  0.82`
- `Recall = 0.81`

The model achieved balanced performance on organisation entities, with precision and recall being very similar. This suggests that the model was equally likely to miss organisation names and produce incorrect organisation predictions.

**MISC** was the smallest entity category with only `702 examples`, while LOC, ORG, and PER all had more than `1600` examples. The lower number of training examples may have contributed to the lower performance on MISC entities, as the model had less data to learn from compared to the other classes.

### 8.2 Token Level Evaluation

In [71]:
print(eval_results["token_report"])

              precision    recall  f1-score   support

       B-LOC       0.94      0.87      0.90      1668
      B-MISC       0.69      0.84      0.76       702
       B-ORG       0.84      0.84      0.84      1661
       B-PER       0.94      0.89      0.91      1617
       I-LOC       0.86      0.77      0.81       257
      I-MISC       0.61      0.72      0.66       216
       I-ORG       0.82      0.85      0.83       835
       I-PER       0.97      0.93      0.95      1156
           O       0.99      0.99      0.99     38323

    accuracy                           0.97     46435
   macro avg       0.85      0.86      0.85     46435
weighted avg       0.97      0.97      0.97     46435

In [72]:
print(eval_results["token_cm"])

             pred_B-LOC  pred_B-MISC  pred_B-ORG  pred_B-PER  pred_I-LOC  \
true_B-LOC         1448           74          81          18           0
true_B-MISC           8          589          40           8           0
true_B-ORG           47           90        1387          42           0
true_B-PER           16           22          71        1438           1
true_I-LOC            1            0           0           0         198
true_I-MISC           0            7           2           1           0
true_I-ORG            6            1          20           0          17
true_I-PER            0            4           0           4           3
true_O               21           67          50          18          11

             pred_I-MISC  pred_I-ORG  pred_I-PER  pred_O
true_B-LOC             5           6           0      36
true_B-MISC            7           2           0      48
true_B-ORG             0          15           1      79
true_B-PER             0           2           7      60
true_I-LOC            10          30           6      12
true_I-MISC          155          15           3      33
true_I-ORG            22         711           9      49
true_I-PER             2          40        1077      26
true_O                53          49           4   38050

At the token level, the model achieved **accuracy** of `0.97`, **macro F1 score** of `0.85`, and **weighted F1 score** of `0.97`. The **weighted F1 score** is much higher because the dataset contains a large number of `O tokens`. Since these tokens were predicted correctly most of the time, they increase the overall score.

The model performed best on **PER** entities. **I-PER** achieved the highest `F1 score of 0.95`, while **B-PER** achieved `0.91`. **LOC** entities also achieved strong results, with **B-LOC** reaching an F1 score of `0.90`.

**MISC** was the most difficult entity type. **B-MISC** achieved `F1 score of 0.76`, while **I-MISC** achieved only `0.66`. This is similar to the entity-level results, where MISC also had the lowest performance.

Looking at **the confusion matrix,** a number of entity tokens were predicted as `O`. For example, `79 B-ORG` tokens, `60 B-PER` tokens and `48 B-MISC` tokens were **classified as non-entity tokens**. This means that the model sometimes failed to recognise entities even when they were present in the sentence.

There was also some **confusion between ORG and MISC** entities. For example, `90 B-ORG` tokens were predicted as **B-MISC** and `40 B-MISC` tokens were predicted as **B-ORG**. This explains why these two categories achieved lower scores than PER and LOC.

Overall, the token-level results were strong, especially for **PER and LOC** entities. However, the model still struggled with **MISC** entities and occasionally failed to detect entity tokens, predicting them as **O** instead.

### 8.3 Error Analysis

I focused on the confusion pairs with the highest number of errors, as these are likely to have the biggest effect on the overall performance of the model.

The first confusion pair I investigated was `B-ORG to B-MISC (90)`, as it occurred most frequently. I then looked at `B-LOC to B-ORG (81)` and `B-LOC to B-MISC (74)` to see if there were any common patterns behind these mistakes.

The classification report also shows that `MISC` had relatively high recall but lower precision than the other entity types. This means the model was able to find many MISC entities, but it also predicted MISC when the correct label was actually something else. This may explain why many ORG and LOC entities were predicted as MISC.

Another common error was predicting entity tokens as `O`. This means the model sometimes failed to recognise that a token belonged to an entity. By looking at the original sentences, I aimed to identify whether these errors were caused by limited context, ambiguous entity names, or incorrect entity boundaries.

#### 8.3.1 Tag Confusion

In [62]:
def tag_confusion(tag1, tag2, sentences, results):

    count = 0

    for i, (words, true_tags, pred_tags) in enumerate(zip(sentences, results["true_entity"], results["pred_entity"])):

        for true_tag, pred_tag in zip(true_tags, pred_tags):

            if true_tag == tag1 and pred_tag == tag2:

                count += 1

                print(f"\nSentence {i}")
                print(" ".join(words))
                print()

                for word, true_label, pred_label in zip(words, true_tags, pred_tags):
                    print(f"{word:20} {true_label:8} {pred_label:8}")

                print("-" * 80)

    print(f"\nTotal {tag1} - {tag2} errors: {count}")

##### B-ORG vs B-MISC

In [55]:
tag_confusion("B-ORG", "B-MISC", test_sents, eval_results)

Sentence 196
The Wallabies currently have no plans to make any special presentation to the 34-year-old winger but a full house of 75,000 spectators will still gather in the hope of witnessing one last moment of magic .

The                  O        O
Wallabies            B-ORG    B-MISC
currently            O        O
have                 O        O
no                   O        O
plans                O        O
to                   O        O
make                 O        O
any                  O        O
special              O        O
presentation         O        O
to                   O        O
the                  O        O
34-year-old          O        O
winger               O        O
but                  O        O
a                    O        O
full                 O        O
house                O        O
of                   O        O
75,000               O        O
spectators           O        O
will                 O        O
still                O        O
gather               O        O
in                   O        O
the                  O        O
hope                 O        O
of                   O        O
witnessing           O        O
one                  O        O
last                 O        O
moment               O        O
of                   O        O
magic                O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 355
Standings of National Hockey

Standings            O        O
of                   O        O
National             B-ORG    B-MISC
Hockey               I-ORG    I-MISC
--------------------------------------------------------------------------------

Sentence 396
TORONTO AT NY RANGERS

TORONTO              B-ORG    B-ORG
AT                   O        O
NY                   B-ORG    B-MISC
RANGERS              I-ORG    I-MISC
--------------------------------------------------------------------------------

Sentence 407
Results of National Hockey

Results              O        O
of                   O        O
National             B-ORG    B-MISC
Hockey               I-ORG    I-MISC
--------------------------------------------------------------------------------

Sentence 417
Marshall Faulk rushed for 101 yards and two touchdowns and Jason Belser returned an interception 44 yards for a score as the Colts improved to 8-6 , the same mark as the Eagles , who lost for the fourth time in five games .

Marshall             B-PER    B-PER
Faulk                I-PER    I-PER
rushed               O        O
for                  O        O
101                  O        O
yards                O        O
and                  O        O
two                  O        O
touchdowns           O        O
and                  O        O
Jason                B-PER    B-PER
Belser               I-PER    I-PER
returned             O        O
an                   O        O
interception         O        O
44                   O        O
yards                O        O
for                  O        O
a                    O        O
score                O        O
as                   O        O
the                  O        O
Colts                B-ORG    B-MISC
improved             O        O
to                   O        O
8-6                  O        O
,                    O        O
the                  O        O
same                 O        O
mark                 O        O
as                   O        O
the                  O        O
Eagles               B-ORG    B-PER
,                    O        O
who                  O        O
lost                 O        O
for                  O        O
the                  O        O
fourth               O        O
time                 O        O
in                   O        O
five                 O        O
games                O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 418
Paul Justin , starting for the sidelined Jim Harbaugh , was 14-of-23 for 144 yards and a touchdown for the the Colts , who played their last home game of the season .

Paul                 B-PER    B-PER
Justin               I-PER    I-PER
,                    O        O
starting             O        O
for                  O        O
the                  O        O
sidelined            O        O
Jim                  B-PER    B-PER
Harbaugh             I-PER    I-PER
,                    O        O
was                  O        O
14-of-23             O        O
for                  O        O
144                  O        O
yards                O        O
and                  O        O
a                    O        O
touchdown            O        O
for                  O        O
the                  O        O
the                  O        O
Colts                B-ORG    B-MISC
,                    O        O
who                  O        O
played               O        O
their                O        O
last                 O        O
home                 O        O
game                 O        O
of                   O        O
the                  O        O
season               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 420
The Eagles were held without a touchdown until the final five seconds .

The                  O        O
Eagles               B-ORG    B-MISC
were                 O        O
held                 O        O
without              O        O
a                    O        O
touchdown            O        O
until                O        O
the                  O        O
final                O        O
five                 O        O
seconds              O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 423
The Colts won despite the absence of injured starting defensive tackle Tony Siragusa , cornerback Ray Buchanan and linebacker Quentin Coryatt .

The                  O        O
Colts                B-ORG    B-MISC
won                  O        O
despite              O        O
the                  O        O
absence              O        O
of                   O        O
injured              O        O
starting             O        O
defensive            O        O
tackle               O        O
Tony                 B-PER    B-PER
Siragusa             I-PER    I-PER
,                    O        O
cornerback           O        O
Ray                  B-PER    B-PER
Buchanan             I-PER    I-PER
and                  O        O
linebacker           O        O
Quentin              B-PER    B-PER
Coryatt              I-PER    I-PER
.                    O        O
--------------------------------------------------------------------------------

Sentence 427
Third-stringer Kerwin Bell , a 1988 draft choice of the Miami Dolphins , made his NFL debut and was 5-of-5 for 75 yards , including a 20-yard scoring strike to Marvin Harrison in the third period .

Third-stringer       O        O
Kerwin               B-PER    B-PER
Bell                 I-PER    I-PER
,                    O        O
a                    O        O
1988                 O        O
draft                O        O
choice               O        O
of                   O        O
the                  O        O
Miami                B-ORG    B-ORG
Dolphins             I-ORG    I-ORG
,                    O        O
made                 O        O
his                  O        O
NFL                  B-ORG    B-MISC
debut                O        O
and                  O        O
was                  O        O
5-of-5               O        O
for                  O        O
75                   O        O
yards                O        O
,                    O        O
including            O        O
a                    O        O
20-yard              O        O
scoring              O        O
strike               O        O
to                   O        O
Marvin               B-PER    B-PER
Harrison             I-PER    I-PER
in                   O        O
the                  O        O
third                O        O
period               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 433
Standings of National

Standings            O        O
of                   O        O
National             B-ORG    B-MISC
--------------------------------------------------------------------------------

Sentence 487
National Football League

National             B-ORG    B-MISC
Football             I-ORG    I-MISC
League               I-ORG    I-MISC
--------------------------------------------------------------------------------

Sentence 554
Result of National Football

Result               O        O
of                   O        O
National             B-ORG    B-MISC
Football             B-LOC    I-MISC
--------------------------------------------------------------------------------

Sentence 906
RADIO ROMANIA AFTERNOON HEALINES AT 4 PM .

RADIO                B-ORG    B-MISC
ROMANIA              I-ORG    I-MISC
AFTERNOON            O        O
HEALINES             O        O
AT                   O        O
4                    O        O
PM                   O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 951
So far this year Zywiec , whose full name is Zaklady Piwowarskie w Zywcu SA , has netted six million zlotys on sales of 224 million zlotys .

So                   O        O
far                  O        O
this                 O        O
year                 O        O
Zywiec               B-ORG    B-MISC
,                    O        O
whose                O        O
full                 O        O
name                 O        O
is                   O        O
Zaklady              B-ORG    B-MISC
Piwowarskie          I-ORG    I-MISC
w                    I-ORG    O
Zywcu                I-ORG    B-ORG
SA                   I-ORG    I-ORG
,                    O        O
has                  O        O
netted               O        O
six                  O        O
million              O        O
zlotys               O        O
on                   O        O
sales                O        O
of                   O        O
224                  O        O
million              O        O
zlotys               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 951
So far this year Zywiec , whose full name is Zaklady Piwowarskie w Zywcu SA , has netted six million zlotys on sales of 224 million zlotys .

So                   O        O
far                  O        O
this                 O        O
year                 O        O
Zywiec               B-ORG    B-MISC
,                    O        O
whose                O        O
full                 O        O
name                 O        O
is                   O        O
Zaklady              B-ORG    B-MISC
Piwowarskie          I-ORG    I-MISC
w                    I-ORG    O
Zywcu                I-ORG    B-ORG
SA                   I-ORG    I-ORG
,                    O        O
has                  O        O
netted               O        O
six                  O        O
million              O        O
zlotys               O        O
on                   O        O
sales                O        O
of                   O        O
224                  O        O
million              O        O
zlotys               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 958
Earlier this year South African Breweries Ltd ( SAB ) bought strategic stakes in the unlisted Lech and Tychy brewers , which together hold more than 20 percent of the market , and Australia 's Brewpole BV has a controlling stake in Poland 's larges t brewery , Elbrewery Company Ltd. ( EB ) .

Earlier              O        O
this                 O        O
year                 O        O
South                B-ORG    B-ORG
African              I-ORG    I-ORG
Breweries            I-ORG    I-ORG
Ltd                  I-ORG    I-ORG
(                    O        O
SAB                  B-ORG    B-ORG
)                    O        O
bought               O        O
strategic            O        O
stakes               O        O
in                   O        O
the                  O        O
unlisted             O        O
Lech                 B-ORG    B-ORG
and                  O        I-ORG
Tychy                B-ORG    I-ORG
brewers              O        O
,                    O        O
which                O        O
together             O        O
hold                 O        O
more                 O        O
than                 O        O
20                   O        O
percent              O        O
of                   O        O
the                  O        O
market               O        O
,                    O        O
and                  O        O
Australia            B-LOC    B-LOC
's                   O        O
Brewpole             B-ORG    B-ORG
BV                   I-ORG    I-ORG
has                  O        O
a                    O        O
controlling          O        O
stake                O        O
in                   O        O
Poland               B-LOC    B-LOC
's                   O        O
larges               O        O
t                    O        O
brewery              O        O
,                    O        O
Elbrewery            B-ORG    B-ORG
Company              I-ORG    I-ORG
Ltd.                 I-ORG    O
(                    O        O
EB                   B-ORG    B-MISC
)                    O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 959
Van Boxmeer said the tough competition had prevented Zywiec from raising prices in line with inflation , which had added to the pressure on the firm 's margins .

Van                  B-PER    B-PER
Boxmeer              I-PER    I-PER
said                 O        O
the                  O        O
tough                O        O
competition          O        O
had                  O        O
prevented            O        O
Zywiec               B-ORG    B-MISC
from                 O        O
raising              O        O
prices               O        O
in                   O        O
line                 O        O
with                 O        O
inflation            O        O
,                    O        O
which                O        O
had                  O        O
added                O        O
to                   O        O
the                  O        O
pressure             O        O
on                   O        O
the                  O        O
firm                 O        O
's                   O        O
margins              O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 962
Some analysts say cheaper but high-quality Czech imports could invade Poland once tariffs for CEFTA countries are lifted in 1998 , but van Boxmeer says such a threat might be exaggerated despite the Czech beer market 's overcapacity .

Some                 O        O
analysts             O        O
say                  O        O
cheaper              O        O
but                  O        O
high-quality         O        O
Czech                B-LOC    B-MISC
imports              O        O
could                O        O
invade               O        O
Poland               B-LOC    B-LOC
once                 O        O
tariffs              O        O
for                  O        O
CEFTA                B-ORG    B-MISC
countries            O        O
are                  O        O
lifted               O        O
in                   O        O
1998                 O        O
,                    O        O
but                  O        O
van                  O        B-PER
Boxmeer              B-PER    I-PER
says                 O        O
such                 O        O
a                    O        O
threat               O        O
might                O        O
be                   O        O
exaggerated          O        O
despite              O        O
the                  O        O
Czech                B-LOC    B-MISC
beer                 O        O
market               O        O
's                   O        O
overcapacity         O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 965
Van Boxmeer said Zywiec had its eye on Okocim , which has said it would start producing Carlsberg beer next year , but that Zywiec 's potential production of Heineken was a medium-term possibility rather than a short-term one .

Van                  B-PER    B-PER
Boxmeer              I-PER    I-PER
said                 O        O
Zywiec               B-ORG    B-PER
had                  O        O
its                  O        O
eye                  O        O
on                   O        O
Okocim               B-ORG    B-MISC
,                    O        O
which                O        O
has                  O        O
said                 O        O
it                   O        O
would                O        O
start                O        O
producing            O        O
Carlsberg            B-ORG    B-MISC
beer                 O        O
next                 O        O
year                 O        O
,                    O        O
but                  O        O
that                 O        O
Zywiec               B-ORG    B-PER
's                   O        O
potential            O        O
production           O        O
of                   O        O
Heineken             B-ORG    B-PER
was                  O        O
a                    O        O
medium-term          O        O
possibility          O        O
rather               O        O
than                 O        O
a                    O        O
short-term           O        O
one                  O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 965
Van Boxmeer said Zywiec had its eye on Okocim , which has said it would start producing Carlsberg beer next year , but that Zywiec 's potential production of Heineken was a medium-term possibility rather than a short-term one .

Van                  B-PER    B-PER
Boxmeer              I-PER    I-PER
said                 O        O
Zywiec               B-ORG    B-PER
had                  O        O
its                  O        O
eye                  O        O
on                   O        O
Okocim               B-ORG    B-MISC
,                    O        O
which                O        O
has                  O        O
said                 O        O
it                   O        O
would                O        O
start                O        O
producing            O        O
Carlsberg            B-ORG    B-MISC
beer                 O        O
next                 O        O
year                 O        O
,                    O        O
but                  O        O
that                 O        O
Zywiec               B-ORG    B-PER
's                   O        O
potential            O        O
production           O        O
of                   O        O
Heineken             B-ORG    B-PER
was                  O        O
a                    O        O
medium-term          O        O
possibility          O        O
rather               O        O
than                 O        O
a                    O        O
short-term           O        O

The error analysis showed that the model most often confused **ORG** entities with **MISC** entities. After looking at the sentences, I found that this was particularly common for `sports team names`. For example, **Wallabies** and **Colts** were predicted as MISC instead of ORG. However, this was not always the case. Some team names, such as **Eagles** and **Barbarians**, were predicted as PER in some examples, suggesting that the model found these names difficult to classify consistently.

I also noticed that some `short organisation names` and `acronyms`, such as **NFL**, were predicted as MISC. Since these names provide limited lexical information, the model may have relied more on the surrounding context, which sometimes resulted in the wrong entity type being predicted.

These examples help explain why MISC achieved relatively high recall but lower precision. The model identified many MISC entities correctly, but it also predicted MISC for entities that actually belonged to other classes, especially ORG.

##### B-LOC vs B-ORG

In [57]:
tag_confusion("B-LOC", "B-ORG", test_sents, eval_results)

Sentence 82
China 0 Uzbekistan 2 ( halftime 0-0 )

China                B-LOC    B-LOC
0                    O        O
Uzbekistan           B-LOC    B-ORG
2                    O        O
(                    O        O
halftime             O        O
0-0                  O        O
)                    O        O
--------------------------------------------------------------------------------

Sentence 87
Uzbekistan 1 1 0 0 2 0 3

Uzbekistan           B-LOC    B-ORG
1                    O        O
1                    O        O
0                    O        O
0                    O        O
2                    O        O
0                    O        O
3                    O        O
--------------------------------------------------------------------------------

Sentence 155
Bowyer , who moved to the Yorkshire club in August for 3.5 million pounds ( $ 5.8 million ) , was expected to play against Middlesbrough on Saturday .

Bowyer               B-PER    B-PER
,                    O        O
who                  O        O
moved                O        O
to                   O        O
the                  O        O
Yorkshire            B-LOC    B-ORG
club                 O        O
in                   O        O
August               O        O
for                  O        O
3.5                  O        O
million              O        O
pounds               O        O
(                    O        O
$                    O        O
5.8                  O        O
million              O        O
)                    O        O
,                    O        O
was                  O        O
expected             O        O
to                   O        O
play                 O        O
against              O        O
Middlesbrough        B-ORG    B-ORG
on                   O        O
Saturday             O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 202
Barbarians - 15 - Tim Stimpson ( England ) ; 14 - Nigel Walker ( Wales ) , 13 - Allan Bateman ( Wales ) , 12 - Gregor Townsend ( Scotland ) , 11 - Tony Underwood ( England ) ; 10 - Rob Andrew ( England ) , 9 - Rob Howley ( Wales ) ; 8 - Scott Quinnell ( Wales ) , 7 - Neil Back ( England ) , 6 - Dale McIntosh ( Pontypridd ) , 5 - Ian Jones ( New Zealand ) , 4 - Craig Quinnell ( Wales ) , 3 - Darren Garforth ( Leicester ) , 2 - Norm Hewitt ( New Zealand ) , 1 - Nick Popplewell ( Ireland ) .

Barbarians           B-ORG    B-PER
-                    O        O
15                   O        O
-                    O        O
Tim                  B-PER    B-PER
Stimpson             I-PER    I-PER
(                    O        O
England              B-LOC    B-LOC
)                    O        O
;                    O        O
14                   O        O
-                    O        O
Nigel                B-PER    B-PER
Walker               I-PER    I-PER
(                    O        O
Wales                B-LOC    B-LOC
)                    O        O
,                    O        O
13                   O        O
-                    O        O
Allan                B-PER    B-PER
Bateman              I-PER    I-PER
(                    O        O
Wales                B-LOC    B-LOC
)                    O        O
,                    O        O
12                   O        O
-                    O        O
Gregor               B-PER    B-PER
Townsend             I-PER    I-PER
(                    O        O
Scotland             B-LOC    B-LOC
)                    O        O
,                    O        O
11                   O        O
-                    O        O
Tony                 B-PER    B-PER
Underwood            I-PER    I-PER
(                    O        O
England              B-LOC    B-LOC
)                    O        O
;                    O        O
10                   O        O
-                    O        O
Rob                  B-PER    B-PER
Andrew               I-PER    I-PER
(                    O        O
England              B-LOC    B-LOC
)                    O        O
,                    O        O
9                    O        O
-                    O        O
Rob                  B-PER    B-PER
Howley               I-PER    I-PER
(                    O        O
Wales                B-LOC    B-LOC
)                    O        O
;                    O        O
8                    O        O
-                    O        O
Scott                B-PER    B-PER
Quinnell             I-PER    I-PER
(                    O        O
Wales                B-LOC    B-LOC
)                    O        O
,                    O        O
7                    O        O
-                    O        O
Neil                 B-PER    B-PER
Back                 I-PER    I-PER
(                    O        O
England              B-LOC    B-LOC
)                    O        O
,                    O        O
6                    O        O
-                    O        O
Dale                 B-PER    B-PER
McIntosh             I-PER    I-PER
(                    O        O
Pontypridd           B-LOC    O
)                    O        O
,                    O        O
5                    O        O
-                    O        O
Ian                  B-PER    B-PER
Jones                I-PER    I-PER
(                    O        O
New                  B-LOC    B-LOC
Zealand              I-LOC    I-LOC
)                    O        O
,                    O        O
4                    O        O
-                    O        O
Craig                B-PER    B-PER
Quinnell             I-PER    I-PER
(                    O        O
Wales                B-LOC    B-LOC
)                    O        O
,                    O        O
3                    O        O
-                    O        O
Darren               B-PER    B-PER
Garforth             I-PER    I-PER
(                    O        O
Leicester            B-LOC    B-ORG
)                    O        O
,                    O        O
2                    O        O
-                    O        O
Norm                 B-PER    B-PER
Hewitt               I-PER    I-PER
(                    O        O
New                  B-LOC    B-LOC
Zealand              I-LOC    I-LOC
)                    O        O
,                    O        O
1                    O        O
-                    O        O
Nick                 B-PER    B-PER
Popplewell           I-PER    I-PER
(                    O        O
Ireland              B-LOC    B-LOC
)                    O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 300
West Indies batsman Brian Lara suffered another blow to his Australian tour , after already being disciplined for misconduct , when he was dismissed cheaply in the first limited overs match against Australia on Friday .

West                 B-LOC    B-ORG
Indies               I-LOC    I-ORG
batsman              O        O
Brian                B-PER    B-PER
Lara                 I-PER    I-PER
suffered             O        O
another              O        O
blow                 O        O
to                   O        O
his                  O        O
Australian           B-MISC   B-MISC
tour                 O        O
,                    O        O
after                O        O
already              O        O
being                O        O
disciplined          O        O
for                  O        O
misconduct           O        O
,                    O        O
when                 O        O
he                   O        O
was                  O        O
dismissed            O        O
cheaply              O        O
in                   O        O
the                  O        O
first                O        O
limited              O        O
overs                O        O
match                O        O
against              O        O
Australia            B-LOC    B-LOC
on                   O        O
Friday               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 303
West Indies were 53 for two in 15 overs when rain stopped play at the Melbourne Cricket Ground after captain Courtney Walsh won the toss and elected to bat .

West                 B-LOC    B-LOC
Indies               I-LOC    I-LOC
were                 O        O
53                   O        O
for                  O        O
two                  O        O
in                   O        O
15                   O        O
overs                O        O
when                 O        O
rain                 O        O
stopped              O        O
play                 O        O
at                   O        O
the                  O        O
Melbourne            B-LOC    B-ORG
Cricket              I-LOC    I-ORG
Ground               I-LOC    I-ORG
after                O        O
captain              O        O
Courtney             B-PER    B-PER
Walsh                I-PER    I-PER
won                  O        O
the                  O        O
toss                 O        O
and                  O        O
elected              O        O
to                   O        O
bat                  O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 316
West Indies captain Courtney Walsh elected to bat after winning the toss in the first match in the World Series limited overs competition against Australia at the Melbourne Cricket Ground on Friday .

West                 B-LOC    B-ORG
Indies               I-LOC    I-ORG
captain              O        O
Courtney             B-PER    B-PER
Walsh                I-PER    I-PER
elected              O        O
to                   O        O
bat                  O        O
after                O        O
winning              O        O
the                  O        O
toss                 O        O
in                   O        O
the                  O        O
first                O        O
match                O        O
in                   O        O
the                  O        O
World                B-MISC   B-MISC
Series               I-MISC   I-MISC
limited              O        O
overs                O        O
competition          O        O
against              O        O
Australia            B-LOC    B-LOC
at                   O        O
the                  O        O
Melbourne            B-LOC    B-LOC
Cricket              O        I-LOC
Ground               O        I-LOC
on                   O        O
Friday               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 321
BALI 1996-12-06

BALI                 B-LOC    B-ORG
1996-12-06           O        O
--------------------------------------------------------------------------------

Sentence 419
Indianapolis closes with games at Kansas City and Cincinnati .

Indianapolis         B-LOC    B-ORG
closes               O        O
with                 O        O
games                O        O
at                   O        O
Kansas               B-LOC    B-LOC
City                 I-LOC    I-LOC
and                  O        O
Cincinnati           B-LOC    B-LOC
.                    O        O
--------------------------------------------------------------------------------

Sentence 679
Karlsruhe 3 ( Reich 29th , Carl 44th , Dundee 69th ) Freiburg 0 .

Karlsruhe            B-LOC    B-ORG
3                    O        O
(                    O        O
Reich                B-PER    B-PER
29th                 O        O
,                    O        O
Carl                 B-PER    B-PER
44th                 O        O
,                    O        O
Dundee               B-ORG    B-PER
69th                 O        O
)                    O        O
Freiburg             B-LOC    B-ORG
0                    O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 679
Karlsruhe 3 ( Reich 29th , Carl 44th , Dundee 69th ) Freiburg 0 .

Karlsruhe            B-LOC    B-ORG
3                    O        O
(                    O        O
Reich                B-PER    B-PER
29th                 O        O
,                    O        O
Carl                 B-PER    B-PER
44th                 O        O
,                    O        O
Dundee               B-ORG    B-PER
69th                 O        O
)                    O        O
Freiburg             B-LOC    B-ORG
0                    O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 913
* The international airport in Timisoara and the domestic airports in Arad , Oradea and Sibiu were closed due to fog .

*                    O        O
The                  O        O
international        O        O
airport              O        O
in                   O        O
Timisoara            B-LOC    B-LOC
and                  O        O
the                  O        O
domestic             O        O
airports             O        O
in                   O        O
Arad                 B-LOC    B-MISC
,                    O        O
Oradea               B-LOC    B-LOC
and                  O        O
Sibiu                B-LOC    B-ORG
were                 O        O
closed               O        O
due                  O        O
to                   O        O
fog                  O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 982
The UK Department of Transport on Friday said that the latest round of " open skies " talks with the U.S. had ended with no deal on liberalising the transatlantic flight market and no date set for when talks would restart .

The                  O        O
UK                   B-LOC    B-ORG
Department           B-ORG    I-ORG
of                   I-ORG    I-ORG
Transport            I-ORG    I-ORG
on                   O        O
Friday               O        O
said                 O        O
that                 O        O
the                  O        O
latest               O        O
round                O        O
of                   O        O
"                    O        O
open                 O        O
skies                O        O
"                    O        O
talks                O        O
with                 O        O
the                  O        O
U.S.                 B-LOC    B-LOC
had                  O        O
ended                O        O
with                 O        O
no                   O        O
deal                 O        O
on                   O        O
liberalising         O        O
the                  O        O
transatlantic        O        O
flight               O        O
market               O        O
and                  O        O
no                   O        O
date                 O        O
set                  O        O
for                  O        O
when                 O        O
talks                O        O
would                O        O
restart              O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 1000
BELFAST 1996-12-06

BELFAST              B-LOC    B-ORG
1996-12-06           O        O
--------------------------------------------------------------------------------

Sentence 1058
The government still has a majority , " a spokesman from Major 's office in Downing Street said .

The                  O        O
government           O        O
still                O        O
has                  O        O
a                    O        O
majority             O        O
,                    O        O
"                    O        O
a                    O        O
spokesman            O        O
from                 O        O
Major                B-PER    B-ORG
's                   O        O
office               O        O
in                   O        O
Downing              B-LOC    B-ORG
Street               I-LOC    I-ORG
said                 O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 1068
The contract involved upgrading the flight data processing system at the Oceanic Control Centre in Prestwick in south west Scotland for National Air Traffic Services Ltd ( NATS ) , subsidiary of the Civil Aviation Authority .

The                  O        O
contract             O        O
involved             O        O
upgrading            O        O
the                  O        O
flight               O        O
data                 O        O
processing           O        O
system               O        O
at                   O        O
the                  O        O
Oceanic              B-LOC    B-ORG
Control              I-LOC    I-ORG
Centre               I-LOC    I-ORG
in                   O        O
Prestwick            B-LOC    B-LOC
in                   O        O
south                O        O
west                 O        O
Scotland             B-LOC    B-LOC
for                  O        O
National             B-ORG    B-ORG
Air                  I-ORG    I-ORG
Traffic              I-ORG    I-ORG
Services             I-ORG    I-ORG
Ltd                  I-ORG    I-ORG
(                    O        O
NATS                 B-ORG    B-ORG
)                    O        O
,                    O        O
subsidiary           O        O
of                   O        O
the                  O        O
Civil                B-ORG    B-ORG
Aviation             I-ORG    I-ORG
Authority            I-ORG    I-ORG
.                    O        O
--------------------------------------------------------------------------------

Sentence 1102
( ( Winnipeg bureau 204-947-3548 ) )

(                    O        O
(                    O        O
Winnipeg             B-LOC    B-ORG
bureau               O        O
204-947-3548         O        O
)                    O        O
)                    O        O
--------------------------------------------------------------------------------

Sentence 1110
Vancouver 5 7

Vancouver            B-LOC    B-ORG
5                    O        O
7                    O        O
--------------------------------------------------------------------------------

Sentence 1153
Homestake Mining Co tops Wall Street 's list as the most likely white knight buyer for Santa Fe Pacific Gold Corp if Santa Fe rejects unsolicited suitor Newmont Mining Corp .

Homestake            B-ORG    B-ORG
Mining               I-ORG    I-ORG
Co                   I-ORG    I-ORG
tops                 O        O
Wall                 B-LOC    B-ORG
Street               I-LOC    I-ORG
's                   O        O
list                 O        O
as                   O        O
the                  O        O
most                 O        O
likely               O        O
white                O        O
knight               O        O
buyer                O        O
for                  O        O
Santa                B-ORG    B-ORG
Fe                   I-ORG    I-ORG
Pacific              I-ORG    I-ORG
Gold                 I-ORG    I-ORG
Corp                 I-ORG    I-ORG
if                   O        O
Santa                B-ORG    B-ORG
Fe                   I-ORG    I-ORG
rejects              O        O
unsolicited          O        O
suitor               O        O
Newmont              B-ORG    B-ORG
Mining               I-ORG    I-ORG
Corp                 I-ORG    I-ORG
.                    O        O
--------------------------------------------------------------------------------

Sentence 1173

The `B-LOC to B-ORG` errors show that many location names were predicted as organisations. After looking at the examples, I noticed that this happened most often in `sports-related sentences`. Names such as Wimbledon, Victoria and West Indies can refer to `both geographical locations and sports teams`, creating **ambiguity** for the model. 

Another common pattern was `location names appearing as part of organisation names`, such as UK Department of Transport and Budapest Bank. This also creates **ambiguity**, as the location name is embedded within the name of an organisation.

I also found several errors in headlines and score tables, where only a place name was provided with very little surrounding context. These examples suggest that many of the `B-LOC to B-ORG` errors were caused by ambiguity and limited contextual information.

##### B-LOC vs B-MISC

In [58]:
tag_confusion("B-LOC", "B-MISC", test_sents, eval_results)

Sentence 4
But China saw their luck desert them in the second match of the group , crashing to a surprise 2-0 defeat to newcomers Uzbekistan .

But                  O        O
China                B-LOC    B-LOC
saw                  O        O
their                O        O
luck                 O        O
desert               O        O
them                 O        O
in                   O        O
the                  O        O
second               O        O
match                O        O
of                   O        O
the                  O        O
group                O        O
,                    O        O
crashing             O        O
to                   O        O
a                    O        O
surprise             O        O
2-0                  O        O
defeat               O        O
to                   O        O
newcomers            O        O
Uzbekistan           B-LOC    B-MISC
.                    O        O
--------------------------------------------------------------------------------

Sentence 91
CRICKET - PAKISTAN V NEW ZEALAND ONE-DAY SCOREBOARD .

CRICKET              O        O
-                    O        O
PAKISTAN             B-LOC    B-LOC
V                    O        O
NEW                  B-LOC    B-MISC
ZEALAND              I-LOC    I-MISC
ONE-DAY              O        O
SCOREBOARD           O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 198
" Campo has a massive following in this country and has had the public with him ever since he first played here in 1984 , " said Andrew , also likely to be making his final Twickenham appearance .

"                    O        O
Campo                B-PER    B-ORG
has                  O        O
a                    O        O
massive              O        O
following            O        O
in                   O        O
this                 O        O
country              O        O
and                  O        O
has                  O        O
had                  O        O
the                  O        O
public               O        O
with                 O        O
him                  O        O
ever                 O        O
since                O        O
he                   O        O
first                O        O
played               O        O
here                 O        O
in                   O        O
1984                 O        O
,                    O        O
"                    O        O
said                 O        O
Andrew               B-PER    B-PER
,                    O        O
also                 O        O
likely               O        O
to                   O        O
be                   O        O
making               O        O
his                  O        O
final                O        O
Twickenham           B-LOC    B-MISC
appearance           O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 206
Leading second round scores in the Zimbabwe Open at the par-72 Chapman Golf Club on Friday ( South African unless stated ) : 132 Des Terblanche 65 67 133 Mark McNulty ( Zimbabwe ) 72 61 134 Steve van Vuuren 65 69 136 Nick Price ( Zimbabwe ) 68 68 , Justin Hobday 71 65 ,

Leading              O        O
second               O        O
round                O        O
scores               O        O
in                   O        O
the                  O        O
Zimbabwe             B-MISC   B-MISC
Open                 I-MISC   I-MISC
at                   O        O
the                  O        O
par-72               O        O
Chapman              B-LOC    B-MISC
Golf                 I-LOC    I-MISC
Club                 I-LOC    O
on                   O        O
Friday               O        O
(                    O        O
South                B-MISC   B-MISC
African              I-MISC   I-MISC
unless               O        O
stated               O        O
)                    O        O
:                    O        O
132                  O        O
Des                  B-PER    B-PER
Terblanche           I-PER    I-PER
65                   O        O
67                   O        O
133                  O        O
Mark                 B-PER    B-PER
McNulty              I-PER    I-PER
(                    O        O
Zimbabwe             B-LOC    B-LOC
)                    O        O
72                   O        O
61                   O        O
134                  O        O
Steve                B-PER    B-PER
van                  I-PER    I-PER
Vuuren               I-PER    I-PER
65                   O        O
69                   O        O
136                  O        O
Nick                 B-PER    B-PER
Price                I-PER    I-PER
(                    O        O
Zimbabwe             B-LOC    B-LOC
)                    O        O
68                   O        O
68                   O        O
,                    O        O
Justin               B-PER    B-PER
Hobday               I-PER    I-PER
71                   O        O
65                   O        O
,                    O        O
--------------------------------------------------------------------------------

Sentence 290
Scores : West Indies 172 all out in 49.2 overs ( Shivnarine Chanderpaul 54 ) ; Australia 173-5 in 48.4 overs ( Greg Blewett 57 not out ) .

Scores               O        O
:                    O        O
West                 B-LOC    B-MISC
Indies               I-LOC    I-MISC
172                  O        O
all                  O        O
out                  O        O
in                   O        O
49.2                 O        O
overs                O        O
(                    O        O
Shivnarine           B-PER    B-PER
Chanderpaul          I-PER    I-PER
54                   O        O
)                    O        O
;                    O        O
Australia            B-LOC    B-LOC
173-5                O        O
in                   O        O
48.4                 O        O
overs                O        O
(                    O        O
Greg                 B-PER    B-PER
Blewett              I-PER    I-PER
57                   O        O
not                  O        O
out                  O        O
)                    O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 367
ATLANTIC DIVISION

ATLANTIC             B-LOC    B-MISC
DIVISION             O        I-MISC
--------------------------------------------------------------------------------

Sentence 385
PACIFIC DIVISION

PACIFIC              B-LOC    B-MISC
DIVISION             O        I-MISC
--------------------------------------------------------------------------------

Sentence 437
ATLANTIC DIVISION

ATLANTIC             B-LOC    B-MISC
DIVISION             O        I-MISC
--------------------------------------------------------------------------------

Sentence 466
PACIFIC DIVISION

PACIFIC              B-LOC    B-MISC
DIVISION             O        I-MISC
--------------------------------------------------------------------------------

Sentence 831
Lazio have injury doubts about striker Pierluigi Casiraghi , Czech midfielder Pavel Nedved and defender Paolo Negro , while Roma present a full strength side led by Argentine Abel Balbo , Marco Delvecchio and Francesco Totti in attack .

Lazio                B-ORG    B-ORG
have                 O        O
injury               O        O
doubts               O        O
about                O        O
striker              O        O
Pierluigi            B-PER    B-PER
Casiraghi            I-PER    I-PER
,                    O        O
Czech                B-LOC    B-MISC
midfielder           O        O
Pavel                B-PER    B-PER
Nedved               I-PER    I-PER
and                  O        O
defender             O        O
Paolo                B-PER    B-PER
Negro                I-PER    I-PER
,                    O        O
while                O        O
Roma                 B-ORG    B-ORG
present              O        O
a                    O        O
full                 O        O
strength             O        O
side                 O        O
led                  O        O
by                   O        O
Argentine            B-MISC   B-MISC
Abel                 B-PER    B-PER
Balbo                I-PER    I-PER
,                    O        O
Marco                B-PER    B-PER
Delvecchio           I-PER    I-PER
and                  O        O
Francesco            B-PER    B-PER
Totti                I-PER    I-PER
in                   O        O
attack               O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 892
Czech President Vaclav Havel on Friday welcomed the appointment of Madeleine Albright , who is of Czech extraction , as the United States ' first woman Secretary of State .

Czech                B-LOC    B-MISC
President            O        O
Vaclav               B-PER    B-PER
Havel                I-PER    I-PER
on                   O        O
Friday               O        O
welcomed             O        O
the                  O        O
appointment          O        O
of                   O        O
Madeleine            B-PER    B-PER
Albright             I-PER    I-PER
,                    O        O
who                  O        O
is                   O        O
of                   O        O
Czech                B-LOC    B-MISC
extraction           O        O
,                    O        O
as                   O        O
the                  O        O
United               B-LOC    B-LOC
States               I-LOC    I-LOC
'                    O        O
first                O        O
woman                O        O
Secretary            O        O
of                   O        O
State                O        B-ORG
.                    O        O
--------------------------------------------------------------------------------

Sentence 892
Czech President Vaclav Havel on Friday welcomed the appointment of Madeleine Albright , who is of Czech extraction , as the United States ' first woman Secretary of State .

Czech                B-LOC    B-MISC
President            O        O
Vaclav               B-PER    B-PER
Havel                I-PER    I-PER
on                   O        O
Friday               O        O
welcomed             O        O
the                  O        O
appointment          O        O
of                   O        O
Madeleine            B-PER    B-PER
Albright             I-PER    I-PER
,                    O        O
who                  O        O
is                   O        O
of                   O        O
Czech                B-LOC    B-MISC
extraction           O        O
,                    O        O
as                   O        O
the                  O        O
United               B-LOC    B-LOC
States               I-LOC    I-LOC
'                    O        O
first                O        O
woman                O        O
Secretary            O        O
of                   O        O
State                O        B-ORG
.                    O        O
--------------------------------------------------------------------------------

Sentence 901
Czech diplomats , seeking to have their country included in the expected expansion of NATO , praised the selection of Albright , known to be a strong supporter of alliance 's integration of former Soveit-bloc countries .

Czech                B-LOC    B-MISC
diplomats            O        O
,                    O        O
seeking              O        O
to                   O        O
have                 O        O
their                O        O
country              O        O
included             O        O
in                   O        O
the                  O        O
expected             O        O
expansion            O        O
of                   O        O
NATO                 B-ORG    B-ORG
,                    O        O
praised              O        O
the                  O        O
selection            O        O
of                   O        O
Albright             B-PER    B-PER
,                    O        O
known                O        O
to                   O        O
be                   O        O
a                    O        O
strong               O        O
supporter            O        O
of                   O        O
alliance             O        O
's                   O        O
integration          O        O
of                   O        O
former               O        O
Soveit-bloc          B-MISC   B-MISC
countries            O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 905
Czech ambassador to the United Nations , Karel Kovanda , told the daily Mlada Fronta Dnes that Albright " is a little light in our diplomatic heaven , " but warned against expecting her to exert any influence in favour of the Czechs .

Czech                B-LOC    B-MISC
ambassador           O        O
to                   O        O
the                  O        O
United               B-ORG    B-ORG
Nations              I-ORG    I-ORG
,                    O        O
Karel                B-PER    B-PER
Kovanda              I-PER    I-PER
,                    O        O
told                 O        O
the                  O        O
daily                O        O
Mlada                B-ORG    B-ORG
Fronta               I-ORG    I-ORG
Dnes                 I-ORG    O
that                 O        O
Albright             B-PER    B-MISC
"                    O        O
is                   O        O
a                    O        O
little               O        O
light                O        O
in                   O        O
our                  O        O
diplomatic           O        O
heaven               O        O
,                    O        O
"                    O        O
but                  O        O
warned               O        O
against              O        O
expecting            O        O
her                  O        O
to                   O        O
exert                O        O
any                  O        O
influence            O        O
in                   O        O
favour               O        O
of                   O        O
the                  O        O
Czechs               B-MISC   B-MISC
.                    O        O
--------------------------------------------------------------------------------

Sentence 913
* The international airport in Timisoara and the domestic airports in Arad , Oradea and Sibiu were closed due to fog .

*                    O        O
The                  O        O
international        O        O
airport              O        O
in                   O        O
Timisoara            B-LOC    B-LOC
and                  O        O
the                  O        O
domestic             O        O
airports             O        O
in                   O        O
Arad                 B-LOC    B-MISC
,                    O        O
Oradea               B-LOC    B-LOC
and                  O        O
Sibiu                B-LOC    B-ORG
were                 O        O
closed               O        O
due                  O        O
to                   O        O
fog                  O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 920
He said after June general elections in which the ruling three-party coalition lost its parliamentary majority , the ODS executive , led by Prime Minister Vaclav Klaus , had developed proposals on these subjects to present at the congress on Saturday in the Czech second city Brno .

He                   O        O
said                 O        O
after                O        O
June                 O        O
general              O        O
elections            O        O
in                   O        O
which                O        O
the                  O        O
ruling               O        O
three-party          O        O
coalition            O        O
lost                 O        O
its                  O        O
parliamentary        O        O
majority             O        O
,                    O        O
the                  O        O
ODS                  B-ORG    B-ORG
executive            O        O
,                    O        O
led                  O        O
by                   O        O
Prime                O        O
Minister             O        O
Vaclav               B-PER    B-PER
Klaus                I-PER    I-PER
,                    O        O
had                  O        O
developed            O        O
proposals            O        O
on                   O        O
these                O        O
subjects             O        O
to                   O        O
present              O        O
at                   O        O
the                  O        O
congress             O        O
on                   O        O
Saturday             O        O
in                   O        O
the                  O        O
Czech                B-LOC    B-MISC
second               O        O
city                 O        O
Brno                 B-LOC    B-LOC
.                    O        O
--------------------------------------------------------------------------------

Sentence 922
The ODS , a party in which Klaus often tries to emulate the style of former British Prime Minister Margaret Thatcher , has been in control of Czech politics since winning general elections in 1992 .

The                  O        O
ODS                  B-ORG    B-ORG
,                    O        O
a                    O        O
party                O        O
in                   O        O
which                O        O
Klaus                B-PER    B-PER
often                O        O
tries                O        O
to                   O        O
emulate              O        O
the                  O        O
style                O        O
of                   O        O
former               O        O
British              B-MISC   B-MISC
Prime                O        O
Minister             O        O
Margaret             B-PER    B-PER
Thatcher             I-PER    I-PER
,                    O        O
has                  O        O
been                 O        O
in                   O        O
control              O        O
of                   O        O
Czech                B-LOC    B-MISC
politics             O        O
since                O        O
winning              O        O
general              O        O
elections            O        O
in                   O        O
1992                 O        O
.                    O        O
--------------------------------------------------------------------------------

Sentence 924
The party , led by the vigorously-confident Klaus , took 32 of 81 seats after late November runoff elections to the new upper house of Czech parliament .

The                  O        O
party                O        O
,                    O        O
led                  O        O
by                   O        O
the                  O        O
vigorously-confident O        O
Klaus                B-PER    B-PER
,                    O        O
took                 O        O
32                   O        O
of                   O        O
81                   O        O
seats                O        O
after                O        O
late                 O        O
November             O        O
runoff               O        O
elections            O        O
to                   O        O
the                  O        O
new                  O        O
upper                O        O
house                O        O

The `B-LOC to B-MISC` errors show that many location entities were predicted as MISC. After examining the examples, several common patterns emerged.

**The most frequent pattern involved location names used as adjectives rather than direct references to places**. The clearest example was Czech, which was repeatedly labelled as LOC in the dataset but predicted as MISC by the model in phrases such as Czech President, Czech politics, Czech parliament and Czech beer. This suggests that distinguishing between location names and nationality-related expressions can be difficult, particularly when the word is used to describe a person, organisation or object rather than a physical location.

A second pattern appeared in **sports-related articles**. Country and region names such as New Zealand, West Indies, Kanpur and Belfast were often used to refer to teams, matches or competitions rather than simply to geographical locations. This creates ambiguity, making it more difficult for the model to assign the correct entity type.

Finally, several errors occurred in **short headlines and section titles**, such as ATLANTIC DIVISION and PACIFIC DIVISION, where there was very little surrounding context. Without additional context, it becomes harder for the model to distinguish between location names and other entity types.

#### 8.3.2 Boundary Errors

In [43]:

for i, (tokens, gold_tags, pred_tags) in enumerate(zip(test_sents, eval_results["true_entity"], eval_results["pred_entity"])):

    gold_entities = get_entities(gold_tags)
    pred_entities = get_entities(pred_tags)

    print(gold_entities)

[('LOC', 2, 2), ('PER', 7, 7)]
[('PER', 0, 1)]
[('LOC', 0, 0), ('LOC', 2, 4)]
[('LOC', 0, 0), ('MISC', 6, 7), ('LOC', 15, 15)]
[('LOC', 1, 1), ('LOC', 23, 23)]
[('LOC', 0, 0), ('MISC', 16, 16), ('PER', 18, 19), ('MISC', 34, 34)]
[('PER', 0, 1)]
[('MISC', 2, 2), ('MISC', 8, 9)]
[('MISC', 3, 4), ('LOC', 10, 10)]
[('LOC', 11, 11), ('LOC', 26, 26)]
[('PER', 0, 1), ('PER', 14, 15), ('MISC', 19, 19), ('PER', 23, 24)]
[('LOC', 7, 7)]
[('PER', 1, 2), ('PER', 27, 27)]
[('PER', 0, 1), ('LOC', 4, 4)]
[('LOC', 0, 0), ('MISC', 6, 6), ('MISC', 18, 18)]
[('PER', 0, 0)]
[('LOC', 0, 0), ('PER', 2, 3), ('MISC', 9, 9)]
[('MISC', 1, 1)]
[]
[('LOC', 0, 0), ('MISC', 5, 6), ('ORG', 16, 16)]
[('LOC', 1, 1), ('LOC', 3, 3), ('LOC', 5, 6), ('LOC', 9, 9)]
[]
[('ORG', 0, 1), ('PER', 3, 3), ('LOC', 6, 6)]
[('LOC', 0, 0)]
[('LOC', 0, 0), ('PER', 2, 3)]
[('LOC', 6, 6), ('LOC', 8, 8)]
[('PER', 0, 0), ('PER', 4, 5), ('LOC', 30, 30), ('LOC', 32, 32)]
[('PER', 0, 1), ('PER', 7, 7), ('PER', 14, 15), ('LOC', 23, 23)]
[('PER', 0, 0), ('MISC', 6, 8), ('LOC', 19, 19), ('LOC', 23, 23)]
[('PER', 0, 0)]
[('MISC', 4, 5), ('PER', 12, 12)]
[]
[]
[('PER', 2, 3), ('PER', 5, 6), ('PER', 8, 9), ('PER', 11, 12), ('PER', 14, 15), ('PER', 17, 18), ('PER', 20, 21), ('PER', 23, 24), ('PER', 26, 27), ('PER', 29, 30), ('PER', 32, 33), ('PER', 35, 36), ('PER', 38, 39), ('PER', 41, 43), ('PER', 45, 46), ('PER', 48, 49), ('PER', 51, 52), ('PER', 54, 55), ('PER', 57, 58), ('PER', 60, 61), ('PER', 63, 64)]
[('LOC', 5, 5), ('LOC', 8, 8)]
[('LOC', 0, 0), ('LOC', 2, 4)]
[('LOC', 9, 9), ('MISC', 13, 14), ('LOC', 17, 17)]
[('PER', 0, 1), ('PER', 16, 17)]
[('MISC', 4, 4)]
[('PER', 1, 2), ('PER', 27, 27)]
[('LOC', 0, 0)]
[('PER', 0, 1), ('PER', 9, 10), ('PER', 17, 18)]
[('LOC', 0, 0), ('MISC', 6, 6)]
[('PER', 4, 4), ('PER', 13, 14), ('PER', 21, 21)]
[('PER', 0, 0), ('PER', 5, 5)]
[('LOC', 0, 0), ('PER', 7, 7), ('PER', 20, 21)]
[('LOC', 0, 0), ('PER', 4, 5), ('PER', 9, 10), ('PER', 14, 15), ('PER', 19, 20), ('PER', 24, 25), ('PER', 29, 30), ('PER', 34, 35), ('PER', 39, 40), ('PER', 46, 47), ('PER', 51, 52), ('PER', 56, 57), ('PER', 61, 62), ('PER', 66, 67)]
[('LOC', 0, 0), ('PER', 4, 5), ('PER', 9, 10), ('PER', 14, 15), ('PER', 19, 20), ('PER', 24, 25), ('PER', 29, 30), ('PER', 36, 37), ('PER', 41, 42), ('PER', 46, 47), ('PER', 51, 53), ('PER', 57, 58), ('PER', 64, 65), ('PER', 69, 70)]
[('MISC', 1, 2)]
[('LOC', 0, 0), ('LOC', 2, 2)]
[('MISC', 3, 4)]
[]
[]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('PER', 1, 2), ('LOC', 4, 4)]
[('MISC', 2, 3)]
[('LOC', 0, 0), ('LOC', 2, 4)]
[('MISC', 2, 3)]
[('LOC', 0, 0), ('LOC', 2, 2)]
[]
[('LOC', 0, 0), ('PER', 2, 3), ('PER', 8, 9)]
[('LOC', 0, 0), ('PER', 2, 3)]
[]
[('LOC', 0, 0), ('LOC', 2, 2)]
[('PER', 2, 3), ('PER', 6, 7)]
[]
[]
[]
[('LOC', 0, 0)]
[('LOC', 0, 0)]
[('LOC', 0, 0)]
[('LOC', 0, 0)]
[('LOC', 2, 2), ('LOC', 4, 5)]
[('MISC', 3, 3)]
[('LOC', 0, 0), ('LOC', 2, 2)]
[]
[('LOC', 4, 4), ('LOC', 6, 7)]
[]
[('LOC', 0, 0)]
[('PER', 0, 1)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1)]
[('PER', 0, 1)]
[]
[]
[]
[('PER', 2, 2), ('PER', 8, 8)]
[('PER', 0, 0), ('PER', 6, 6), ('PER', 9, 9)]
[('PER', 0, 0)]
[('LOC', 0, 1)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 6)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 6)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 6)]
[('PER', 0, 1), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 7)]
[('PER', 0, 1), ('PER', 4, 4)]
[('PER', 0, 1), ('PER', 4, 4)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 6)]
[('PER', 0, 1), ('PER', 5, 6), ('PER', 9, 9)]
[('PER', 0, 1)]
[]
[]
[]
[]
[('PER', 2, 3), ('PER', 11, 12)]
[('PER', 7, 8), ('PER', 11, 12)]
[('PER', 5, 6), ('PER', 9, 10)]
[('PER', 0, 1)]
[('LOC', 2, 2)]
[('LOC', 8, 8)]
[('MISC', 2, 4)]
[('LOC', 0, 0)]
[('MISC', 3, 5)]
[('MISC', 0, 0)]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('PER', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 0, 0), ('PER', 2, 3), ('ORG', 10, 10), ('ORG', 19, 20), ('ORG', 23, 23)]
[('PER', 0, 0), ('ORG', 9, 9), ('ORG', 23, 23), ('ORG', 25, 25), ('ORG', 31, 31)]
[('ORG', 0, 0), ('LOC', 9, 9), ('ORG', 15, 15)]
[('MISC', 4, 4), ('ORG', 13, 13)]
[('PER', 0, 0), ('MISC', 4, 4), ('MISC', 15, 15), ('ORG', 22, 22)]
[('ORG', 2, 2), ('PER', 4, 4)]
[('LOC', 0, 0)]
[('ORG', 0, 0), ('LOC', 2, 2), ('PER', 5, 6), ('ORG', 28, 29)]
[('PER', 0, 0), ('LOC', 25, 25)]
[('LOC', 24, 24)]
[('ORG', 0, 0), ('PER', 4, 4)]
[('PER', 0, 0), ('LOC', 6, 6), ('ORG', 25, 25)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 5, 5)]
[]
[]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 2), ('LOC', 4, 4)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 1), ('PER', 3, 3), ('PER', 6, 6)]
[('PER', 0, 1)]
[('LOC', 0, 0)]
[('PER', 1, 2), ('LOC', 5, 5), ('ORG', 11, 11), ('LOC', 13, 13)]
[('PER', 0, 0), ('MISC', 26, 26), ('PER', 27, 28)]
[('PER', 0, 1), ('LOC', 15, 15), ('PER', 25, 26)]
[('ORG', 1, 1), ('MISC', 14, 14), ('PER', 31, 32), ('MISC', 42, 42)]
[('ORG', 1, 1)]
[('PER', 0, 0), ('ORG', 12, 12), ('PER', 14, 15), ('LOC', 21, 21), ('MISC', 30, 31), ('LOC', 34, 35)]
[('PER', 1, 1), ('PER', 27, 27), ('LOC', 36, 36)]
[('LOC', 3, 3), ('LOC', 10, 10), ('LOC', 12, 12), ('LOC', 14, 14), ('LOC', 16, 16)]
[('ORG', 4, 4), ('LOC', 15, 15), ('PER', 17, 18), ('PER', 22, 23), ('ORG', 26, 27), ('PER', 29, 30), ('PER', 32, 33)]
[]
[('ORG', 0, 0), ('PER', 4, 5), ('LOC', 7, 7), ('PER', 12, 13), ('LOC', 15, 15), ('PER', 20, 21), ('LOC', 23, 23), ('PER', 28, 29), ('LOC', 31, 31), ('PER', 36, 37), ('LOC', 39, 39), ('PER', 44, 45), ('LOC', 47, 47), ('PER', 52, 53), ('LOC', 55, 55), ('PER', 60, 61), ('LOC', 63, 63), ('PER', 68, 69), ('LOC', 71, 71), ('PER', 76, 77), ('LOC', 79, 79), ('PER', 84, 85), ('LOC', 87, 88), ('PER', 93, 94), ('LOC', 96, 96), ('PER', 101, 102), ('LOC', 104, 104), ('PER', 109, 110), ('LOC', 112, 113), ('PER', 118, 119), ('LOC', 121, 121)]
[('LOC', 0, 0), ('PER', 4, 5), ('PER', 9, 10), ('PER', 14, 15), ('PER', 19, 20), ('PER', 27, 28), ('PER', 32, 33), ('PER', 37, 38), ('PER', 42, 43), ('PER', 47, 48), ('PER', 52, 53), ('PER', 57, 58), ('PER', 62, 63), ('PER', 67, 68), ('PER', 72, 73), ('PER', 77, 78)]
[('MISC', 2, 3)]
[('LOC', 0, 0)]
[('MISC', 6, 7), ('LOC', 11, 13), ('MISC', 17, 18), ('PER', 24, 25), ('PER', 29, 30), ('LOC', 32, 32), ('PER', 37, 39), ('PER', 43, 44), ('LOC', 46, 46), ('PER', 51, 52)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 8, 9), ('LOC', 11, 11), ('PER', 16, 17), ('PER', 21, 22), ('PER', 26, 27), ('PER', 31, 34), ('LOC', 36, 36), ('PER', 41, 41)]
[('PER', 0, 0), ('PER', 4, 5), ('PER', 9, 10)]
[('PER', 2, 3), ('PER', 7, 8), ('PER', 12, 14), ('LOC', 16, 16), ('PER', 21, 22)]
[('PER', 2, 3), ('LOC', 5, 5), ('PER', 10, 11), ('LOC', 13, 13), ('PER', 18, 19)]
[('PER', 0, 1), ('PER', 5, 6)]
[('LOC', 7, 7)]
[('LOC', 0, 0)]
[('LOC', 0, 0), ('PER', 2, 3), ('LOC', 16, 16), ('MISC', 21, 22)]
[('PER', 1, 2), ('PER', 5, 6), ('ORG', 8, 9), ('PER', 12, 13), ('ORG', 15, 16), ('MISC', 22, 22), ('LOC', 27, 27)]
[('PER', 0, 0), ('ORG', 17, 18), ('ORG', 22, 23)]
[]
[('ORG', 2, 3), ('MISC', 10, 12), ('MISC', 16, 17)]
[('PER', 2, 3), ('ORG', 9, 9), ('MISC', 11, 11), ('ORG', 13, 13)]
[]
[('PER', 2, 3), ('PER', 5, 6)]
[('PER', 2, 3), ('PER', 5, 6), ('PER', 8, 9), ('PER', 11, 12), ('PER', 14, 15), ('PER', 17, 18), ('PER', 20, 21)]
[('PER', 2, 3), ('PER', 5, 6), ('PER', 8, 9), ('PER', 11, 12), ('PER', 14, 15), ('PER', 17, 18), ('PER', 20, 21)]
[('PER', 2, 3), ('PER', 5, 6), ('PER', 8, 9), ('PER', 11, 12)]
[('ORG', 0, 0)]
[('MISC', 2, 2)]
[('LOC', 0, 2)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('ORG', 0, 0), ('ORG', 2, 3)]
[('PER', 2, 2)]
[('PER', 0, 1)]
[('LOC', 0, 0)]
[('LOC', 0, 0), ('PER', 2, 3), ('LOC', 12, 13), ('MISC', 20, 21)]
[('PER', 0, 0)]
[('LOC', 0, 0), ('LOC', 14, 15)]
[('PER', 1, 2)]
[('PER', 2, 2)]
[('PER', 7, 8)]
[('PER', 0, 0), ('PER', 18, 19)]
[('LOC', 0, 1), ('PER', 4, 5), ('PER', 9, 9)]
[('PER', 2, 2), ('LOC', 6, 6), ('PER', 8, 9), ('PER', 12, 13)]
[('LOC', 1, 1), ('LOC', 13, 14)]
[('PER', 6, 7)]
[('PER', 0, 0)]
[('LOC', 0, 0), ('LOC', 5, 5), ('MISC', 17, 18)]
[('LOC', 2, 2), ('LOC', 4, 5), ('MISC', 6, 7)]
[('LOC', 0, 0)]
[('MISC', 3, 4)]
[('LOC', 4, 4), ('LOC', 6, 7)]
[('LOC', 0, 1)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 4), ('PER', 6, 6)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1)]
[('PER', 0, 1), ('PER', 4, 4)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 5, 6)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1)]
[('PER', 0, 1)]
[]
[]
[]
[]
[('PER', 2, 2), ('PER', 8, 8)]
[('PER', 0, 0), ('PER', 3, 3), ('PER', 6, 6)]
[('PER', 0, 1)]
[('LOC', 0, 0)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1)]
[('PER', 0, 1), ('PER', 3, 3), ('PER', 5, 5)]
[('PER', 0, 1), ('PER', 3, 3)]
[('PER', 0, 1)]
[]
[]
[]
[('PER', 4, 5), ('PER', 7, 8), ('PER', 10, 11), ('PER', 13, 14)]
[('PER', 2, 2), ('PER', 9, 9)]
[('PER', 0, 0), ('PER', 7, 7), ('PER', 13, 13)]
[]
[('LOC', 2, 2)]
[('LOC', 2, 2), ('LOC', 4, 5)]
[('LOC', 0, 0)]
[('LOC', 0, 0), ('LOC', 2, 3), ('MISC', 9, 10), ('LOC', 16, 18)]
[('LOC', 2, 3), ('PER', 11, 12), ('LOC', 16, 16), ('PER', 22, 23)]
[('LOC', 2, 3), ('LOC', 11, 11)]
[('LOC', 0, 0)]
[('LOC', 0, 1), ('MISC', 12, 13), ('LOC', 18, 18)]
[('MISC', 2, 3)]
[('LOC', 0, 0), ('LOC', 2, 2)]
[('MISC', 8, 9), ('LOC', 12, 12), ('LOC', 14, 14), ('LOC', 16, 17)]
[('LOC', 0, 0), ('PER', 5, 6), ('PER', 11, 12), ('PER', 17, 18), ('ORG', 22, 22)]
[('PER', 2, 2)]
[('LOC', 0, 0)]
[('LOC', 0, 1), ('PER', 3, 4), ('MISC', 10, 10), ('LOC', 32, 32)]
[('PER', 0, 0), ('LOC', 17, 17), ('PER', 19, 20)]
[('LOC', 1, 2), ('PER', 21, 22), ('PER', 25, 26)]
[('LOC', 0, 1), ('LOC', 15, 17), ('PER', 20, 21)]
[('PER', 0, 0), ('MISC', 12, 12)]
[]
[]
[('PER', 2, 3), ('PER', 8, 8), ('LOC', 13, 13), ('PER', 15, 16)]
[('PER', 0, 0)]
[('PER', 0, 0), ('PER', 19, 19), ('LOC', 34, 34)]
[('LOC', 0, 0), ('LOC', 9, 11), ('PER', 25, 25)]
[('PER', 0, 0), ('LOC', 8, 9), ('LOC', 12, 12)]
[('LOC', 1, 2), ('LOC', 4, 4)]
[('LOC', 0, 0), ('MISC', 14, 15)]
[('LOC', 2, 3)]
[('LOC', 0, 0)]
[('LOC', 0, 1), ('PER', 3, 4), ('MISC', 18, 19), ('LOC', 24, 24), ('LOC', 27, 27)]
[]
[('LOC', 0, 0), ('PER', 2, 3), ('PER', 8, 9), ('PER', 11, 12), ('PER', 14, 15), ('PER', 17, 18), ('PER', 20, 21), ('PER', 23, 24), ('PER', 26, 27), ('PER', 29, 30), ('PER', 32, 33), ('PER', 35, 36), ('PER', 38, 39)]
[('LOC', 0, 1), ('PER', 3, 4), ('PER', 6, 7), ('PER', 9, 10), ('PER', 12, 13), ('PER', 15, 16), ('PER', 18, 19), ('PER', 21, 22), ('PER', 24, 25), ('PER', 27, 28), ('PER', 30, 31), ('PER', 33, 34), ('PER', 39, 40)]
[('MISC', 2, 4)]
[('LOC', 0, 0)]
[('MISC', 9, 11)]
[]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 8), ('LOC', 10, 10)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 8), ('LOC', 10, 10)]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 8), ('LOC', 10, 10)]
[]
[('PER', 0, 2), ('LOC', 4, 4), ('PER', 7, 8), ('LOC', 10, 10)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[('PER', 6, 7), ('LOC', 9, 9), ('PER', 12, 12)]
[('PER', 0, 0), ('LOC', 2, 2), ('PER', 5, 6), ('LOC', 8, 8), ('PER', 11, 13)]
[('LOC', 1, 1)]
[]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 6), ('LOC', 8, 8)]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[('PER', 6, 7), ('LOC', 9, 9), ('PER', 12, 13), ('LOC', 15, 15), ('PER', 18, 19), ('LOC', 21, 21), ('PER', 24, 25), ('LOC', 27, 27)]
[('MISC', 2, 2), ('MISC', 5, 9)]
[('LOC', 0, 0)]
[('MISC', 7, 11), ('LOC', 15, 16), ('ORG', 20, 21), ('LOC', 23, 23), ('ORG', 26, 26), ('LOC', 28, 28)]
[]
[('PER', 0, 1), ('PER', 7, 8)]
[]
[('ORG', 0, 0)]
[('LOC', 0, 1)]
[('ORG', 2, 3)]
[('ORG', 0, 0)]
[]
[]
[]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('LOC', 0, 0)]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[]
[('MISC', 0, 1)]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('LOC', 0, 0)]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('ORG', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0)]
[('MISC', 3, 3)]
[('LOC', 0, 1)]
[('ORG', 4, 4), ('ORG', 6, 6), ('ORG', 15, 16), ('ORG', 18, 19)]
[]
[('ORG', 2, 3)]
[('ORG', 0, 0)]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('ORG', 0, 0), ('ORG', 2, 3)]
[('ORG', 0, 1), ('ORG', 3, 3)]
[('ORG', 0, 0), ('ORG', 2, 3)]
[('ORG', 0, 1), ('ORG', 3, 4)]
[('ORG', 0, 0), ('ORG', 4, 4)]
[('LOC', 0, 0)]
[('ORG', 2, 3), ('ORG', 21, 22)]
[('PER', 0, 1), ('PER', 10, 11), ('ORG', 22, 22), ('ORG', 32, 32)]
[('PER', 0, 1), ('PER', 7, 8), ('ORG', 21, 21)]
[('LOC', 0, 0), ('LOC', 5, 6), ('LOC', 8, 8)]
[('ORG', 1, 1)]
[('LOC', 0, 0), ('ORG', 11, 12), ('ORG', 14, 15), ('ORG', 23, 25), ('ORG', 29, 29)]
[('ORG', 3, 3), ('ORG', 7, 9)]
[('ORG', 1, 1), ('PER', 11, 12), ('PER', 15, 16), ('PER', 19, 20)]
[('PER', 0, 0)]
[('PER', 0, 0), ('PER', 7, 7)]
[('PER', 0, 0)]
[('PER', 1, 2), ('ORG', 10, 11), ('ORG', 15, 15), ('PER', 30, 31)]
[('LOC', 5, 5), ('PER', 7, 8), ('PER', 11, 11)]
[('ORG', 0, 0), ('PER', 2, 3)]
[('PER', 0, 1)]
[('ORG', 0, 0)]
[('LOC', 0, 1)]
[('ORG', 2, 2)]
[('ORG', 0, 1)]
[]
[]
[('LOC', 0, 0)]
[]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[]
[]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('LOC', 0, 0)]
[]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0)]
[('LOC', 0, 1)]
[('ORG', 0, 2)]
[]
[]
[('MISC', 0, 0)]
[]
[]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[]
[('ORG', 4, 4)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[]
[]
[('MISC', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[]
[]
[]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[]
[]
[('MISC', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[]
[]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[]
[]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 1), ('LOC', 3, 4)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[('ORG', 0, 0), ('LOC', 2, 3)]
[('ORG', 0, 0), ('LOC', 2, 2)]
[]
[('ORG', 0, 1), ('LOC', 3, 3)]
[('ORG', 0, 0)]
[('LOC', 0, 1)]
[('ORG', 2, 2), ('LOC', 3, 3)]
[('LOC', 0, 0)]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('ORG', 0, 0), ('MISC', 2, 3), ('PER', 5, 5), ('MISC', 8, 9)]
[('LOC', 0, 0)]
[('ORG', 0, 1), ('PER', 4, 5), ('MISC', 13, 14), ('ORG', 19, 20), ('LOC', 22, 22)]
[('PER', 0, 0), ('ORG', 6, 7), ('MISC', 17, 18), ('ORG', 20, 21)]
[]
[('PER', 3, 3)]
[('PER', 0, 0), ('ORG', 6, 7), ('PER', 10, 11), ('ORG', 13, 14), ('PER', 17, 18), ('PER', 22, 23), ('ORG', 25, 25)]
[('MISC', 1, 2), ('PER', 27, 28), ('ORG', 34, 36)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 1), ('ORG', 3, 5)]
[]
[]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 2)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 2)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 0), ('ORG', 2, 3)]
[('ORG', 0, 1), ('ORG', 3, 4)]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('ORG', 0, 0), ('ORG', 2, 3)]
[]
[]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 2)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 2)]
[('ORG', 0, 2)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('ORG', 0, 2)]
[('ORG', 0, 1)]
[('ORG', 0, 1)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 0), ('ORG', 2, 2), ('PER', 5, 6), ('PER', 9, 10), ('PER', 13, 13)]
[('PER', 0, 0), ('PER', 3, 4)]
[]
[]
[]
[('ORG', 0, 2), ('PER', 5, 6), ('ORG', 9, 9), ('PER', 12, 13)]
[('PER', 2, 3)]
[]
[]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 1), ('ORG', 7, 9), ('PER', 12, 12)]
[('PER', 0, 2)]
[]
[]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 3, 3)]
[]
[]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 1)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('ORG', 0, 0)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 2, 2)]
[]
[('ORG', 0, 0), ('ORG', 2, 2)]
[('ORG', 0, 2), ('ORG', 4, 4)]
[('MISC', 2, 2)]
[('LOC', 0, 0)]
[('MISC', 6, 6)]
[('ORG', 0, 0), ('PER', 3, 3), ('PER', 7, 7), ('ORG', 10, 11), ('PER', 14, 14), ('PER', 17, 17)]
[]
[]
[('ORG', 0, 1), ('PER', 4, 4), ('ORG', 7, 8), ('PER', 11, 11)]
[]
[]
[('LOC', 0, 0), ('PER', 3, 3), ('PER', 6, 6), ('ORG', 9, 9), ('LOC', 12, 12)]
[]
[]
[('ORG', 0, 0), ('PER', 3, 3), ('ORG', 8, 9)]
[]
[]
[('MISC', 2, 4)]
[('LOC', 0, 0), ('LOC', 2, 2)]
[('MISC', 7, 9), ('PER', 15, 16), ('LOC', 18, 18), ('PER', 21, 22), ('LOC', 24, 24)]
[('PER', 0, 1), ('LOC', 3, 3), ('PER', 6, 7), ('LOC', 9, 9)]
[('PER', 2, 2), ('LOC', 5, 5), ('PER', 7, 7)]
[('LOC', 0, 0)]
[('LOC', 0, 0), ('ORG', 3, 3), ('PER', 6, 8), ('LOC', 13, 13), ('MISC', 16, 17), ('PER', 25, 26), ('MISC', 39, 39), ('PER', 41, 42)]
[('PER', 0, 0), ('ORG', 9, 10), ('MISC', 15, 18)]

To analyse boundary errors, I first converted the BIO tags into entity spans using the `get_entities()` function from the `seqeval` library. I then compared each predicted entity with the corresponding gold entity of the same type. 

I separated boundary errors into five categories:

* **Truncated end:** the predicted entity started at the correct position but ended early.
* **Extended end:** the predicted entity started correctly but included extra tokens at the end.
* **Truncated start:** the predicted entity ended at the correct position but started late.
* **Extended start:** the predicted entity started early but ended at the correct position.
* **Shifted** both the start and end boundaries differed from the gold entity.

I separated boundary errors into five categories to identify the most common types of boundary mistakes made by the model and better understand its prediction behaviour.

In [45]:
boundary_errors = []

for i, (tokens, gold_tags, pred_tags) in enumerate(zip(test_sents, eval_results["true_entity"], eval_results["pred_entity"])):

    gold_entities = get_entities(gold_tags)
    pred_entities = get_entities(pred_tags)

    for gold_label, gold_start, gold_end in gold_entities:
        for pred_label, pred_start, pred_end in pred_entities:

            # Only compare entities with the same type
            if gold_label != pred_label:
                continue

            # Check whether the spans overlap
            if max(gold_start, pred_start) <= min(gold_end, pred_end):

                # Ignore exact matches
                if (gold_start, gold_end) == (pred_start, pred_end):
                    continue

                # Classify the boundary error
                if pred_start == gold_start and pred_end < gold_end:
                    kind = "truncated_end"

                elif pred_start == gold_start and pred_end > gold_end:
                    kind = "extended_end"

                elif pred_start > gold_start and pred_end == gold_end:
                    kind = "truncated_start"

                elif pred_start < gold_start and pred_end == gold_end:
                    kind = "extended_start"

                else:
                    kind = "shifted"

                boundary_errors.append({
                    "kind": kind,
                    "label": gold_label,
                    "gold": " ".join(tokens[gold_start:gold_end + 1]),
                    "predicted": " ".join(tokens[pred_start:pred_end + 1]),
                    "gold_span": (gold_start, gold_end),
                    "pred_span": (pred_start, pred_end),
                    "sentence": " ".join(tokens)
                })

print(f"Total boundary errors: {len(boundary_errors)}")

Total boundary errors: 139

In [46]:
counts = Counter(error["kind"] for error in boundary_errors)
print(counts)

Counter({'truncated_end': 37, 'truncated_start': 37, 'extended_end': 32, 'extended_start': 27, 'shifted': 6})

In [52]:
boundary_errors[:2]

[{'kind': 'truncated_end',
  'label': 'MISC',
  'gold': '1995 World Cup',
  'predicted': '1995',
  'gold_span': (6, 8),
  'pred_span': (6, 6),
  'sentence': 'Cuttitta announced his retirement after the 1995 World Cup , where he took issue with being dropped from the Italy side that faced England in the pool stages .'},
 {'kind': 'truncated_start',
  'label': 'MISC',
  'gold': '1995 World Cup',
  'predicted': 'World Cup',
  'gold_span': (6, 8),
  'pred_span': (7, 8),
  'sentence': 'Cuttitta announced his retirement after the 1995 World Cup , where he took issue with being dropped from the Italy side that faced England in the pool stages .'}]

In [57]:
for error in boundary_errors:

    if error["kind"] == "truncated_end":
        print(error["label"])
        print(error["gold"])
        print(error["predicted"])
        print(error["sentence"])
        print("--" * 50)

MISC
1995 World Cup
1995
Cuttitta announced his retirement after the 1995 World Cup , where he took issue with being dropped from the Italy side that faced England in the pool stages .
----------------------------------------------------------------------------------------------------
ORG
McDonald 's
McDonald
Leeds ' England under-21 striker Lee Bowyer was fined 4,500 pounds ( $ 7,400 ) on Friday for hurling chairs at restaurant staff during a disturbance at a McDonald 's fast-food restaurant .
----------------------------------------------------------------------------------------------------
LOC
National stadium
National
Result of the second leg of the African Cup Winners ' Cup final at the National stadium on Friday : Arab Contractors ( Egypt ) 4 Sodigraf ( Zaire ) 0 ( halftime 2-0 )
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
NY
NY RANGERS 10 13 5 91 81 25
----------------------------------------------------------------------------------------------------
ORG
NY ISLANDERS
NY
NY ISLANDERS 7 11 8 65 72 22
----------------------------------------------------------------------------------------------------
LOC
Santiago Bernabeu stadium
Santiago Bernabeu
Spanish police will breathalyse fans at the gates of the Santiago Bernabeu stadium and ban drunk supporters from Saturday 's big Real Madrid-Barcelona game , the Madrid daily El Mundo said on Friday .
----------------------------------------------------------------------------------------------------
MISC
Serie A
Serie
Italian Serie A games to be played on Sunday ( league positions in parentheses , all kick- off times GMT ) :
----------------------------------------------------------------------------------------------------
ORG
Mlada Fronta Dnes
Mlada Fronta
Czech ambassador to the United Nations , Karel Kovanda , told the daily Mlada Fronta Dnes that Albright " is a little light in our diplomatic heaven , " but warned against expecting her to exert any influence in favour of the Czechs .
----------------------------------------------------------------------------------------------------
ORG
U.S. Senate Banking Committee
U.S.
Switzerland stands accused by Senator Alfonse D'Amato , chairman of the powerful U.S. Senate Banking Committee , of agreeing to give money to Poland from unclaimed bank accounts of Polish citizens , as part of an accord on compensating Swiss nationals whose assets had been seized in communist Poland .
----------------------------------------------------------------------------------------------------
ORG
Elbrewery Company Ltd.
Elbrewery Company
Earlier this year South African Breweries Ltd ( SAB ) bought strategic stakes in the unlisted Lech and Tychy brewers , which together hold more than 20 percent of the market , and Australia 's Brewpole BV has a controlling stake in Poland 's larges t brewery , Elbrewery Company Ltd. ( EB ) .
----------------------------------------------------------------------------------------------------
ORG
PT Tambang Timah
PT Tambang
PT Tambang Timah closed at $ 15.575 per GDR in London on Friday .
----------------------------------------------------------------------------------------------------
ORG
Monopolies and Mergers Commission
Monopolies
The British government warned Friday that it would refer the proposed trans-Atlantic alliance between British Airways Plc and American Airlines to Britain 's Monopolies and Mergers Commission unless the carriers complied with a number of conditions .
----------------------------------------------------------------------------------------------------
MISC
Thai Resource
Thai
Thai Resource 264 31/12 Ras Tanura / Red Sea W46.50 Mobil .
----------------------------------------------------------------------------------------------------
ORG
Russ Berrie and Co Inc
Russ Berrie
Russ Berrie and Co Inc said on Friday that A. Curts Cooke will retire as president and chief operating officer effective July 1 , 1997 .
----------------------------------------------------------------------------------------------------
ORG
RAO Norilsky Nikel
RAO
The official Itar-Tass news agency quoted Livshits as telling parliamentary deputies that RAO Norilsky Nikel 0#NKEL.RUO had to pay its tax arrears and that bankruptcy procedures applied to the metals group .
----------------------------------------------------------------------------------------------------
LOC
Gulf of Mexico
Gulf
- Gulf of Mexico :
----------------------------------------------------------------------------------------------------
MISC
German shepherds
German
The five breeds credited with the most incidents were chow chows , Rottweilers , German shepherds , cocker spaniels and Dalmatians . "
----------------------------------------------------------------------------------------------------
MISC
Learjet 36
Learjet
The pilot and co-pilot , the only two aboard , were killed in the crash of the Learjet 36 , airport manager David Snow said in a telephone interview .
----------------------------------------------------------------------------------------------------
LOC
Republic of Padania
Republic of
A three-day " independence " march along the Po River in September , culminating in a declaration in Venice of a self-styled " Republic of Padania " , flopped badly .
----------------------------------------------------------------------------------------------------
ORG
PT Tambang Timah
PT
PT Tambang Timah was traded at $ 15.625 per GDR in London on Friday at around 0931 GMT .
----------------------------------------------------------------------------------------------------
ORG
Civil Aviation Administration of China
Civil Aviation Administration
An assessment group made up of the State Council 's Port Office , the Civil Aviation Administration of China , the General Administration of Customs and other authorities had granted the airport permission to handle foreign aircraft , Xinhua said .
----------------------------------------------------------------------------------------------------
ORG
Mines and Energy Ministry
Mines
Both sources said Bre-X and Barrick did not hold talks on Thursday with Mines and Energy Ministry Secretary-General Umar Said , who is coordinating the negotiations over the Busang find in East Kalimantan .
----------------------------------------------------------------------------------------------------
ORG
Indonesian Mines and Energy Ministry
Indonesian Mines
The first source also said Bre-X had until December 21 to submit to the Indonesian Mines and Energy Ministry a feasibility study on the central region of the Busang property , estimated to contain 2.6 million ounces of gold .
----------------------------------------------------------------------------------------------------
ORG
Mines and Energy Ministry
Mines
The source said no new deadline had been set by the Mines and Energy Ministry for Bre-X and Barrick to strike a deal .
----------------------------------------------------------------------------------------------------
MISC
Nation 's Cup
Nation
Nation 's Cup standings :
----------------------------------------------------------------------------------------------------
MISC
World cup
World
Canada I , represented by Pierre Lueders and breakman Dave MacEachern , completed the third World cup event of the winter a further one-hundredth of a second behind the Italians .
----------------------------------------------------------------------------------------------------
MISC
SCOTTISH PREMIER DIVISION
SCOTTISH
SOCCER - LEADING SCOTTISH PREMIER DIVISION SCORERS .
----------------------------------------------------------------------------------------------------
MISC
Scottish premier
Scottish
Scottish premier division after Saturday 's matches :
----------------------------------------------------------------------------------------------------
PER
Kim Byung Ji
Kim Byung
South Korea : 1 - Kim Byung Ji ; 2 - Kim Pan Keun ; 5 - Huh Ki Tae ; 8 - Roh Sang Rae ( 7 - Sin Tae Yong 33 ) ; 9 - Kim Do Hoon ; 11 - Ko Jeong Woon ; 17 - Ha Seok Ju ; 18 - Hwang Sun Hong ; 22 - Lee Young Jin ; 23 - Yoo Sang Chul ; 24 - Kim Joo Sung .
----------------------------------------------------------------------------------------------------
PER
Kim Pan Keun
Kim Pan
South Korea : 1 - Kim Byung Ji ; 2 - Kim Pan Keun ; 5 - Huh Ki Tae ; 8 - Roh Sang Rae ( 7 - Sin Tae Yong 33 ) ; 9 - Kim Do Hoon ; 11 - Ko Jeong Woon ; 17 - Ha Seok Ju ; 18 - Hwang Sun Hong ; 22 - Lee Young Jin ; 23 - Yoo Sang Chul ; 24 - Kim Joo Sung .
----------------------------------------------------------------------------------------------------
PER
Lee Young Jin
Lee Young
South Korea : 1 - Kim Byung Ji ; 2 - Kim Pan Keun ; 5 - Huh Ki Tae ; 8 - Roh Sang Rae ( 7 - Sin Tae Yong 33 ) ; 9 - Kim Do Hoon ; 11 - Ko Jeong Woon ; 17 - Ha Seok Ju ; 18 - Hwang Sun Hong ; 22 - Lee Young Jin ; 23 - Yoo Sang Chul ; 24 - Kim Joo Sung .
----------------------------------------------------------------------------------------------------
PER
Hwang Sun Hong
Hwang Sun
South Korea - Kim Do Hoon 5 , Hwang Sun Hong 7 and 15 , Koo
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
NY
NY RANGERS 11 13 5 97 86 27
----------------------------------------------------------------------------------------------------
ORG
NY ISLANDERS
NY
NY ISLANDERS 7 11 8 65 72 22
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
NY
NY RANGERS 6 Toronto 5
----------------------------------------------------------------------------------------------------
PER
Axel Schulz
Axel
German Axel Schulz outpointed Cuba 's Jose Ribalta in their International Boxing Federation non-title 10-round heavyweight fight on Saturday .
----------------------------------------------------------------------------------------------------
MISC
1966 World Cup
1966
The lanky former Leeds United defender did not make his England debut until the age of 30 but eventually won 35 caps and was a key member of the 1966 World Cup winning team with his younger brother , Bobby .
----------------------------------------------------------------------------------------------------

The most common boundary error was `truncated end`.

For example, the model predicted "1995" instead of "1995 World Cup", "Santiago Bernabeu" instead of "Santiago Bernabeu stadium", and "Civil Aviation Administration" instead of "Civil Aviation Administration of China". 

Similar errors also occurred for personal names, "Kim Byung" instead of "Kim Byung Ji", and for organisation names, "Mlada Fronta" instead of "Mlada Fronta Dnes". 

***These examples suggest that the model struggled to determine its complete ending, particularly for longer multi-word entities.***

In [58]:
for error in boundary_errors:

    if error["kind"] == "extended_end":
        print(error["label"])
        print(error["gold"])
        print(error["predicted"])
        print(error["sentence"])
        print("--" * 50)

LOC
Melbourne
Melbourne Cricket Ground
West Indies captain Courtney Walsh elected to bat after winning the toss in the first match in the World Series limited overs competition against Australia at the Melbourne Cricket Ground on Friday .
----------------------------------------------------------------------------------------------------
MISC
AMERICAN
AMERICAN FOOTBALL CONFERENCE
AMERICAN FOOTBALL CONFERENCE
----------------------------------------------------------------------------------------------------
ORG
Rotary Club
Rotary Club of Houston
Ohio State left tackle Orlando Pace became the first repeat winner of the Lombardi Award Thursday night when the Rotary Club of Houston again honoured him as college football 's lineman of the year .
----------------------------------------------------------------------------------------------------
ORG
Barcelona
Barcelona Real Madrid
25-1 Barcelona Real Madrid
----------------------------------------------------------------------------------------------------
ORG
Barcelona
Barcelona Barcelona
4-1 Barcelona Barcelona
----------------------------------------------------------------------------------------------------
ORG
Real Madrid
Real Madrid Barcelona
Real Madrid Barcelona
----------------------------------------------------------------------------------------------------
ORG
Sporting
Sporting Gijon
Sporting Gijon 15 4 4 7 15 22 16
----------------------------------------------------------------------------------------------------
ORG
Social Democratic Union
Social Democratic Union and the Hungarian Democratic Union
* The Democratic Convention signed an agreement on government and parliamentary support with its coalition partners the Social Democratic Union and the Hungarian Democratic Union ( UDMR ) .
----------------------------------------------------------------------------------------------------
ORG
Lech
Lech and Tychy
Earlier this year South African Breweries Ltd ( SAB ) bought strategic stakes in the unlisted Lech and Tychy brewers , which together hold more than 20 percent of the market , and Australia 's Brewpole BV has a controlling stake in Poland 's larges t brewery , Elbrewery Company Ltd. ( EB ) .
----------------------------------------------------------------------------------------------------
ORG
Zywiec
Zywiec Full Light
He said his firm would be better off concentrating on its leading brand , Zywiec Full Light , which accounts for 85 percent of sales and is the country 's largest-selling brand .
----------------------------------------------------------------------------------------------------
ORG
British Airways
British Airways /
The Office of Fair Trade called for British Airways / American to allow third-party access to their joint frequent flyer programme where the applicant does not have access to an equivalent programme .
----------------------------------------------------------------------------------------------------
ORG
New York Commodities
New York Commodities Desk
-- New York Commodities Desk +1 212 859 1640
----------------------------------------------------------------------------------------------------
ORG
New York Commodities
New York Commodities Desk
-- New York Commodities Desk , 212-859-1640
----------------------------------------------------------------------------------------------------
LOC
Bratislava
Bratislava Rabbi
Skinheads attack Bratislava Rabbi - police .
----------------------------------------------------------------------------------------------------
MISC
Soviet-led
Soviet-led Warsaw Pact
Russia opposes NATO 's plans to take in countries of eastern and central Europe which used to be part of the Soviet-led Warsaw Pact , saying such moves would threaten its security .
----------------------------------------------------------------------------------------------------
ORG
WTO
WTO secretariat
Speaking to ICFTU delegates , Richard Eglin , director of the WTO secretariat , said the WTO was capable of making a significant contribution to governmental efforts to solve social problems .
----------------------------------------------------------------------------------------------------
ORG
U.S. Treasury
U.S. Treasury Secretary
" I think his views on ( U.S. Treasury Secretary Robert ) Rubin 's comments were indeed what he himself thinks about the dollar , " said Hank Note , chief dealer at Sumitomo Bank .
----------------------------------------------------------------------------------------------------
MISC
Christian-Shi'ite
Christian-Shi'ite Moslem
Israel and Lahd have repeatedly demanded safety guarantees for the SLA -- a mixed Christian-Shi'ite Moslem force -- which the Jewish states regards as loyal allies .
----------------------------------------------------------------------------------------------------
ORG
FSA
FSA INSURED
FSA INSURED
----------------------------------------------------------------------------------------------------
PER
John Mills
John Mills Jr
Fourteen years after he bludgeoned and shot a man whose trailer home he robbed in 1982 , John Mills Jr .
----------------------------------------------------------------------------------------------------
ORG
NYMEX
NYMEX Henry Hub
NYMEX Henry Hub natgas futures settled significantly lower Friday , pressured early by profit taking and driven even lower late by the National Weather Service 's bearish six to 10 day forecast , sources said .
----------------------------------------------------------------------------------------------------
MISC
German
German Bunds
German Bunds were not much better , offering returns of 0.05 percent , while Japanese government bonds managed a 0.38 percent gain .
----------------------------------------------------------------------------------------------------
LOC
Po
Po River
A three-day " independence " march along the Po River in September , culminating in a declaration in Venice of a self-styled " Republic of Padania " , flopped badly .
----------------------------------------------------------------------------------------------------
ORG
National
National and Labour
New Zealand First leader Winston Peters on Friday said coalition talks with the National and Labour parties were at a similar level of completion .
----------------------------------------------------------------------------------------------------
ORG
NZ First
NZ First and National
Peters left a meeting between NZ First and National negotiators to spend 20 minutes speaking to Labour leader Helen Clark .
----------------------------------------------------------------------------------------------------
ORG
Labour
Labour and National
Peters said the talks with Labour and National had reached " about the same level of completion , and that 's good " .
----------------------------------------------------------------------------------------------------
ORG
State Council
State Council 's Port Office
An assessment group made up of the State Council 's Port Office , the Civil Aviation Administration of China , the General Administration of Customs and other authorities had granted the airport permission to handle foreign aircraft , Xinhua said .
----------------------------------------------------------------------------------------------------
ORG
Citra Group
Citra Group of Suharto
Barrick has teamed up with a construction company in the Citra Group of Suharto 's eldest daughter , Siti Hardianti Rukmana , in what Barrick had said was a partnership " to prepare us for a potential mining development project " .
----------------------------------------------------------------------------------------------------
MISC
World Cup
World Cup Super G
Svetlana Gladishiva of Russia won the women 's World Cup Super G race on Saturday .
----------------------------------------------------------------------------------------------------
ORG
LPGA
LPGA Tours
The final round of the special event , which pairs players from the PGA and LPGA Tours , will be played in the alternate shot format on Sunday .
----------------------------------------------------------------------------------------------------
ORG
Ironi Rishon
Ironi Rishon Lezion
Ironi Rishon Lezion 12 4 1 7 13 24 13
----------------------------------------------------------------------------------------------------
ORG
Sporting
Sporting Gijon
Sporting Gijon 15 4 4 7 15 22 16
----------------------------------------------------------------------------------------------------

The second main boundary error was **extended end**. 

For example, it predicted **“Melbourne Cricket Ground”** instead of **“Melbourne”**, **“Rotary Club of Houston”** instead of **“Rotary Club”**, and **“U.S. Treasury Secretary”** instead of **“U.S. Treasury”**. 

Similar errors also occurred when the model joined two separate entities, **“Lech and Tychy”** instead of **“Lech”**, and **“Labour and National”** instead of **“Labour”**. 

In some cases, the added token was a role or description, **“Bratislava Rabbi”** instead of **“Bratislava”** and **“WTO secretariat”** instead of **“WTO”**. 

***These examples show that the model had difficulty deciding where the entity should end, especially when another name, title, or descriptive word followed it.***

In [59]:
for error in boundary_errors:

    if error["kind"] == "truncated_start":
        print(error["label"])
        print(error["gold"])
        print(error["predicted"])
        print(error["sentence"])
        print("--" * 50)

MISC
1995 World Cup
World Cup
Cuttitta announced his retirement after the 1995 World Cup , where he took issue with being dropped from the Italy side that faced England in the pool stages .
----------------------------------------------------------------------------------------------------
PER
Franco Properzi Curti
Properzi Curti
Squad : Javier Pertile , Paolo Vaccari , Marcello Cuttitta , Ivan Francescato , Leandro Manteri , Diego Dominguez , Francesco Mazzariol , Alessandro Troncon , Orazio Arancio , Andrea Sgorlon , Massimo Giovanelli , Carlo Checchinato , Walter Cristofoletto , Franco Properzi Curti , Carlo Orlandi , Massimo Cuttitta , Giambatista Croci , Gianluca Guidi , Nicola Mazzucato , Alessandro Moscardi , Andrea Castellani .
----------------------------------------------------------------------------------------------------
PER
Nihad al-Boushi
al-Boushi
Syria : 24 - Salem Bitar , 3 - Bachar Srour ; 4 - Hassan Abbas , 5 - Tarek Jabban , 6 - Ammar Awad ( 9 - Louay Taleb 69 ) , 8 - Nihad al-Boushi , 10 - Mohammed Afash , 12 - Ali Dib , 13 - Abdul Latif Helou ( 17 - Ammar Rihawiy 46 ) , 14 - Khaled Zaher ; 16 - Nader Jokhadar .
----------------------------------------------------------------------------------------------------
PER
Nader Jokhadar
Jokhadar
Syria : 24 - Salem Bitar , 3 - Bachar Srour ; 4 - Hassan Abbas , 5 - Tarek Jabban , 6 - Ammar Awad ( 9 - Louay Taleb 69 ) , 8 - Nihad al-Boushi , 10 - Mohammed Afash , 12 - Ali Dib , 13 - Abdul Latif Helou ( 17 - Ammar Rihawiy 46 ) , 14 - Khaled Zaher ; 16 - Nader Jokhadar .
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
RANGERS
NY RANGERS 10 13 5 91 81 25
----------------------------------------------------------------------------------------------------
ORG
NY ISLANDERS
ISLANDERS
NY ISLANDERS 7 11 8 65 72 22
----------------------------------------------------------------------------------------------------
ORG
NY GIANTS
GIANTS
NY GIANTS AT MIAMI
----------------------------------------------------------------------------------------------------
ORG
1. FC Cologne
FC Cologne
1. FC Cologne 16 8 2 6 31 27 26
----------------------------------------------------------------------------------------------------
ORG
REAL MADRID
MADRID
SOCCER SHOWCASE-BETTING ON REAL MADRID V BARCELONA .
----------------------------------------------------------------------------------------------------
ORG
U.S. Senate Banking Committee
Senate Banking Committee
Switzerland stands accused by Senator Alfonse D'Amato , chairman of the powerful U.S. Senate Banking Committee , of agreeing to give money to Poland from unclaimed bank accounts of Polish citizens , as part of an accord on compensating Swiss nationals whose assets had been seized in communist Poland .
----------------------------------------------------------------------------------------------------
ORG
Zaklady Piwowarskie w Zywcu SA
Zywcu SA
So far this year Zywiec , whose full name is Zaklady Piwowarskie w Zywcu SA , has netted six million zlotys on sales of 224 million zlotys .
----------------------------------------------------------------------------------------------------
ORG
Irish Republican Army
Republican Army
A woman was charged on Friday with terrorist offences after three Irish Republican Army mortar bombs were found in a Belfast house , police said .
----------------------------------------------------------------------------------------------------
ORG
Monopolies and Mergers Commission
Mergers Commission
The British government warned Friday that it would refer the proposed trans-Atlantic alliance between British Airways Plc and American Airlines to Britain 's Monopolies and Mergers Commission unless the carriers complied with a number of conditions .
----------------------------------------------------------------------------------------------------
ORG
Goldman , Sachs
, Sachs
A city official , who declined to be named , explained that Goldman , Sachs , which this summer was demoted to the second tier of the syndicate , proposed the floating rate issue and as a result was promoted to book runner for this offering .
----------------------------------------------------------------------------------------------------
ORG
Placer Dome Inc
Dome Inc
Placer Dome Inc too was considered unlikley because it is focusing on geographic expansion in areas that do match Santa Fe 's Nevada , South America and Central Asia presence , they said .
----------------------------------------------------------------------------------------------------
ORG
Russ Berrie and Co Inc
Co Inc
Russ Berrie and Co Inc said on Friday that A. Curts Cooke will retire as president and chief operating officer effective July 1 , 1997 .
----------------------------------------------------------------------------------------------------
PER
A. Curts Cooke
Curts Cooke
Russ Berrie and Co Inc said on Friday that A. Curts Cooke will retire as president and chief operating officer effective July 1 , 1997 .
----------------------------------------------------------------------------------------------------
LOC
Gulf of Mexico
Mexico
- Gulf of Mexico :
----------------------------------------------------------------------------------------------------
PER
Aung San Suu Kyi
San Suu Kyi
On Tuesday and Wednesday , opposition leader Aung San Suu Kyi was restricted to her home by the military government to prevent her from being drawn into the protests .
----------------------------------------------------------------------------------------------------
PER
Yuhanna Abdullah Muhammed
Abdullah Muhammed
Prison officials said they had no record of Mills ' official conversion , but they said that , on May 14 , 1991 , he had asked that a new name , Yuhanna Abdullah Muhammed , be added to his prison file , which is usually an indication of a conversion to Islam .
----------------------------------------------------------------------------------------------------
ORG
Coe and Clerici
Clerici
Royal Clipper - 77,000 tonnes coal Maracaibo / Fos 19/12-2/1 $ 9.90 fio 20,000 shinc / 25,000 shinc Coe and Clerici .
----------------------------------------------------------------------------------------------------
MISC
Lucky Emdldm
Emdldm
Lucky Emdldm 20/11/96 5,000 Japan
----------------------------------------------------------------------------------------------------
ORG
Mines and Energy Ministry
Energy Ministry
Both sources said Bre-X and Barrick did not hold talks on Thursday with Mines and Energy Ministry Secretary-General Umar Said , who is coordinating the negotiations over the Busang find in East Kalimantan .
----------------------------------------------------------------------------------------------------
ORG
Indonesian Mines and Energy Ministry
Energy Ministry
The first source also said Bre-X had until December 21 to submit to the Indonesian Mines and Energy Ministry a feasibility study on the central region of the Busang property , estimated to contain 2.6 million ounces of gold .
----------------------------------------------------------------------------------------------------
ORG
Mines and Energy Ministry
Energy Ministry
The source said no new deadline had been set by the Mines and Energy Ministry for Bre-X and Barrick to strike a deal .
----------------------------------------------------------------------------------------------------
PER
Siti Hardianti Rukmana
Hardianti Rukmana
Barrick has teamed up with a construction company in the Citra Group of Suharto 's eldest daughter , Siti Hardianti Rukmana , in what Barrick had said was a partnership " to prepare us for a potential mining development project " .
----------------------------------------------------------------------------------------------------
MISC
1993 World Cup
World Cup
Other facts : As a qualifier for the 1993 World Cup finals through Europa Cup results , 16-year-old Goetschl won the slalom to become history 's youngest World Cup victor .
----------------------------------------------------------------------------------------------------
MISC
Nation 's Cup
Cup
Nation 's Cup standings :
----------------------------------------------------------------------------------------------------
MISC
WORLD GRAND PRIX
GRAND PRIX
BADMINTON - WORLD GRAND PRIX SEMIFINAL RESULTS .
----------------------------------------------------------------------------------------------------
PER
Hendro Kartiko
Kartiko
Indonesia : 20 - Hendro Kartiko ; 2 - Agung Setyabudi ; 3 - Suwandi Siswoyo ; 4 - Yeyen Tumera ; 5 - Aples Tecuari ; 6 - Sudiriman ; 7 - Widodo Gahyo Purta ; 8 - Ronny Wabia ; 11 - Bima Sakti ; 12 - Chris Yarangga ( 15 - Francis Wewengken 36 ) ; 16 - Marzuki Badriawan .
----------------------------------------------------------------------------------------------------
PER
Kim Joo Sung
Joo Sung
South Korea : 1 - Kim Byung Ji ; 2 - Kim Pan Keun ; 5 - Huh Ki Tae ; 8 - Roh Sang Rae ( 7 - Sin Tae Yong 33 ) ; 9 - Kim Do Hoon ; 11 - Ko Jeong Woon ; 17 - Ha Seok Ju ; 18 - Hwang Sun Hong ; 22 - Lee Young Jin ; 23 - Yoo Sang Chul ; 24 - Kim Joo Sung .
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
RANGERS
NY RANGERS 11 13 5 97 86 27
----------------------------------------------------------------------------------------------------
ORG
NY ISLANDERS
ISLANDERS
NY ISLANDERS 7 11 8 65 72 22
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
RANGERS
NY RANGERS AT TORONTO
----------------------------------------------------------------------------------------------------
ORG
NY RANGERS
RANGERS
NY RANGERS 6 Toronto 5
----------------------------------------------------------------------------------------------------
PER
Predrag Mijatovic
Mijatovic
Real Madrid 's Balkan strike force of Davor Suker and Predrag Mijatovic shot their side to a 2-0 win over Barcelona in Spain 's old firm game on Saturday .
----------------------------------------------------------------------------------------------------
MISC
1966 World Cup
World Cup
The lanky former Leeds United defender did not make his England debut until the age of 30 but eventually won 35 caps and was a key member of the 1966 World Cup winning team with his younger brother , Bobby .
----------------------------------------------------------------------------------------------------

The **truncated start** error was common across different entity types. 

For example, the model predicted **"World Cup"** instead of **"1995 World Cup"**, **"Senate Banking Committee"** instead of **"U.S. Senate Banking Committee"**, and **"Energy Ministry"** instead of **"Mines and Energy Ministry"**. 

Similar errors were also observed for personal names, **"San Suu Kyi"** instead of **"Aung San Suu Kyi"**, **"Curts Cooke"** instead of **"A. Curts Cooke"**, and **"Hardianti Rukmana"** instead of **"Siti Hardianti Rukmana"**.

In addition, the model frequently omitted abbreviations or prefixes from organisation names, for example predicting **"RANGERS"** instead of **"NY RANGERS"**, and **"FC Cologne"** instead of **"1. FC Cologne"**. 

***These examples suggest that the model often ignored leading modifiers, abbreviations, numbers, or titles that formed part of the complete entity name.***

In [60]:
for error in boundary_errors:

    if error["kind"] == "extended_start":
        print(error["label"])
        print(error["gold"])
        print(error["predicted"])
        print(error["sentence"])
        print("--" * 50)

ORG
Real Madrid
Madrid Real Madrid
5-2 Real Madrid Real Madrid
----------------------------------------------------------------------------------------------------
ORG
Barcelona
Madrid Barcelona
28-1 Real Madrid Barcelona
----------------------------------------------------------------------------------------------------
ORG
Real Madrid
Barcelona Real Madrid
25-1 Barcelona Real Madrid
----------------------------------------------------------------------------------------------------
ORG
Barcelona
Barcelona Barcelona
4-1 Barcelona Barcelona
----------------------------------------------------------------------------------------------------
ORG
Barcelona
Real Madrid Barcelona
Real Madrid Barcelona
----------------------------------------------------------------------------------------------------
PER
Kennet Andersson
Swede Kennet Andersson
Led as usual by Swede Kennet Andersson and Russian Igor Kolyvanov in attack , Bologna can expect a tough home match against a Piacenza side still exultant after a 3-2 league win over AC Milan last Sunday .
----------------------------------------------------------------------------------------------------
ORG
Hungarian Democratic Union
Social Democratic Union and the Hungarian Democratic Union
* The Democratic Convention signed an agreement on government and parliamentary support with its coalition partners the Social Democratic Union and the Hungarian Democratic Union ( UDMR ) .
----------------------------------------------------------------------------------------------------
PER
Boxmeer
van Boxmeer
" The perspective on growth is such that reasonably we can think that somewhere between 65 and 80 litres per year is certainly reachable , " van Boxmeer said on Polish per-capita beer consumption , currently around 40 litres .
----------------------------------------------------------------------------------------------------
ORG
Tychy
Lech and Tychy
Earlier this year South African Breweries Ltd ( SAB ) bought strategic stakes in the unlisted Lech and Tychy brewers , which together hold more than 20 percent of the market , and Australia 's Brewpole BV has a controlling stake in Poland 's larges t brewery , Elbrewery Company Ltd. ( EB ) .
----------------------------------------------------------------------------------------------------
PER
Boxmeer
van Boxmeer
Some analysts say cheaper but high-quality Czech imports could invade Poland once tariffs for CEFTA countries are lifted in 1998 , but van Boxmeer says such a threat might be exaggerated despite the Czech beer market 's overcapacity .
----------------------------------------------------------------------------------------------------
PER
Boxmeer
van Boxmeer
" You will not win the war of the Polish beer market with imported international brands , " van Boxmeer said , adding that Heineken would remain an up-market import in Poland .
----------------------------------------------------------------------------------------------------
ORG
Department of Transport
UK Department of Transport
The UK Department of Transport on Friday said that the latest round of " open skies " talks with the U.S. had ended with no deal on liberalising the transatlantic flight market and no date set for when talks would restart .
----------------------------------------------------------------------------------------------------
PER
John Paul
Pope John Paul
Poland 's ex-communist President Aleksander Kwasniewski is likely to visit Polish-born Pope John Paul in early 1997 despite uneasy relations between the Vatican and Warsaw , the foreign minister said on Friday .
----------------------------------------------------------------------------------------------------
ORG
Tallinna Pank
Estonian Tallinna Pank
Estonian Tallinna Pank 11-mo net 46.6 mln kroons .
----------------------------------------------------------------------------------------------------
MISC
Warsaw Pact
Soviet-led Warsaw Pact
Russia opposes NATO 's plans to take in countries of eastern and central Europe which used to be part of the Soviet-led Warsaw Pact , saying such moves would threaten its security .
----------------------------------------------------------------------------------------------------
MISC
Turkish
Ottoman Turkish
Some residents of the Kazanluk area are Moslems who converted to Islam during Ottoman Turkish rule .
----------------------------------------------------------------------------------------------------
MISC
Moslem
Christian-Shi'ite Moslem
Israel and Lahd have repeatedly demanded safety guarantees for the SLA -- a mixed Christian-Shi'ite Moslem force -- which the Jewish states regards as loyal allies .
----------------------------------------------------------------------------------------------------
ORG
U.S. Court of Appeals
Circuit U.S. Court of Appeals
On Thursday , the 11th Circuit U.S. Court of Appeals in Atlanta denied his appeal in federal court .
----------------------------------------------------------------------------------------------------
MISC
Permian
NYMEX Permian
NYMEX Permian natgas , also untraded , ended 10 cents lower at $ 2.90 .
----------------------------------------------------------------------------------------------------
ORG
Labour
National and Labour
New Zealand First leader Winston Peters on Friday said coalition talks with the National and Labour parties were at a similar level of completion .
----------------------------------------------------------------------------------------------------
ORG
National
NZ First and National
Peters left a meeting between NZ First and National negotiators to spend 20 minutes speaking to Labour leader Helen Clark .
----------------------------------------------------------------------------------------------------
ORG
National
Labour and National
Peters said the talks with Labour and National had reached " about the same level of completion , and that 's good " .
----------------------------------------------------------------------------------------------------
ORG
Commerce Ministry
Thai Commerce Ministry
The Thai Commerce Ministry detailed rice loading at Thai ports as follows ( in tonnes ) :
----------------------------------------------------------------------------------------------------
MISC
Winter Olympics
Lillehammer Winter Olympics
Other Facts : Gladishiva won a silver medal in super G at the 1994 Lillehammer Winter Olympics and a bronze medal in downhill at the 1991 World Championships .
----------------------------------------------------------------------------------------------------
MISC
World Championships
1991 World Championships
Other Facts : Gladishiva won a silver medal in super G at the 1994 Lillehammer Winter Olympics and a bronze medal in downhill at the 1991 World Championships .
----------------------------------------------------------------------------------------------------
PER
Masnada
Florence Masnada
10= Florence Masnada ( France ) 51
----------------------------------------------------------------------------------------------------
PER
Masnada
Florence Masnada
11. Florence Masnada ( France ) 133
----------------------------------------------------------------------------------------------------

The **extended start** error predicted `Swede Kennet Andersson` instead of `Kennet Andersson`, `UK Department of Transport` instead of `Department of Transport`, and `Pope John Paul` instead of `John Paul`. 

Similar errors also appeared when the model added nationality, location, title, or descriptive information, such as `Estonian Tallinna Pank` instead of `Tallinna Pank`, `Thai Commerce Ministry` instead of `Commerce Ministry`, and `Soviet-led Warsaw Pact` instead of `Warsaw Pact`. 

In some cases, the model also joined a previous organisation with the correct one, for example predicting `Lech and Tychy` instead of `Tychy` and `National and Labour` instead of `Labour`. 

***These examples suggest that the model often found the correct entity but included nearby modifiers or neighbouring entity tokens at the beginning.***